### ISSUE TITLE
(Monk Mistweaver) Soothing Mist gets canceled when casting to party frame.

### ISSUE THREAD

**Issue by NoobTaco** [Snakybo/Clicked#10]
**Expected Results:** Soothing Mist spell is a channeled spell that allows for the use of Enveloping Mist and Vivify to be cast while channeling Soothing Mist. Soothing mist should not stop the channeled cast while casting the other spells.

**Actual Results:** If you mouse over a party member and start to cast Soothing Mist the cast gets broken when you try to cast Vivify. 

**Steps**

1.  Target player unitframe and cast Soothing Mist
2.  While channeling Soothing Mist cast Enveloping Mist.
3. Observe that soothing mist continues to cast while Enveloping mist is cast.
4. Target party frame (default UI and Elv UI both tested) and cast Soothing Mist.
5. While channeling Soothing Mist cast Enveloping Mist.
6. Observe that soothing mist STOPS casting to cast Enveloping mist.

**Comment by Snakybo** [comment]
Thanks for the detailed report!

I'm not able to reproduce this on my Monk though, how are your bindings set up? I'm testing it with this configuration for both SM and EM:

![image](https://user-images.githubusercontent.com/3172140/96616633-fb2fac80-1302-11eb-9311-bf2e078b43e1.png)
![image](https://user-images.githubusercontent.com/3172140/96616713-008cf700-1303-11eb-8345-6e58fea0e613.png)

Enabling the "interrupt current cast" toggle on EM does cause it to stop casting SM, but that shouldn't change the behavior between player frame and party frames. Could you post the contents of `/cc dump` as well? That will include information on the macro it generates.

**Comment by NoobTaco** [comment]
This is odd. It worked for a little bit then I flipped a check box on and off for interupt and now its not working again.

![image](https://user-images.githubusercontent.com/1172935/96620233-08757880-12bc-11eb-9c10-b354f5486964.png)
![image](https://user-images.githubusercontent.com/1172935/96620279-19be8500-12bc-11eb-884d-dc2aa5e9307d.png)

Short demo
https://www.youtube.com/watch?v=kjHNzPNUIr8

`Version: 0.9.0
Race: Dwarf
Level: 28
Class: Monk
Specialization: Mistweaver
Talents: 1/1 2/2
Mode: AnyUp

----- Loaded binding 1 -----
Keybind: ALT-CTRL-SHIFT-BUTTON2
Hovercast: true
Action: menu
Attribute-alt-ctrl-shift-type2: menu

----- Loaded binding 2 -----
Keybind: BUTTON2
Hovercast: true
Action: macro
Data: /click ClickedStopCastingButton
Data: /use [@mouseover] Soothing Mist
Attribute-type2: macro
Attribute-macrotext2: /click ClickedStopCastingButton
Attribute-macrotext2: /use [@mouseover] Soothing Mist

----- Loaded binding 3 -----
Keybind: ALT-BUTTON1
Hovercast: false
Action: macro
Data: /click ClickedStopCastingButton
Data: /use Life Cocoon
Attribute-macrotext: /click ClickedStopCastingButton
Attribute-macrotext: /use Life Cocoon
Attribute-type: macro

----- Loaded binding 4 -----
Keybind: BUTTON1
Hovercast: true
Action: macro
Data: /click ClickedStopCastingButton
Data: /use [@mouseover,help,nodead] Renewing Mist
Attribute-type1: macro
Attribute-macrotext1: /click ClickedStopCastingButton
Attribute-macrotext1: /use [@mouseover,help,nodead] Renewing Mist

----- Loaded binding 5 -----
Keybind: SHIFT-BUTTON1
Hovercast: false
Action: macro
Data: /click ClickedStopCastingButton
Data: /use Enveloping Mist
Attribute-macrotext: /click ClickedStopCastingButton
Attribute-macrotext: /use Enveloping Mist
Attribute-type: macro

----- Loaded binding 6 -----
Keybind: CTRL-BUTTON1
Hovercast: false
Action: macro
Data: /click ClickedStopCastingButton
Data: /use Detox
Attribute-macrotext: /click ClickedStopCastingButton
Attribute-macrotext: /use Detox
Attribute-type: macro

----- Loaded binding 7 -----
Keybind: SHIFT-BUTTON2
Hovercast: false
Action: macro
Data: /click ClickedStopCastingButton
Data: /use Vivify
Attribute-macrotext: /click ClickedStopCastingButton
Attribute-macrotext: /use Vivify
Attribute-type: macro

----- Loaded binding 8 -----
Keybind: ALT-CTRL-SHIFT-BUTTON1
Hovercast: true
Action: target
Attribute-alt-ctrl-shift-type1: target

----- Loaded binding 9 -----
Keybind: SHIFT-MOUSEWHEELUP
Hovercast: false
Action: macro
Data: /click ClickedStopCastingButton
Data: /use Reawaken
Attribute-macrotext: /click ClickedStopCastingButton
Attribute-macrotext: /use Reawaken
Attribute-type: macro

----- Hovercast attributes -----
Attribute-macrotext2: /click ClickedStopCastingButton
Attribute-macrotext2: /use [@mouseover] Soothing Mist
Attribute-shift-macrotext1: /click ClickedStopCastingButton
Attribute-shift-macrotext1: /use Enveloping Mist
Attribute-type1: macro
Attribute-ctrl-macrotext1: /click ClickedStopCastingButton
Attribute-ctrl-macrotext1: /use Detox
Attribute-alt-macrotext1: /click ClickedStopCastingButton
Attribute-alt-macrotext1: /use Life Cocoon
Attribute-alt-ctrl-shift-type1: target
Attribute-ctrl-type1: macro
Attribute-alt-type1: macro
Attribute-macrotext1: /click ClickedStopCastingButton
Attribute-macrotext1: /use [@mouseover,help,nodead] Renewing Mist
Attribute-shift-macrotext2: /click ClickedStopCastingButton
Attribute-shift-macrotext2: /use Vivify
Attribute-shift-type2: macro
Attribute-type2: macro
Attribute-alt-ctrl-shift-type2: menu
Attribute-shift-type1: macro

----- Registered unit frames -----
ElvUF_RaidGroup1UnitButton2
ElvUF_Raid40Group8UnitButton4
ElvUF_TargetTargetTarget
ElvUF_Raid40Group5UnitButton2
ElvUF_RaidGroup4UnitButton1
ElvUF_RaidpetGroup2UnitButton2
ElvUF_Raid40Group1UnitButton3
ElvUF_PartyGroup1UnitButton4
ElvUF_PartyGroup1UnitButton5Pet
ElvUF_PartyGroup1UnitButton3Pet
ElvUF_Raid40Group6UnitButton1
ElvUF_Raid40Group4UnitButton2
ElvUF_TankUnitButton1Target
ElvUF_RaidGroup4UnitButton2
ElvUF_RaidpetGroup1UnitButton2
ElvUF_RaidGroup6UnitButton4
ElvUF_Raid40Group2UnitButton1
ElvUF_RaidGroup6UnitButton3
ElvUF_TankUnitButton1
ElvUF_RaidGroup5UnitButton3
ElvUF_RaidGroup4UnitButton5
ElvUF_Raid40Group6UnitButton2
ElvUF_Raid40Group3UnitButton2
ElvUF_RaidGroup5UnitButton5
ElvUF_RaidGroup5UnitButton2
ElvUF_PartyGroup1UnitButton6
ElvUF_RaidGroup5UnitButton4
ElvUF_RaidpetGroup2UnitButton5
ElvUF_Raid40Group7UnitButton2
ElvUF_Raid40Group6UnitButton4
ElvUF_Raid40Group3UnitButton4
ElvUF_RaidGroup1UnitButton1
ElvUF_Boss5
ElvUF_RaidGroup1UnitButton5
ElvUF_RaidGroup3UnitButton2
ElvUF_RaidGroup4UnitButton4
ElvUF_PartyGroup1UnitButton4Target
ElvUF_PartyGroup1UnitButton2Pet
ElvUF_Raid40Group5UnitButton3
ElvUF_RaidGroup6UnitButton2
ElvUF_Raid40Group8UnitButton5
ElvUF_Raid40Group8UnitButton3
ElvUF_Raid40Group2UnitButton4
ElvUF_RaidGroup3UnitButton4
ElvUF_Raid40Group4UnitButton3
ElvUF_RaidGroup2UnitButton5
ElvUF_FocusTarget
ElvUF_Raid40Group8UnitButton2
ElvUF_Player
ElvUF_Raid40Group7UnitButton4
ElvUF_PartyGroup1UnitButton5
ElvUF_Focus
ElvUF_RaidGroup1UnitButton6
ElvUF_RaidGroup1UnitButton4
ElvUF_Raid40Group1UnitButton6
ElvUF_PartyGroup1UnitButton3
ElvUF_TargetTarget
ElvUF_RaidGroup1UnitButton3
ElvUF_PartyGroup1UnitButton6Target
ElvUF_RaidGroup6UnitButton1
ElvUF_Arena4
ElvUF_RaidGroup3UnitButton1
ElvUF_Raid40Group2UnitButton2
ElvUF_RaidGroup2UnitButton1
ElvUF_AssistUnitButton1Target
ElvUF_AssistUnitButton1
ElvUF_Raid40Group1UnitButton2
ElvUF_RaidpetGroup2UnitButton4
ElvUF_RaidpetGroup2UnitButton3
ElvUF_Pet
ElvUF_Raid40Group1UnitButton1
ElvUF_RaidpetGroup1UnitButton5
ElvUF_Raid40Group7UnitButton3
ElvUF_RaidpetGroup1UnitButton4
ElvUF_Raid40Group3UnitButton5
ElvUF_Raid40Group5UnitButton4
ElvUF_Raid40Group4UnitButton1
ElvUF_RaidGroup6UnitButton5
ElvUF_RaidGroup3UnitButton3
ElvUF_PartyGroup1UnitButton1
ElvUF_Raid40Group7UnitButton5
ElvUF_RaidpetGroup1UnitButton3
ElvUF_PetTarget
ElvUF_PartyGroup1UnitButton4Pet
ElvUF_PartyGroup1UnitButton2
ElvUF_Raid40Group5UnitButton5
ElvUF_Raid40Group7UnitButton1
ElvUF_PartyGroup1UnitButton5Target
ElvUF_PartyGroup1UnitButton3Target
ElvUF_RaidGroup3UnitButton5
ElvUF_Arena3
ElvUF_RaidGroup2UnitButton4
ElvUF_Raid40Group6UnitButton5
ElvUF_Target
ElvUF_RaidGroup2UnitButton3
ElvUF_Raid40Group6UnitButton3
ElvUF_RaidpetGroup1UnitButton1
ElvUF_RaidGroup2UnitButton2
ElvUF_Raid40Group4UnitButton4
ElvUF_RaidpetGroup2UnitButton1
ElvUF_Raid40Group1UnitButton5
ElvUF_Raid40Group3UnitButton1
ElvUF_RaidGroup4UnitButton3
ElvUF_Arena5
ElvUF_Raid40Group4UnitButton5
ElvUF_PartyGroup1UnitButton6Pet
ElvUF_Raid40Group5UnitButton1
ElvUF_Boss4
ElvUF_Boss3
ElvUF_RaidGroup5UnitButton1
ElvUF_Arena1
ElvUF_Boss2
ElvUF_PartyGroup1UnitButton1Target
ElvUF_Raid40Group3UnitButton3
ElvUF_Raid40Group2UnitButton5
ElvUF_PartyGroup1UnitButton1Pet
ElvUF_Raid40Group8UnitButton1
ElvUF_PartyGroup1UnitButton2Target
ElvUF_Raid40Group2UnitButton3
ElvUF_Boss1
ElvUF_Arena2
ElvUF_Raid40Group1UnitButton4
PlayerFrame
PetFrame
TargetFrame
TargetFrameToT
FocusFrame
FocusFrameToT
PartyMemberFrame1
PartyMemberFrame1PetFrame
PartyMemberFrame2
PartyMemberFrame2PetFrame
PartyMemberFrame3
PartyMemberFrame3PetFrame
PartyMemberFrame4
PartyMemberFrame4PetFrame
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
CompactRaidFrame1Buff1
CompactRaidFrame1Debuff1
CompactRaidFrame1DispelDebuff1
CompactRaidFrame1Buff2
CompactRaidFrame1Debuff2
CompactRaidFrame1DispelDebuff2
CompactRaidFrame1Buff3
CompactRaidFrame1Debuff3
CompactRaidFrame1DispelDebuff3
CompactRaidFrame1
CompactRaidFrame2Buff1
CompactRaidFrame2Debuff1
CompactRaidFrame2DispelDebuff1
CompactRaidFrame2Buff2
CompactRaidFrame2Debuff2
CompactRaidFrame2DispelDebuff2
CompactRaidFrame2Buff3
CompactRaidFrame2Debuff3
CompactRaidFrame2DispelDebuff3
CompactRaidFrame2`

**Comment by Snakybo** [comment]
Ah, can you try setting the targets for EM to "Mouseover target" or "Unit frame"? The "Default" target is similar to the  behavior when clicking abilities on your action bar, it targets the current target or yourself if you don't have a target. So in this case you will stop casting SM because you start casting EM on yourself.

**Comment by Snakybo** [comment]
I did notice some instances where things weren't properly update after making changes, I'll definitely look into fixing that.

**Comment by NoobTaco** [comment]
That was it. Thanks for that tip. I am glad it's not a bug. 

Thanks for the addon and please let me know if there is anything I can help test.

**Comment by Snakybo** [comment]
Awesome. glad to get it resolved so quickly, and thanks for the super detailed report/info!
