### ISSUE TITLE
Lua Error when opening Configuration

### ISSUE THREAD

**Issue by Dairyman** [Snakybo/Clicked#100]
### Describe the bug

Changes made here https://github.com/Snakybo/Clicked/commit/2773b48b87a8310bd4d9ebf8bce147328cf215cd#diff-5ab6b73ce426a956c46741421d8fb32236497a995ea9235efe9b64ad436f205eR501 broke it.

`macroIcon` can be a number.

### Clicked Version

1.7.0

### World of Warcraft Flavor

Shadowlands

### Testing

- [ ] Yes
- [X] No

### Lua Errors

2x Clicked\Core\Utils.lua:672: bad argument #1, expected string but got number
[string "=[C]"]: in function `assert'
[string "@Clicked\Core\Utils.lua"]:672: in function `IsStringNilOrEmpty'
[string "@Clicked\Core\Utils.lua"]:501: in function `GetBindingNameAndIcon'
[string "@Clicked\Widgets\AceGUIContainer-ClickedTreeGroup.lua"]:120: in function <...Clicked\Widgets\AceGUIContainer-ClickedTreeGroup.lua:119>
[string "@Clicked\Widgets\AceGUIContainer-ClickedTreeGroup.lua"]:821: in function `ConstructTree'
[string "@Clicked\Config\Bindings.lua"]:2654: in function `BindingConfig_Redraw'
[string "@Clicked\Config\Bindings.lua"]:2624: in function `BindingConfig_Open'
[string "@Clicked\Core\Clicked-1.7.0.lua"]:57: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5188: in function <FrameXML\ChatFrame.lua:5134>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4852: in function <FrameXML\ChatFrame.lua:4851>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4888: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = false
(*temporary) = "bad argument #1, expected string but got number"

### Reproduction Steps

 * Have macro binding where the icon is defined as FiledID (number)
 * Open Clicked Binding Configuration (used /clicked)
 * Get Error

### Last Working Version

1.6.12

**Comment by Snakybo** [comment]
Thanks, fixed in 1.7.1
