### ISSUE TITLE
Condition Spec in TBC?

### ISSUE THREAD

**Issue by volostyle** [Snakybo/Clicked#101]
### Describe the bug

I notice on the curse site, the screenshots show options in the condition tab for spec, but I don't see those options in the TBC version. Is that only for retail? If so, how do you handle different macros for different specs? Do I need to use the profiles feature?

Will the spec options be available for the WOTLK version since dual spec is a thing?

### Clicked Version

1.7.1

### World of Warcraft Flavor

Burning Crusade Classic

### Testing

- [ ] Yes
- [ ] No

### Reproduction Steps

Create Macro
Check Load Conditions Tab
Spec option not available.

### Screenshots

![image](https://user-images.githubusercontent.com/41602737/184212642-6d0fd1ed-6157-44a9-8968-4c51aa67609e.png)

**Comment by Snakybo** [comment]
I'm trying to get this feature in WOTLK.
