### ISSUE TITLE
/use doesn't work for spells with same-named item

### ISSUE THREAD

**Issue by whitter392** [Snakybo/Clicked#102]
### Describe the bug

trying to cast Frozen Orb using a default 'cast a spell' bind in Clicked does not work when a Frozen Orb (item) is in the inventory, bank, or reagent bank. the workaround is to make a custom macro with '/cast' instead of '/use'. removing the frozen orb item completely and then relogging also restores /use functionality for the spell.

### Clicked Version

1.7.2

### World of Warcraft Flavor

Shadowlands

### Testing

- [ ] Yes
- [X] No

### Reproduction Steps

have frozen orb item in inventory/bank/reagent bank
add new spell bind for frozen orb
press bound key
nothing happens

**Comment by Snakybo** [comment]
Thanks, will be fixed in the next release.
