### ISSUE TITLE
Party frames do not allow click-casting

### ISSUE THREAD

**Issue by Snakybo** [Snakybo/Clicked#109]
The new frame pool system changed the way party frames work. The existing `PartyMemberFrameN` globals were removed and instead new unnamed frames are being created.

**Comment by Toludin** [comment]
These aren't unnamed, to me at least - the schema they use is CompactPartyFrameMemberX. I've been updating each release's Blizzard.lua file to this and it's been working fine on beta for me.

I don't yet know what the Pet frames are called, but hopefully I'll get a group with a pet soon.

![image](https://user-images.githubusercontent.com/236548/191885527-22ea8d06-cccc-4025-bcbc-82798dab9e39.png)

**Comment by CirnoNine** [comment]
Yeah, I've been able to make the compact frames work by adding them as @Toludin mentioned:
```
	table.insert(unitFrames[""], "CompactPartyFrameMember1")
	table.insert(unitFrames[""], "CompactPartyFrameMember2")
	table.insert(unitFrames[""], "CompactPartyFrameMember3")
	table.insert(unitFrames[""], "CompactPartyFrameMember4")
	table.insert(unitFrames[""], "CompactPartyFrameMember5")
```

For the standard frames, they work if I insert this into `RegisterBlizzardUnitFrames`:
```
	for memberFrame in PartyFrame.PartyMemberFramePool:EnumerateActive() do
	    Clicked:RegisterClickCastFrame("", memberFrame)
	end
```

**Comment by Snakybo** [comment]
```lua
for memberFrame in PartyFrame.PartyMemberFramePool:EnumerateActive() do
    Clicked:RegisterClickCastFrame("", memberFrame)
end
```

This did indeed fix it for click-casting but there was a second issue regarding hover-casting, that took some time to resolve.
