### ISSUE TITLE
[WOTLK] Renew and Power Word: Shield not working on low level targets with error "Target is too low level"

### ISSUE THREAD

**Issue by rushtothesun** [Snakybo/Clicked#113]
### Describe the bug

Having some weird issues on my Priest.

All my heals have Mouseover -> Target -> Player

For example Greater Heal's status is 
`/stopspelltarget
/cast [@mouseover,help,nodead] Greater Heal; [@target,help,nodead] Greater Heal; [@player] Greater Heal`

The issue is that Renew and PWS don't seem to work on low level targets.
This is testable in the Cathedral in Stormwind by the Priest Trainer.
The following also applies to Players and not just NPCs

My priest is 70. Bishop Farthing is level 40. Brother Joshua is level 50. Renew and PWS don't work on these two.
Archibishop Benedictus is level 60. Renew and PWS does work as expected.

When I mouseover or target Farthing/Joshua and use Renew or PWS my character's hands light up but nothing is casted and the red text "Target is too low level" appears. If I manually click Renew or PWS then the heal/shield goes off as expected

Greater Heal and Flash Heal works as expected on Farthing/Joshua.

Interestingly enough, choosing a lower rank Renew/PWS in clicked does allow the spell to work. Rank 8 and below of Renew works on Bishop Farthing.

### Clicked Version

Clicked 1.7.7

### World of Warcraft Flavor

Burning Crusade Classic

### Testing

- [X] Yes
- [ ] No

### Reproduction Steps

Listed in description

### Screenshots

![WowClassic_hgQpJVmpkg](https://user-images.githubusercontent.com/20650932/192179672-99d84502-fe54-474f-981b-f268a3fec941.png)

### Debug Output

Version: 1.7.7
Project ID: 11
Race: Human
Level: 70
Class: PRIEST
Mode: AnyUp

Possess Bar: disabled
Override Bar: disabled
Vehicle: disabled
Vehicle UI: disabled

----- Loaded binding 1 -----
Keybind: BUTTON3
Hovercast: true
Action: macro
Identifier: 3

/stopspelltarget
/cast [@mouseover] Dispel Magic

----- Loaded binding 2 -----
Keybind: SHIFT-BUTTON3
Hovercast: true
Action: macro
Identifier: 3

/stopspelltarget
/cast [@mouseover,help,nodead] Abolish Disease

----- Loaded binding 3 -----
Keybind: BUTTON3
Hovercast: false
Action: macro
Identifier: clicked-mouse-3

/stopspelltarget
/cast [@mouseover,exists] Dispel Magic; [@target,exists] Dispel Magic; [@player] Dispel Magic

----- Loaded binding 4 -----
Keybind: `
Hovercast: false
Action: macro
Identifier: clicked-button-`

/stopspelltarget
/cast [@mouseover,help,nodead] Prayer of Mending; [@target,help,nodead] Prayer of Mending; [@player] Prayer of Mending

----- Loaded binding 5 -----
Keybind: 3
Hovercast: false
Action: macro
Identifier: clicked-button-3

/stopspelltarget
/cast [@mouseover,help,nodead] Flash Heal; [@target,help,nodead] Flash Heal; [@player] Flash Heal

----- Loaded binding 6 -----
Keybind: 2
Hovercast: false
Action: macro
Identifier: clicked-button-2

/stopspelltarget
/cast [@mouseover,help,nodead] Renew; [@target,help,nodead] Renew; [@player] Renew

----- Loaded binding 7 -----
Keybind: E
Hovercast: false
Action: macro
Identifier: clicked-button-e

/stopspelltarget
/cast [@mouseover,help,nodead] Prayer of Healing; [@target,help,nodead] Prayer of Healing; [@player] Prayer of Healing

----- Loaded binding 8 -----
Keybind: 4
Hovercast: false
Action: macro
Identifier: clicked-button-4

/stopspelltarget
/cast [@mouseover,help,nodead] Binding Heal; [@target,help,nodead] Binding Heal

----- Loaded binding 9 -----
Keybind: 6
Hovercast: false
Action: macro
Identifier: clicked-button-6

/stopspelltarget
/cast [@mouseover,help,nodead] Power Word: Shield; [@target,help,nodead] Power Word: Shield; [@player] Power Word: Shield

----- Loaded binding 10 -----
Keybind: SHIFT-BUTTON3
Hovercast: false
Action: macro
Identifier: clicked-mouse-shift3

/stopspelltarget
/cast [@mouseover,help,nodead] Abolish Disease; [@target,help,nodead] Abolish Disease; [@player] Abolish Disease

----- Loaded binding 11 -----
Keybind: 1
Hovercast: false
Action: macro
Identifier: clicked-button-1

/stopspelltarget
/cast [@mouseover,help,nodead] Greater Heal; [@target,help,nodead] Greater Heal; [@player] Greater Heal

----- Loaded binding 12 -----
Keybind: SHIFT-T
Hovercast: false
Action: macro
Identifier: clicked-button-shiftt

/stopspelltarget
/cast Mass Dispel

----- Macro Handler Attributes -----
type-clicked-mouse-3: macro
type-clicked-button-2: macro
macrotext-clicked-button-shiftt: /stopspelltarget
macrotext-clicked-button-shiftt: /cast Mass Dispel
type-clicked-button-shiftt: macro
macrotext-clicked-button-3: /stopspelltarget
macrotext-clicked-button-3: /cast [@mouseover,help,nodead] Flash Heal; [@target,help,nodead] Flash Heal; [@player] Flash Heal
macrotext-clicked-mouse-3: /stopspelltarget
macrotext-clicked-mouse-3: /cast [@mouseover,exists] Dispel Magic; [@target,exists] Dispel Magic; [@player] Dispel Magic
type-clicked-mouse-shift3: macro
type-clicked-button-3: macro
type-clicked-button-1: macro
macrotext-clicked-button-1: /stopspelltarget
macrotext-clicked-button-1: /cast [@mouseover,help,nodead] Greater Heal; [@target,help,nodead] Greater Heal; [@player] Greater Heal
macrotext-clicked-button-6: /stopspelltarget
macrotext-clicked-button-6: /cast [@mouseover,help,nodead] Power Word: Shield; [@target,help,nodead] Power Word: Shield; [@player] Power Word: Shield
macrotext-clicked-mouse-shift3: /stopspelltarget
macrotext-clicked-mouse-shift3: /cast [@mouseover,help,nodead] Abolish Disease; [@target,help,nodead] Abolish Disease; [@player] Abolish Disease
type-clicked-button-6: macro
macrotext-clicked-button-2: /stopspelltarget
macrotext-clicked-button-2: /cast [@mouseover,help,nodead] Renew; [@target,help,nodead] Renew; [@player] Renew
macrotext-clicked-button-4: /stopspelltarget
macrotext-clicked-button-4: /cast [@mouseover,help,nodead] Binding Heal; [@target,help,nodead] Binding Heal
type-clicked-button-e: macro
macrotext-clicked-button-`: /stopspelltarget
macrotext-clicked-button-`: /cast [@mouseover,help,nodead] Prayer of Mending; [@target,help,nodead] Prayer of Mending; [@player] Prayer of Mending
macrotext-clicked-button-e: /stopspelltarget
macrotext-clicked-button-e: /cast [@mouseover,help,nodead] Prayer of Healing; [@target,help,nodead] Prayer of Healing; [@player] Prayer of Healing
type-clicked-button-`: macro
type-clicked-button-4: macro

----- Hovercast Attributes -----
shift-macrotext3: /stopspelltarget
shift-macrotext3: /cast [@mouseover,help,nodead] Abolish Disease
macrotext3: /stopspelltarget
macrotext3: /cast [@mouseover] Dispel Magic
shift-type3: macro
type3: macro

----- Registered unit frames -----
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
Boss5TargetFrame
CompactRaidFrame1
CompactRaidFrame1Buff1
CompactRaidFrame1Buff2
CompactRaidFrame1Buff3
CompactRaidFrame1Debuff1
CompactRaidFrame1Debuff2
CompactRaidFrame1Debuff3
CompactRaidFrame1DispelDebuff1
CompactRaidFrame1DispelDebuff2
CompactRaidFrame1DispelDebuff3
FocusFrame
FocusFrameToT
PartyMemberFrame1
PartyMemberFrame1PetFrame
PartyMemberFrame2
PartyMemberFrame2PetFrame
PartyMemberFrame3
PartyMemberFrame3PetFrame
PartyMemberFrame4
PartyMemberFrame4PetFrame
PetFrame
PlayerFrame
TargetFrame
TargetFrameToT

----- Profile -----
S352UTnoqy4NOfqN8P9oNw3gJnr2RLtwuGcLWiZ4iuDQ6qYMErE23H0hJJRnx2IeW2)7IDgsrrrPppZW)rH2HtddMxM3uur)LV8JZIRksypomkpJ(g3w962jmiJLYddEFCvuCrsCg93XZ4z1X3gZlx2d)HDyDOVZE7chRvDXP5jpUVg7iAS7EACBhR1h)G7yZYF4PRpNnpoAF9Il1l1Hb3eNnloB(MZP4SA(8swDCEM4ljt2A4tN2bSiX)tC4tzrL5(Yt3jnzpDDutvDE6txl)(WGQcEsYLSKgoDU2Ph10Aw5CE9fzX19VTMx(owvD4nup2uYw0n0bRMNUOn0hIyzr8K)UH3WNfi6nH1vuVupMx3VUMf9fX3qt)3ZlRLnBA(WzHNegW)xEuJyGoQCgnVlg4IZSYYMc5Xu2l9BQZ30nYHT8AzWqHP3YI4FE47g5h85H(xE150v0ROXsLOxpNv(LLtaRgT0m1x4pkMpfd9cwjDrFZ17GKC2mXKMybdVuC6oHZssfF19loF9z5PX3rFzfn84j8OA(mAOsDsuE6nS6nMsNFp3G4m68HMRM(ybxywfDjnr0LJ8hSLT(0AR0MKAAHPWmXKI0c5kHOewL4k(6gpEYWbbIpVASiSFNMV0gzhS4mBy2hf3KS151Ud2sAED7JZPnPmAoFZH5LJYfMipk0QQOyws83Klr3QFeJUd0h0)w2E(xBIlkOz2nt87oaVn5rA(7at3KbSBKtHlV29IlipWkppF2HSOMLiwGSz(wXX)3YZ4YBwoW4pVuUUA5Qaf74c(HwHv9qCA6HNvkUVyQMNur3XYY40tl3AwNUjARf5bz85S13qK3uplpVuUCDXDp75wIDxho0)Qpoz0fJVAC)jt)0vJMC1K(dF)Ux8tZBOB(3A5Xl65QA6E067oWXoJtpps(ugXdT(RS8hKluxEF(ohrAn5INlkpBUlNAAe9GXbzILyIhaeuYN3KWkx9n0aATvYUnMwlrpZOV)Ne)h65tjX1e5q8zQZx261qRdzEqd9SzcEn4d9V4mXd)L3YulEQsqW4bND2AU1HXeoAIjS960IAl4eGtqlCbNq(SbWje)sLf)gfWjmhoH0fLdZjC1Kt40YXMC1bCcWjaNyHpIGtqqcWjw8d2nk)j8ooNWtporW48h4LpD9)Kxo7pF66G7I5jZE9WgKRBVTHHQnIdfIdfIdvcxgQtfcoi8V4niouNn8YbplWvNo4SXHldf15JUiyWOlhmzDKNwh)Qd2UP9N8XbIiyTitjQ1OXN1)tYJ0(c7vRJJPAPhMY32RRD3xpUespcspYUzYbPhrMUTxMHSvtmi9is3mr6row6rAFCob97Y1kl6TCqqVqs0L3hIKJGGETCpCGGEzGb9QZXPe0Z61Isi8MOh8MaB2kWjwTb6qYrqYrKPjZ4sos3JZj6QlNWXZfycGjaMayIT2s4WDcdet074ycYLaTCNOTLfOeGsakbOeGs8mzxzCotyBDCmbzJUCcOCdKCcKCI1IudbDcbDYmd6KTuD7hrj4AkfCHY4l4jRvM(RLgoEZ3mUNCX0PJ8DXwYfBjxSLCXwY9NG0Wp5nqA4hy)4Uh5NVCt8(92mUF)wCWDIRTSYPCe8K2sq3QxluQsGJmWrg4iZ2vkhKwedmTi2kObDYg9c4LnrkqiVaPaKcqkaP45vKoZl1ikOcDBnLHUVTLvBKdDKdDKdDKdDKdDdph6kOdCBTfcUJhXyETsjc0bo0bo0boktUpVCnJYKRm73)WLjxBfecozJ(XEIGmGuGcGi0cokaIRRN)ilfMywkuqm4IYDRwY3WPLRnYsbYsbYsbYsbYsHPNLcfKdUOscQfPOTRhYsbafauaqbafMoOqbbHlksuAbk651fXEcGcakaOaGcdhu4OGKWfVsA1fuG0zdqbafauaqHPdkuqt4oAQjCFxNE9qjRfKcqkaPaKctNuOG8SD0vE2oDA3fYZgKcqkaPaKctNuOG8SD(bKNTfifGuasbifGuy6KcfKNTJUYZ21XTZVtj0o40HFy6FmfvIqujcrLievIWFcvIWBEdQeHVFWh6FXzIxX377T1TJcY0MSrV8ABB1ThEFDdxlGRfW1c4AHP7AHc602rxDA70PRhccfifGuasbifMoPqbDA7ORoTTD8(Dkgui4ti4ti4ti4t)Ag8jfKPTJ2Y02QnafWJc4rb8OaEuy6EuOGmTD0vM22w9WRUBgifGuasbifgoPWvbDAt2Ox(SDSB1gc1gKcqkaPaKctNuOGqTD1vO2DTfUJGYook74OSJJYook74j8Ov)KbJ7vENRc60MSrpxkAB1gftw4rb8OaEuapkmDpkuqM2U6ktBrSNW7NcqkaPaKcqkmDsHcY02vxzA70YThifGuasbifGuy6Kcf0NT7pI(SrAkaPaKcqkaPW0jfkOpBxD1NDl4rb2HSlsKBjlIl0KxvC28eEyWPnPSm6J8L54Z3kmiTz7hNS0ez5NPQGhfZsI)gRoopBR(X3(G9XQxyZ8V2exuWLm77zjn0ayR2jhG3M8in02yWj7Xa2n0qFDx8clEGvcr3br39lPO7CvqD2Kn6LoBNwEI9mf24tyJpbsb24tyJpz0B8jfKNTRUYZUvxuzarKNGhfiYtiYtMEKNuqD2UARo7owydYcqbafauaqHHdk8uqC2Kn6f6jBREIWwHqpHqpHqpHqpHqpzYHEYtbXzlky4SOvPrmLfvM7Zs5HbtAYE66OMQ680NUw(9Y8oMKCPmHH(UD8aOaUuaxkGlfWLct3LcfeNTNUIZw4sbYsX)hsX)XExD9M4ibb)fTsaXoeEKCR3eRJy4yirksRGDIZSjwXm2N)yZX(W9BF7zmWbewFZor3jzC9iK2gHLJlQURQ6nIas)S1WKLpWlQrMnrY8cUmumBv6EskkyCGx9kksxHwqrHX888D1J0KP(EmL(K2kij63jCGGKwxJ(eKgZxjY8LxLLuMIWgh6Ec6E6Ku3tog4oBQg7Ou0fekambiuacfGqrtNqHbwZ25Dyn7lGH7asbqkasbqkA6ifgynB1UQZQzu0VRAXhHHzJHzJHzJHzJHz3OhMTboZ2XwNz31zq328oPO3CwCc8Mn8M92aMM(vtXcPEUtR9OUHEl)7jsHwbj14T8KSL)6N4urDtbl)1OLlR3X6PFlDMLFPcFMlLI49o)7BzEMu8eFlFSKYIhtsY0JuRYG9VXD8rVzwz(blUA64BNSyYWPZUFX4PlMo0)Jh67(LjLs1NZp)mNxi4XfpxtfsX3ez0n7vc653LjVQdrGJhfanUOg3XaVzR0UKvuk65E2faPanFcnFcnFcnFQP38jd8MTJTEZUx)(dAZJPaCk(N11cY7jnEj4uqKO2ecxGtXtIcndPNti6iH88cpPksXEuXmjt8uzmpBZ7q0N2wLMQseDVu(C2WG7v)L8IO4OIvvVwfVAvhnvjD1(FPCwPmIoKp69PH3oAMwpKQBvvQPKXM4nAe9YahdCNnvJLCk6FrN2CEpbKcGuS)VKeifQhCbKIQhfZZAqifUgypBQg7qkgmOnhJhaNa4eaN4TrdmWjAI4egyoBxBnND3oDWqkWqkWqkWqkWqkA4dPW1aZzt1yhHIUUoNrKrATsKfukaLcqPauko2oqP516jdmNTR1MZULVukasbqkasbqkonqkmWF2U26pBxfBKwdJc21(FA2hU82zZghqyRP8mLS5zpPccPpaqdaAaqdaAybOXLMRbQr(35TNkOU2B0KALb1XpI1kH6MX3Y8gFN3uLWN0nFARARQ94MnC6vEkburph0mnxnz0W71FmhtYvUg4mCQg767vVoQzW3AaPaUeYKqKjHitcpj97NRbodNQXoGIbo9BtSzaqbakaqbakonbkmWy4U2AmCcO4mWOq90ZQSaxLbetf8yDspSozbc4jlJEMEZ8dt1aKY5Ll5YkEW0)7fgXJJ(oFZAz5xlboe)zzuA6UreX(rvb9r814v1NvgubkRyvtgs8kpdafaO40eOWaFH7ARVWjGcOnxOnxOnxOnxOn3MU2CnWw4UwBl8oTQbPJwpHwpbgfGrXjjJIZnWv4unwnJc2LrYhj68)9xUwWJ))RhupmNj(lryPQlfJZEuKPcSawKSqKLvMwOZxYcEwXWYIKHff8WxuVLEvY6hMiNZ8vL(vEO4Z()24a2N9dUBXnr5Hl(JsrU6SEdp7L1hr1wNLP6pYlIvpqFJNZiAuqUv)Sy78)SiNQxTBfWnErgnH6G1L4MlmigB1mFBpXy77tRvvHt1APvTBsxTwJxht5uNBG1YPAScSjOxhLfsGYPWCoWo1a7udStnAY7uJZnWA5unwcu4EwxxGuGjIRvIoXYB39l(16XDVZ6fN4(EW6fVQemrC6Qh2Pg0fH2Zo14hS35tRjouuu8Vs5pysCPWmDvrkJtxmBeFeJ)bYeh0yx6N9(Ej2cwktUElf7L(BPHKnIYVCUN35C)c2)TzcIwU)E0rkIJkkO)BXsCSehlXXsCJBjEMGOL7VhDKIKOqQ0z4tm8jKuWWNy4tME4tcY3D2hiF3m7juuGIcuuGIcRROqq(UZ0MV7KrPPm7jifqkGuaPW6Kcbb8otBaVtgLetNrbPasbKcifwNuiiH3z6dUxeRPpafakauaOW6Gcbj8oxzW9MMmknCOPWpB8Zg)SXpB8Z2Y(z7Pa)Up(ZR331CBh8FU1FLLvnTBxTnKp6C9PUlKoCafakauaOaqHPbfcINDO0XDLV0)NDDMrOqvNp7xhBoTO84H2D)90IUR3vyO11NliJ7QDh28TRjqyXl9VBq5rrtGSSNfTA3(UAo(66PxAceAcK7FyU0TU0qnbYB26s91os)dDEpljS(q8SNHfYOnRFzriKXH3i4ncEJG3ig3BKCbHcp015AeYmnoAm1hcKI(xWM6dj8TqRRoSBHVAHguFiuFi(39)PQ9LUdD)(51f660)CXIJDI)ZH)UvT(yTBV)oN2nRQ)3TFwIXp(5DtE8(GHhVxJe6PadlPqBw)cKcoVvOPasbAkqtH11uiiv45Ad7xGuKJn6ujHOPO6S1fOPW)kUV0n7LBCnnv1xSAeVC3joRPAT7vmlvs4TutHGyHNRnSFzrCWCz4tm8PsKuGKcRlPqqQWZ1Unx9GcAKqM9eZEcqbGcRdkeek8CTHcpo1)KeGdcWbUztaoiahMoahcYeEH2mHhhnobpkqrbkkqrbkkmUIcpfyWZ9uy1hP9eYMuGMcCZg3SXn72TOPWYAk8uGHjfkdfEilfjm9j0uGMc0uGMcRRPqq8Sl0gp7rJjjfWjGtaNaoH15ecsNDXhiD2P0CTqkGu8jqkEM9oJ6PTHHIc)lcPKWc08y2wxB1OPD1DtcjukMuderAsNtcSYd8BF(MshTJ1wlpbmRDEKGRvuHKJo3R)o3nroa5l1YZlqAEhzr965CwVOjDgn4RdNmmC04tNmy0KrH9(y8MV3MnROoN(JeXXmpRwe)(FFfLvcEw117yf5IBfs1TXYO27Z5f3LV98wRHuF5vIkkayFI76258lYAku5k(QxDf1n0BkD2kvG9x7P)c6SpeNqwOuaLcOuapf2UNcnOZULP0z75G5RhyUdm3bM7QHqHTluObC2TmeoB2qjFHq(W5fx(W59f5tjE9F1qRqzFt8drsnLn7dKtPP6H7YX(HuwpVQXKOY(xvyDvryvfp5g6snj1EVKI8ywpAPxYteN17ddIyN1l6Bt6NwMm5l1IsAx7ZL384N4XqDNS)EJyXfP5tJzNhZMZLuqWXUImeFGxmlRachVSchiRZrwN)KWmQf1(skWLXp(1fQ3OLLwTiM1T9)IzDUsdA)L(Yu2W98p0bhqxu6lu6lu6l4OX2D0ObC4Tmfo8JCOCsh0Hd6WbD4GoCqYHvtYHg0HhykD4klfUqPawkGLcyPawkSClfkvG9w8PaJPd337ip4Pa0Hd6WbD4Go8sHn7PqPcSFLcJPdxPuawoGNc4PaEkGNcB3tHg0HhykD4UkLcu9jOuaLcOuaLcBxPqd(WdmLp8JCOrVeAOnAOnAOnAOnAOTvx8jnWdpWy8WvwkqKtblfWsbSualf2ULcnWdNcyqZI7CLsb8uaLcOuaLcOuy7kfAWhEGH8Hh55755IQpHJ(eo6t4OpHJ(KLF0N0Gq7atj0oGcax0Lc0Lc0Lc0Lc0LcRUlfAWNDGP8z7tkmqNa6eqNa6eqNWQ1j0apBxht5Z2N41dcfqOacfqOacf2SqbjcSxO7CDmLpB)w(qPaTOaTOaTOaTOWUBrbjcOHsHH8zZ6if8kkVZ7k4zVEAgV5bDoRBVpn(GoiUZ3(OgJj5jc6xxMMFvMiM1TEgpFT5BwKYi7SngNcpUKks4PCUijLNLEpNYD(12hks7)1ZK0pS5EOUsZNx89605ZxF2Q98rxx2ckE(3(Wx7YSf0CrBhR4oUSFX0DTIkEgLh(p99WM3)p77Gv3)3xKlI4ZwBRXO37pnG8qCN)Yg35BjM0hhoQt7XQh0IAq172u1)NxgZc3z2Qp8KWtBpQ55tAqeUyU6TcSHTp5eAFCD0apCxht5d3Z54JvpSH6FH6FH6FH6FH6Fz31)sdaXDDmLqCp)3DiQagW5a4CaCoaohwoohKmGgvaZyiXDA16)iFf)K9oBATTbccd)xsRCSCYXwQZLw0f1EOxkSKU12G(Wij7a9xF3rMghf8hlZbBw0dKtjsMqqXpEEN9zMcI86Eh51zJmIiVotwGBDdbWT3wEQeK6EDtv1LdcC7(TFxzoEVS2wx7kh96pojVIA3k7BG2MD9)UPPT7c)ctKxxlYR8FoA)(jxEXU6n9)Q4llF(t)4BsWvNodQaSe3KOwt8KNYGvqDfuxb1vqDfrFDfb4jUjrPO4JwK4sZ1Nwls8LuMXDOmdwK4SiXzrIFCVGFTYmIKfjUaHcibmTIQNU4rXjf6SoDwNoRtN1PZ6XDN1dWvDtIwz193j7ZjljGrcyKagjGf9jGfIV6gT(QlScgbwWkGvaRawrSZk8yGRNbLrRX6cRGtSlScyfWkGve9SIqCw3O0zDzeSpJDkoScyfWkGve9SIqSg3O0A8INlTDRNCt3eMRjBVdN(kMRjC6R40xDRo9v3U5AIh(eqYx6DvFgDjHoQF4ChDtg5w4F4BZ0SaNLx4F4WtNvn7QLsoVGkM9oBz)6lCf1U9Uw)d7Y8HRS8R1nVomB4oO25hNqAYqMY2UY1pyt56g)T(ITRFzTmv3KpSrrRB1UsB7))oF(Dx1OXA1jeku(3Td3T)k9pi8(PGLA)dnH4QUrTR6ZtZygWtYxWki5ls(k6t(kex1nADvplzb7vkqfGkavaQi6rfHOQUrPQ65gFzfC4RGvaRawbSIONveIS4gTYI7zfZ8CgKfhzXPDfiloYIh1YI7Xab0ABTYINLSidub7Hq6Sn7Hq2dHr(Ei0eIR4PADf3JkibksGIeOibksGk2tGYtbUEvfPAvfpD(mPP4KafjqrcuKafjqf1jq5XabWk0Qk(8uoduuvbvvqvfuvr0xvriIINQuu88hwm)XPCcu()Uv2GgEOH3rdM7vUX8(BtTl3w5UGc()PPTs(XDBQxv6e7Ro(Ut5N1pr0Wdn8cBna6XabuvHELTFiBkFgOGv4o(UKOST0EFyfEgM)RHLskRm2ysz70qu2ovTY2jpjlBJjB3kGvaRyCYdWkeqX9Iv8p27mO12giim6FjjTYXRoMsdfFXPifk0lnzRWqnyzzSSlKl53E3DTHAcKKH52e)UkwlWGnp(MDEZ0(WpF8(2hBVDXxViZf5keMRqIY2vAv22xwubQG(LL(LL(LL(L149lBKciOeuAv2EM)AUfOiubHkiuXBFrjuaktvakjcBNAKPq)H1J5XL4qOF)y(o26ApU9LN6poDyC4LNYp)8Sv8h5rQ4YyOIR5LLbOcqfGkav85y8YgPaccvO1x7M5fu(jk)eLFIYpr5NSE5NKORTtRU2Lfn10TSywbMvGzfywH1nRiIb(4ufoT(A7llQjwbXkiwbXkiwHXJvePacqfA11ofRG71MyfeRGyfeRW8XkKiSTtRW2jwbs4bRawbScyfMNviryBNwHT9LfCBfGkavaQauH5rfs812P1x7iQGkqbQaubOcqfMhvirxBNwDTDnU5CZ2WkGvaRawH5zfs81oT6tvzHxzH3FnpkYrdp0Wdn8qdVphA4fXac6ck9gBxXyGIyfeRGyfeRW8XkKySTtRX2vn1ubkqfGkavaQW8OcjkBxRvz7QzUBOcuWkGvaRawH1zfrmWhxbQA9kBxrScqfGkavaQW8OcjkBxRvz7Qz1jf(y)g9RUDBcpVAFAQ82UkSjVFl)BEg82TmmoS(pXho96DUs)4WVdh()r)YRpW6TthcB7x9WZ7YluZZBmZUL3V8U3DPzE6eN2hzBcttx(H)E7I76sVSvN3D8PfW5WXl)VE35ZKFbN(MTy732pEC37Swpzx4XUWl9Ru2Vr59iCEViU3sJI8igqqSc9kB7B4MTjxb5kixb5kmFUcjkBNUEAvnmB1m3CyfWkGvaRawH5zfsC2onrXvXkkl8nudkyfWkGvaRW8ScjsBNgtSQyf(ckbvauXvlQ4FS3zWkXoqqu0FPojD1j57yCTGOrjqMjbDqb)6T7OJdgHzkRfcfCwli4BZ5DV3(u52FTW0X7MgoSob1xBlvgd68YqHTldL)XRvB)(8HH1pbLN35A74vpo)86my)TFXldxAqSxEBC)(XdpDHnZwED5gJ)rXxovxnxHgNTlxjwtOIsfuC2aHvaRGyfeRW9Xk04SD0QZ2vsSJRroScyfWkGv4EwHgPTJwL2okmwbKcifqkGu4EsHgNTfRoBx1x3sQcyfWkGvaRW7SImg46YviwD2UjIiEZSS9Q4r7qepeXdr8U)0)Rb)jIxgdOGvyvABPRhLTl)dmkBdPasbKcptk0OSDzXbRVbQenqrduKQGgOObk33aLgLTfRkBx0WJZgiScyfWkGv4EwHgLTfRkBx3M64vqbRawbScyfUNvOrzBXQY29ySn7AZU2F3r9om2MdmRtpWSziGIDTTASDtDFFMYWXiNLT5nq9jXewbScVYk0ySTy1y7M6MwEfu0afnqrdu0aL7BGsJX2IvJTRdeRGkOOckQG6hFJSoDje5Ob6PJgyMcC9kOswv2of4KbsOccvqOccv49qfziGcsHvHTlh3JogRan8qy7HhySILj0WZXA4L0iSDYQW2fwbJvqUcYvqUcYv4(CfAu2ozvz7mROlqUcYvqUcYvCCKCftdEoxHgLTtMv2wIboVhKRGCfKRGCfUpxHgLTtwv2w44EWBGI3afVbkEduB(o36VZlBgcOyzBRcBxf6lAzGgEOHhA4XY20aLVBGsJY2LJeRPdmBHvqdu)Fnq9b7DU2tJJdgf(x0krVqB5JD3jleTL0U1DqcPrbCtnqe5244alZh43((Ah61qczIMDNMrNpHi1Xjox8tE959y)2sXpZzQJvLlZ)5LWSs)7fWtt3zD8NnBUTftVU(lE7jBNoUSW9(UW1LXub5tZ62rNlJZs2UW9Zo47OWYwbSSnYcQwTAf1XY2dAQLTpBiMCpaPaAvaTkGwfTETkQJHTh0udBRZxwWkaRaScWkaRO1ZkQJJTh2uhB350(dXuroyfGvawbyfTDwbHb(yLTh2upB3R)zDWsCeyfGvawbyfTEwrD8S9WM6z7UdXkNksywKWSiHzrcZ26tywIcuJWkASLTpz0zWY2iScewbcRaHv06dROow2EyZTSD3rqABWkaRaScWkA9SI6yz7Hn1Y2d6FsFixbyfGvawbyfTEwHX02QxseUm2mRjtCz(Rerk)78fsxNo6mE9ap4DfpiJkTllnreeK)FoDpTBNgyp7qUNm2Hhs138SOxV1llvfh(6TMT7Ym)X2loYLzhPeY74EIVy)htDyFX25QBU0p17M)otKQ8JJUKlF0LrL9jHuzoRweBVY93DzI)r4LPlYu5ktJIAJ6AtMLOCxsTdfxQgNPIhRuCVh3SPzc12T4XJ8eb0bltSIPB45dc)JIxw6hTsF5qxN3l56dK2yB7BGFP4(SaUK2oD4PR4p5R4bPUSXox7YYI8Ps)jR)C8NNq)2dXudkWx9s(pBC72B7VveFzGW0QEiMAOE8uLU6oyx2R6P9EtzxV)MZ9G4MlLYDbVOpt267o6mAJZ9m1UFeDDLUMTq)SL2xF(r3t7WXPjbPMdD6vrRHEw3ZNh4)nZ93DApoDR0XJ0pBU)j(AMFscDNtFVFZlqRT6O5cM51P)kk(zt1xsHIe0D98Nqf8a1dvCkJvP126Q06ZC5LXRQ6LlV4WLCZB(5pNu4Tpj1t5UV1DrwiN6fDR5ApPG5AZlI(PvT7A5sIc4YUx7U2FRdTjdlOAwrr)A)USIoN1Tp1h837u5byfGvu4H2FcgkhSIo6pIX0nX3IJeMpFRCI1DXYWD5L0B(v0l06koruvVBPp7hgwnWo5PKf8aDFyB)2d9x(vJJDRAP37OJvO)GhIvymTDfXvu0V2LXk6H4kqCfBt4hexHU3xexXwieyfM4hdJZI0djz5bfCSYkm22UcwrrhB)USIE9hnaXvawbyf7pTzbwbyfhm4STxwHX22LZk0Rsr1qVc25sbxjKVE7fcEWX4yrT8)jDlEtmKVFHlMyFL1APlUC6NzwtVYA(EkrCH1Kz6GbnP58gbp2D)wmE(5w7lFX6DYKVBV7onBY4RF)Je0jzTil)xnzk(JASVkm1ocgfyu)QWOigu1mQIofVmn17D6XiBcAQdn1)4jE3FuSIckvcwbyf)YWkmzdufXZu0P4LWk63Rbt55qtDOPo0uppv(q(xbn1ZFs4ivNKrMbsPcwrrRIxQojnyYjeScWkaRaScnQe5F16Lb(JvwHz8ZRGvu0Q4LMRUGvan1HM6qt9dH)ixD3Z)oTwn1hz8lEfSIIwfV0C1TbZIiiUcexbIRaXvG4k2zjD9ODmO(a)IRNgPQr(x5O9aydMDcbRaScWkaRaSI2aR4d8l(OA6xCTVoqEqHXGcJbfgdkmguZgpFX13mD(nZhB)PdN0D(5mgu)B7D(1Yccdgf)BKqsG1TrqebEr7(bRCuJxDtsP)8TV9m1cZi1cIxJZDYUX78XFB7878rUfPiV42zbVEpO6EEXh7J7mB)JZb4kaxb4kaxXqGROL8IpPh5fhNxb4kaxb4kaxXpkxrl5fNQiPUCEf0Eq9gwphNxb4kaxb4kaxXaGRWol4X9GQdJgyRLA5P)JB503sHi(pZ951Si)0BA5ImJELmZBkdD4uK7Eunuysu7LolXx3S6W96LAoPU71Htr4HnZkFPOEHJehmos0jw5JYdzurdWg5f4fWzA558zkDKsVBzeNU(ufRTG8ZoTIfoXKw19emJEL8YCQkbSdbYngQOwYONtuAvIi11ze2pr7(Zm7RBtSy7FXkxzsqlWVc

**Comment by Snakybo** [comment]
Interesting. I looked a bit into this, and it seems like it's a macro restriction and not something I can fix unfortunately.

https://www.reddit.com/r/classicwow/comments/d2dkej/macro_to_downgrade_heal_spells_based_on_target/
https://www.reddit.com/r/classicwow/comments/d8r8no/buff_macro_question_for_player_too_low_level_issue/
