### ISSUE TITLE
LUA When Trying to load in Dragonflight (Beta)

### ISSUE THREAD

**Issue by Sukodin01** [Snakybo/Clicked#114]
### Describe the bug

Will not load in Beta.
![image](https://user-images.githubusercontent.com/114668330/193032152-c5384091-fc71-4490-a2ca-36d2eae62ab1.png)

### Clicked Version

1.7.7

### World of Warcraft Flavor

Shadowlands

### Testing

- [X] Yes
- [ ] No

### Reproduction Steps

Try to load

**Comment by Snakybo** [comment]
I don't have an alpha or beta build for Dragonflight out and the Shadowlands version won't work no, you can manually check-out https://github.com/Snakybo/Clicked/tree/dragonflight for Dragonflight Beta support.
