### ISSUE TITLE
Error when trying to load into beta.

### ISSUE THREAD

**Issue by Sukodin01** [Snakybo/Clicked#115]
### Describe the bug

See error LUA 
![image](https://user-images.githubusercontent.com/114668330/193078595-b1372b6a-da5e-4269-a575-bc5dea21a4f5.png)
 Using the Dragonflight build.

### Clicked Version

1.8.0

### World of Warcraft Flavor

Shadowlands

### Testing

- [X] Yes
- [ ] No

### Reproduction Steps

load it

**Comment by Sukodin01** [comment]
@Snakybo it loads now, but in chat I get the following.. It let me bind spells, but they will not work and it disabled those buttons on the action bar.
![image](https://user-images.githubusercontent.com/114668330/193092906-fb6b7f47-e37a-4c8c-b661-3017adf88fff.png)

**Comment by Snakybo** [comment]
Default party frames is something that I'm still working on, #109. There are (or were I haven't checked after the last patch) some issues regarding self-cast in the beta. It could be that you have to disable the "Auto self-cast" option in the interface settings.

**Comment by Sukodin01** [comment]
OK that makes sense.. I have not been able to get any other party frames working, so I assume the addon wont work until that is fixed.  Thanks for working on this by the way, love the addon.  I am new to this addon (always used clique) and think the issue with the button not working is that I thought this worked like clique, where it only modified spells while hovering over a unit frame.  Is there a way to make it work like that?  I like the still use my bar buttons for other things and change them out, so did not want to build my DPS spells into this addon if I did not have to.

**Comment by Snakybo** [comment]
Glad you like it :)

Yes you can do that by going into the "Targets" page and then selecting the checkbox next to Unit Frame Target and deselecting the checkbox next to Macro Targets. Then it will only activate when hovering over a unit frame.

**Comment by Sukodin01** [comment]
YOU ROCK!!!!  Thanks for the quick reply!
