### ISSUE TITLE
Add filter for "Loaded" bindings

### ISSUE THREAD

**Issue by oliverfischer83** [Snakybo/Clicked#12]
Hi Clicked-Team,
great work with the Addon!

I excessively using bindings for my druid in all forms and specs. To keep the focus, it would help me to have filter for all bindings, which shows the currently "Loaded" bindings only.

Thanks in advance!

**Comment by Snakybo** [comment]
I'm working on a rework for the binding list currently which separates the loaded from the unloaded bindings. Hope that will make it easier to work with.

**Comment by Snakybo** [comment]
Improved in 0.10.0
