### ISSUE TITLE
Feature Request - Create binds/items based on current bar setup as an option

### ISSUE THREAD

**Issue by jermoo** [Snakybo/Clicked#120]
## Is your feature request related to a problem?
No problem, just trying to cut down on the tedium of creating a setup for a new char. 
btw the discussions link in the app description on SF doesn't work. https://github.com/Snakybo/Clicked/discussions

## Describe the solution you'd like
command switch to create/import a setup based on the current spells on bars, maybe even have an arg to indicate which Bar or bars to use e.g. /cc create 1 2 4 ; this would look at bars 1, 2, and 4 respectively and for the current spec, create the binds. The expectation is that additional modification would be necessary for stance/talent but most of the tedium would be done. maybe even have an arg to remove the spell(s) from the spell bar e.g. /cc create 1 2 4 clear

## Describe alternatives you've considered
finding someone with the same setup and asking for an export. Really not viable since so many people play with different key setups. 

## Additional context
None :)

**Comment by Snakybo** [comment]
Something like this would be great, however from the little bit of research that I've done it would be quite hard to implement as not all action bar addons work the same. So, it'd be custom on a per-addon integration basis.

**Comment by mycoss** [comment]
would it be easier/better to instead of looking at bars, have the option to chance spell/key binds based off of the name of a talent loadout?

**Comment by jermoo** [comment]
The main complaint I hear when discussing 'clicked' is how hard it is to setup. I personally find it easy but it was an idea. No worries.

**Comment by Snakybo** [comment]
I've added an option next to do this which supports the default UI, ElvUI, and Bartender4
![image](https://user-images.githubusercontent.com/3172140/201979899-a8d80526-87c6-4a48-8094-7c9624bf00ba.png)

**Comment by Snakybo** [comment]
I agree it's a neat idea and significantly lowers the barrier of entry :)
