### ISSUE TITLE
autounshift

### ISSUE THREAD

**Issue by rml9ty** [Snakybo/Clicked#121]
I would love an option to include the "console autounshift 0/1" command :)

usually, my macros begin and end with that, depending of whether I want to be thrown out of my current form (druid, shaman etc)  when trying to cast a spell or not.

**Comment by Snakybo** [comment]
I've added this in the form of `/cancelform`. I couldn't find any differences between doing `/cancelform` and `console autounshift 1`. Let me know if there's a reason you prefer the console option instead.
