### ISSUE TITLE
macro targets not working

### ISSUE THREAD

**Issue by rml9ty** [Snakybo/Clicked#122]
### Describe the bug

I've created a spell to be casted on "Macro Targets", "On this target" -> "Player you".

the generated macro says:
/stopspelltarget
/cast [@player] Guardian Spirit

despite that, having targeted another friendly player, pressing the assigned button gives the spell to the target, not myself

### Clicked Version

Clicked 1.8.0

### World of Warcraft Flavor

Shadowlands

### Testing

- [X] Yes
- [ ] No

### Reproduction Steps

see bug

**Comment by Snakybo** [comment]
Unfortunately, this is a known Blizzard bug that I've been hoping was going to be fixed prior to pre-patch.

**Comment by rml9ty** [comment]
am I right in the assumption (that how I experienced it) that all macros being created/bound with Clicked basically just use /cast spell and ignore all conditions? or exactly what is it that is not fixed - and do you think it's something that is going to happen? #blizzard

**Comment by Snakybo** [comment]
This seems to be fixed as far as I can see now.
