### ISSUE TITLE
macro conditions for only part of macro

### ISSUE THREAD

**Issue by rml9ty** [Snakybo/Clicked#125]
a lot of macros for me usually look like this:

/cast [harm,nodead][@targettarget,combat,harm,nodead] smite

this is, as far as I understand it, not possible except just using a macro instead of directly binding the spell. is this considered to be 'too advanced' to be inclunded to the normal way of binding things, or would it somehow be possible/of interest to allow something like I described.

cheers!

**Comment by rml9ty** [comment]
what goes with this, kind of, is selecting for instance more than one "channeling" spell. if what I mean is not clear, I'll try to describe it differently :)

**Comment by Snakybo** [comment]
You should be able to achieve this by creating two bindings and assigning them to the same key, it'll end up in a macro that is functionally identical

**Comment by rml9ty** [comment]
you're right. didn't "get" it, until now. thanks :)
