### ISSUE TITLE
Feature Request - Cancel form option checkbox so that bind can take you out of your current form. 

### ISSUE THREAD

**Issue by jermoo** [Snakybo/Clicked#133]
## Is your feature request related to a problem?
When in a different stance/form some spells won't cancel form out to allow casting. 

## Describe the solution you'd like
would like a checkbox to cancel form AND/OR an option to select a change form from a pulldown. 

## Describe alternatives you've considered
I use a set of conditionals but it ends up being very complex. 

## Additional context
tnx in advance. A work around is in place.

**Comment by Snakybo** [comment]
Is this the `/console autounshift 1` command?
