### ISSUE TITLE
Load conditions: Spell Known Moonfire with Lunar inspiration

### ISSUE THREAD

**Issue by budlongn** [Snakybo/Clicked#137]
### Describe the bug

When using the feral druid lunar inspiration talent, the spell known load condition for moonfire seems to break. If I Iremove the condition it will still cast the spell fine, but I can't figure out if it's a weird spell id that I need to load it with or if it's just blizz weirdness that's breaking it.

### Clicked Version

1.9.1

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

1. Set up moonfire bind with spell known load condition
2. Spec feral with lunar inspiration
3. Go into cat form, wait a few seconds, cast moonfire and the bind unloads

### Debug Output

Version: 1.9.1
Data Version: 1
Project ID: 1
Race: NightElf
Level: 60
Class: DRUID
Specialization: 103 (Feral)
Talents: BcGAYhlYdy9RJ6ROrphOEi69vCAAAAAAQIgIJJk0AaJJJJJAAAAAAoJAAAkIJJBJSLBIAAAAAAgEA
Press Mode: AnyDown
Autogen: True

Possess Bar: disabled
Override Bar: disabled
Vehicle: disabled
Vehicle UI: disabled
Pet Battle: disabled

----- Registered unit frames -----
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
Boss5TargetFrame
CompactPartyFrameMember1
CompactPartyFrameMember1Buff1
CompactPartyFrameMember1Buff2
CompactPartyFrameMember1Buff3
CompactPartyFrameMember1CenterStatusIcon
CompactPartyFrameMember1Debuff1
CompactPartyFrameMember1Debuff2
CompactPartyFrameMember1Debuff3
CompactPartyFrameMember1DispelDebuff1
CompactPartyFrameMember1DispelDebuff2
CompactPartyFrameMember1DispelDebuff3
CompactPartyFrameMember2
CompactPartyFrameMember2Buff1
CompactPartyFrameMember2Buff2
CompactPartyFrameMember2Buff3
CompactPartyFrameMember2CenterStatusIcon
CompactPartyFrameMember2Debuff1
CompactPartyFrameMember2Debuff2
CompactPartyFrameMember2Debuff3
CompactPartyFrameMember2DispelDebuff1
CompactPartyFrameMember2DispelDebuff2
CompactPartyFrameMember2DispelDebuff3
CompactPartyFrameMember3
CompactPartyFrameMember3Buff1
CompactPartyFrameMember3Buff2
CompactPartyFrameMember3Buff3
CompactPartyFrameMember3CenterStatusIcon
CompactPartyFrameMember3Debuff1
CompactPartyFrameMember3Debuff2
CompactPartyFrameMember3Debuff3
CompactPartyFrameMember3DispelDebuff1
CompactPartyFrameMember3DispelDebuff2
CompactPartyFrameMember3DispelDebuff3
CompactPartyFrameMember4
CompactPartyFrameMember4Buff1
CompactPartyFrameMember4Buff2
CompactPartyFrameMember4Buff3
CompactPartyFrameMember4CenterStatusIcon
CompactPartyFrameMember4Debuff1
CompactPartyFrameMember4Debuff2
CompactPartyFrameMember4Debuff3
CompactPartyFrameMember4DispelDebuff1
CompactPartyFrameMember4DispelDebuff2
CompactPartyFrameMember4DispelDebuff3
CompactPartyFrameMember5
CompactPartyFrameMember5Buff1
CompactPartyFrameMember5Buff2
CompactPartyFrameMember5Buff3
CompactPartyFrameMember5CenterStatusIcon
CompactPartyFrameMember5Debuff1
CompactPartyFrameMember5Debuff2
CompactPartyFrameMember5Debuff3
CompactPartyFrameMember5DispelDebuff1
CompactPartyFrameMember5DispelDebuff2
CompactPartyFrameMember5DispelDebuff3
FocusFrame
FocusFrameToT
PetFrame
PlayerFrame
TargetFrame
TargetFrameToT

----- Registered sidecars -----
ClickedSidecar1 (for PartyMemberFrame1)
ClickedSidecar2 (for PartyMemberFrame1PetFrame)
ClickedSidecar3 (for PartyMemberFrame2)
ClickedSidecar4 (for PartyMemberFrame2PetFrame)
ClickedSidecar5 (for PartyMemberFrame3)
ClickedSidecar6 (for PartyMemberFrame3PetFrame)
ClickedSidecar7 (for PartyMemberFrame4)
ClickedSidecar8 (for PartyMemberFrame4PetFrame)

----- Profile -----
DwvxpTnmu0)sRtmj2JPqflcAAxClsiHC52KBtTWXoZ5AGYd8BFx70pszAzst9LA7Z54Z9JCTCKCHu8c6AvwJmBKuyBi(VTHTTMBXDxBF1ihlfRvMYLgOTvvzWYP2s1gftlCezTAs10kxlf1kJQgAc03Qkr(yI)jm4B0ywbLPkTuMDX36eKxgUPSOlODnOuiMp5U7KcOiyJW21qHZMb18z5EZhpv4BjB9hpf3xkABqT(Eq7rz2LF)RCeqGRcPLgfLSHq3vqlfCg4DqNmsHIW6oo8IcWuG6F6rpwkcQfq3YQqZrkHiO45WofwdNNOiTfwok4ihFdl8bJoZvIUy(tz4705BOJQK4j7jzI2oLftksdq3af4JPxnlt8yA29RMQAlwXEPnO6uW98EghClNlFg3fYDsX(BRYbhkz0HOpw)2AzdxWH)edSwJLHR3HvEn4oSZ4EOIDckc0Tsrs2dHtyxOv0UU10r2hlzhHFx69toJWpsYNkfEUiiflsYVzYIyJaVsBHYa3gnSdDHksoc66OCDb5enOadSfDHuiQXckAEkueQxd0jSJ)maLHZ5C9CrOzIH1YTyAwZSzzt6Hn7lCE1h6A1yx00Hi6Wcn3M3N815ltVEy2DqI07cSuZnoRVPxy9zR64k)zwuvTLMO38pS5buX7I7(luGw9oC4ZL9QLDXGYWhh5J)YRAAWYbS5g9owYbs5mGqZ0aiEfC8aJHqWTrOH67)rd7)rD()DRbJFupG)TU6He2Gvqh4)YD0Gd1W1(QQUE4euZlnl(pJVITGXG6Z0)8iSN)z8wpvATU2b)c5ZnMPzRUjF2Y5RMNKV4HvZYxLNCw)EKxT1BO(Dk)zQG4pKPTdGWG8SM4GXWC2BnH3wo5JPwRzJYH9yT)5d(LedfFWH7CV40tkXij8GYLsrv4)7hcUwZtB1Q4mTay5Vd

**Comment by Snakybo** [comment]
I can't reproduce this myself, even with your profile, however, I did make a small change that _may_ fix it.  Let me know if it doesn't.
