### ISSUE TITLE
META/CMD modifiers stopped working

### ISSUE THREAD

**Issue by good3n** [Snakybo/Clicked#138]
### Describe the bug

Sorry to necro an old issue (#84) - but it seems like this beast has emerged from it's cave and is causing problems again. The meta modifier doesn't appear to be working at all on v1.9.1

### Clicked Version

1.9.1

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Lua Errors

None

### Reproduction Steps

1. Bind a skill with Left Mouse button for example.
2. Bind another skill with CMD+Left Mouse button

When using the CMD+Left Mouse, only the original skill that only uses Left Mouse occurs.

### Screenshots

![image](https://i.gyazo.com/8618d0a662ffc4a18cbdaa84e215a917.png)
![image](https://i.gyazo.com/97a28c78fda42e1283b86e3afa3aa96d.png)

### Debug Output

Version: 1.9.1
Data Version: 1
Project ID: 1
Race: Dwarf
Level: 60
Class: SHAMAN
Specialization: 264 (Restoration)
Talents: BgQAfcj78nJtvjmejSqe5Zhm9AAAAAAAAAAAAAIhkQSaRCpoFkU0AJlECpkECAIRAQJRkEB
Press Mode: AnyUp
Autogen: False

Possess Bar: disabled
Override Bar: disabled
Vehicle: disabled
Vehicle UI: disabled
Pet Battle: disabled

----- Loaded binding 1 -----
Keybind: BUTTON1
Hovercast: true
Action: macro
Identifier: 1

/stopspelltarget
/cast [@mouseover] Riptide

----- Loaded binding 2 -----
Keybind: SHIFT-BUTTON1
Hovercast: true
Action: target
Identifier: 1

----- Loaded binding 3 -----
Keybind: META-BUTTON1
Hovercast: false
Action: macro
Identifier: clicked-mouse-meta1

/stopspelltarget
/cast Earth Shield

----- Macro Handler Attributes -----
typerelease-clicked-mouse-meta1: macro
macrotext-clicked-mouse-meta1: /stopspelltarget
macrotext-clicked-mouse-meta1: /cast Earth Shield

----- Hovercast Attributes -----
typerelease1: macro
macrotext1: /stopspelltarget
macrotext1: /cast [@mouseover] Riptide
shift-type1: target

----- Registered unit frames -----
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
Boss5TargetFrame
CompactPartyFrameMember1
CompactPartyFrameMember1Buff1
CompactPartyFrameMember1Buff2
CompactPartyFrameMember1Buff3
CompactPartyFrameMember1CenterStatusIcon
CompactPartyFrameMember1Debuff1
CompactPartyFrameMember1Debuff2
CompactPartyFrameMember1Debuff3
CompactPartyFrameMember1DispelDebuff1
CompactPartyFrameMember1DispelDebuff2
CompactPartyFrameMember1DispelDebuff3
CompactPartyFrameMember2
CompactPartyFrameMember2Buff1
CompactPartyFrameMember2Buff2
CompactPartyFrameMember2Buff3
CompactPartyFrameMember2CenterStatusIcon
CompactPartyFrameMember2Debuff1
CompactPartyFrameMember2Debuff2
CompactPartyFrameMember2Debuff3
CompactPartyFrameMember2DispelDebuff1
CompactPartyFrameMember2DispelDebuff2
CompactPartyFrameMember2DispelDebuff3
CompactPartyFrameMember3
CompactPartyFrameMember3Buff1
CompactPartyFrameMember3Buff2
CompactPartyFrameMember3Buff3
CompactPartyFrameMember3CenterStatusIcon
CompactPartyFrameMember3Debuff1
CompactPartyFrameMember3Debuff2
CompactPartyFrameMember3Debuff3
CompactPartyFrameMember3DispelDebuff1
CompactPartyFrameMember3DispelDebuff2
CompactPartyFrameMember3DispelDebuff3
CompactPartyFrameMember4
CompactPartyFrameMember4Buff1
CompactPartyFrameMember4Buff2
CompactPartyFrameMember4Buff3
CompactPartyFrameMember4CenterStatusIcon
CompactPartyFrameMember4Debuff1
CompactPartyFrameMember4Debuff2
CompactPartyFrameMember4Debuff3
CompactPartyFrameMember4DispelDebuff1
CompactPartyFrameMember4DispelDebuff2
CompactPartyFrameMember4DispelDebuff3
CompactPartyFrameMember5
CompactPartyFrameMember5Buff1
CompactPartyFrameMember5Buff2
CompactPartyFrameMember5Buff3
CompactPartyFrameMember5CenterStatusIcon
CompactPartyFrameMember5Debuff1
CompactPartyFrameMember5Debuff2
CompactPartyFrameMember5Debuff3
CompactPartyFrameMember5DispelDebuff1
CompactPartyFrameMember5DispelDebuff2
CompactPartyFrameMember5DispelDebuff3
FocusFrame
FocusFrameToT
PetFrame
PlayerFrame
TargetFrame
TargetFrameToT

----- Registered sidecars -----
ClickedSidecar1 (for PartyMemberFrame1)
ClickedSidecar2 (for PartyMemberFrame1PetFrame)
ClickedSidecar3 (for PartyMemberFrame2)
ClickedSidecar4 (for PartyMemberFrame2PetFrame)
ClickedSidecar5 (for PartyMemberFrame3)
ClickedSidecar6 (for PartyMemberFrame3PetFrame)
ClickedSidecar7 (for PartyMemberFrame4)
ClickedSidecar8 (for PartyMemberFrame4PetFrame)

----- Profile -----
S3z2UTnoyu4NOciQflQlDACBnMeLmrodqbkuQImJJqLL8OLKj9I(Sp)K2XXXP2HGfDXsh0BQTPOexe)YH)8qgZINehDNOQoRSioKfhDDwX0SIz103tFK(XMhwiIJUmC8KRIgDYO3sFvsAJm50)BEsAvzyYCkfx0w8TpN2w3uo)BFw99Xr1le55)tsEl97uoLunt0CzrwZWBAevVnPUj(Ak3ARswMfXrznI5RtFAsrQi)VBfTIPrYCsM6AkxAox0mSPjj9lYVjTSGkanQlBs54PXhfhj(prAR8H8SQPIkvblRGUNvTlu3tvUmSTP8PSr9ipMYS4OXYKEtsQ4tJF7zHrFAC4)C1Pz1Pxrpl1YC90KQVSQW)4tBtC0xepiR9IJI(W43n5nhD5KjN94DEwvI8cLvRukZltMkR(wKN8GOsw4VqKKpx1wSS2AcvCBRYsONMArUiTrmLEUPlnTC(1jnpLsQW(8eKvqfoQIBISDJYWAQ1mNYXWZchTrAdTOcqBEt2c6hvT1ltrJ6MKNulFuxFXrFy4Pdd3)LVknQmyzbBCX7RkBxSrXA7h2kQsEZ7ZX3NuDZ(VnltI6UqDVsZsYZ(QQUDJ8j0zV5b9ZQRx8VTzlwq1SpvVV9d4n5pq1F7P6MsqY1QQWvnDVObHEEpTC6(srtsUOq1MUQXs2ASUv9LTu0pRE()AzHq9MZUF(le07gYE8le7Rtt99zZNV)c6I7wmXWNZ0Btkke5pl)Px23OFBuHywY6(4LTntllRu9ax((W3Px(2DTghE17V4Slp)QZhEXKpE1zxC1fdhF82TNZlBPxU3Of)f5SAmR)QO8EvhQvVo(IUfLvQ3w3v71tfNTEj7XMU6g6f(MB3DjKAExoEPQw42sQzmLgWCuHS3MAmUkXS28KQh)gQnEDQuzBg1TQooAy4hL)cnUvEwZdl)mL5RU61dZVVKh1sJzhhD8O3n8YtKdGP69LnL60MDtMC81bC6BcTL3x54SpF0UntOpnSJj4Jq)aBRb9igc9gBsLCuHOzYXqFJxNGAqJRTf0buJV)aC)wPg38Jo8gOnQ)ynnOnVghGiJRi46aMEfQbXi2IAqCKFTuJLYjIoF0jNirgoAGmObnmczW4ChEaygh4knaZyPYV)WvAaMX26W)PPqPNZmC1GzyBiZW2YIdIbigsfYyUPu)5K)0MBkqmaX4N0CtTLkdpnigogsmc8D7raJthnz4tr2atr1UMGyapKswa845Z25JZ()Hvar65YngOb8GqagnfvEEiMgh6rchZpfMFQ4ieb91HV)vJTDhpMg(Aam8meyW4CwaygGzOwdhygQGiJxSo(Gid1YtAFREQ)8IdoxdMbnSVrImyb2mS2Po4xXTqNb0zaDgBSu4776mc0Gz4BkZWIB7tJ40B8SbwVT7E1UdDgiyg72fkiyg70Lg)5PZGzPb0GBi0yaMAQdFJ9bzgqMbKzazgRTObtzd8xXwFbgImCSD9DGhnq8mq8mE0H)yrtHfn1ZDh)by8myA4fCUPEb32L3NwZTyQPWut9BBdebM0aM04xJjnyA4fCUPEb3J5gq4geoJd6nDkm3uyUPWCtH5M6P5MsdVGZn1l4mlUTe4aObGgyT2Q2dsWCtH5M6WFUP0Wo4CtTdU9axpGmWgicSNXQnSyGmaY4WhzOHjWLXKWm)zynaHZarahrahrax6HASsBxDEr8SaVCW5OpMg2aNBQnW98dcaZamdWmaZamJDDmDC4Xm0Wg4CtTbUJntgkeendendendendOZ4XZLUdCDgAydCUP2a3HXTCWgIoeAaHgqObeA0zeAyRHnW5MAdCpxSbfcIbigGyaIr3HyOHlWLh2EgfbCFhEamboygGzaMbygDhMHgMax6kpJygo2UoYyHG4zG4zG4zG4zG4z0nINHTg2apWuBG7WzboWh4qPbuAaLgqPr3rPHg(apWyFGhWzwoqPbm1hm1hm1hCOXooZJp4wTT2A4d8at9bo3Ycg0a6mGodOZa6m6o6m0Wh4sJ5zuen8yEwyVdbmdWmaZamJUdZqdJGhyQrWzCURlMBkana0aqdan6oqdnCcEGPobNfyB5bx9bObGgaAaOr3bAOHvWdm1k4((U(95Tpec2MJt31LN)e4abhBg6yBkStSnf6OHtWdm1j4bClR(SodWmsL)5LGzSUwa7g6y3q)GF3q3rdVGl9ZTrrbN55Z86Zr0aqdanE(zokGgaAC4dn0Wm4mlJDdo3XYQpVfIaQbOgGAeTUkatpv3y6P0Wn4mltTdolGZ71BVTGAaQbOgGAuuEFH0EV31n2drC0Wo4mlt9dUnZ2YfH1alFkekCS8PWYNQ7qn0Wp4QnceJIRHVpRxVZtbPgqQbKAaPgDnPgA4iCMCRaXiObJ5A5HvDlKAaPgqQbKA0DKAOHNWzYndeJOgo(Eb96J6vO1aAnGwdO1ORP1qdtHZSm1v4dy2YTHKEZ5PXrxozYzHS4OfjvIIM4OzvLTlEdyhGDa2byh)qSJJIJQeZAZtQgvKCDUs7A0TL3jQstQBurApRjjVooAy4hL)sDtwEwZdl)S0HTlVAkL0iuVsYJAlYOl54rVB4LNmHUA5)IAEyHiok68rNCc9Xqhn8goZYuZHZS428(85QbOgGAaQbOg)qudIrSf1G4i)wPgUA4oCASFdNNk2aM8KCQ3O4asn25smeBPi4e8dNGFDJvFRRg2dNjnRNrb3W3jWgknqeXreXreXreX7mre3vh7HZm1E4SaU1a)ESudQS)D29c)F27SN32ggim8FjDKwF4Xmu02H6oypBavxwdbiZeyRmK)9rsPaXbbf4WT1JpRb0zWlp(994ZXu)4L70(5qAC85Rd95JVhKF9NLE6Xl)Q)TAlx)jkZXs)yzhd5Bt95tPdlLooFSBd5ZJPJ739ZDF5UZ(zPCF7eRfwEAS)2T7)W7)2d)4HD3)XNdl(XnbX()EM1)bpn2)s663ZFDzoo)BBMiQbrniQHtIAOrpCXUE4stSKFf)GAWunyQgmvdVnvdn6Hlw1dVRAolt5oudygWmGzaZWBmdnYHlwLdx2gcBk51xiudOgqnGA4nQHg7WfZ2HptncK1GzHZSWzw4mlC)mlCn2HlwTdVr6kA5WjQbrniQbrn8wudnYHlwLdFDruvYx7wOgqnGAa1WBudnAHlw1cpivTlTBvSg(b1aQbudOgoJAmNe4WX9d5P05R9tdpMxU3(tZ)LFNYtd)ziD94ormRf(2MUUsMAm)fhYAWZgE6D2jVaS8cW(F)laBTgVWfREHlsBvrN1aQbzniRbzn8wwdnIHVSrqmTnrQL6ySGlOcObqdGgan8g0qJx4bREHh3ecBk5HHd1aQbudOgEJAOXl8fHlmf1igBRl5vqfqdGganaA4nOHgXWdMfdVn2WOWXWpm8dd)WWp3y4xTgVWdw9cVREz5vvSx6wcAqqdcAqqdVf0qJv4bRwHVk4xj)ymb1aQbudOgEJAOrl8GzTW32g4s32t)u0pf9tr)u(PFknAHhSQfU0121YunGAa1aQbud3qnA0OfEWQw4X26Tf9IlKgQOHkAOIgQCwdvnA0cpyvl8MkPcb)iQbrniQbrn8tudnwHhTAfESBtSMRqfudOgqnCm141278N1gggik(NOcUrnooRLgkHqZqfDvGS1HTOYNerQ)jF7ZDYKbt8qPJbTzoX9ZsAWpFwCpF7pYFe(goPAvYyaCUd3BLA8xAlCX)UTWfITLJ1OCy4TfvJIQrr14EPwJKs2FY)vG942J5VvLXgdo959DEuDSEvDvvTsI6rqjLd6rnoZjCNY(H10tfoMRAzw6pkQR4snMs)DiM8twQ7smQzgznSBy8uZvg7CWiGjTBjcByc52CFgHvInRBiDVPzXoCqJDzklXOHyqdGWVPNTOXI97n0oJGxfuSx5LlhzRs6dxDhyPhpaNFX)dYVDrlL3hOogT9iyEZBYMgCKhk59UKL2TPRhTODuh4P7G1auO8DU1P7(0zJPSRdNuQl

**Comment by good3n** [comment]
Just to further test - I wiped everything and only created one bind (cmd+mouse button 1) and it does nothing.

**Comment by Snakybo** [comment]
Yeah, the auto self-cast behavior has changed in 10.0. I should add a prompt to disable it completely when using Clicked as the new behavior is obnoxious

**Comment by good3n** [comment]
> Yeah, the auto self-cast behavior has changed in 10.0. I should add a prompt to disable it completely when using Clicked as the new behavior is obnoxious

I actually think this was just part of it. I still cannot get CMD to work - however not just your plugin. Clique as well.

**Comment by good3n** [comment]
![image](https://user-images.githubusercontent.com/7230649/203175233-a28528f2-4cd1-4254-83aa-23b9c3859a76.png)

Not sure if this is relevant to what's happening @Snakybo
