### ISSUE TITLE
Feature Request - Keybinds on hotbars

### ISSUE THREAD

**Issue by AbooseYou** [Snakybo/Clicked#139]
## Is your feature request related to a problem?
showing keybinds for skills on hotbars

## Describe the solution you'd like
I'd like to be able to to see keybinds on hotbars to make it easier to play new class with new binds

## Describe alternatives you've considered
i don't no about this

## Additional context
Top row is what i mean by adding binds to hotbars

![DtoQukqukP](https://user-images.githubusercontent.com/5286813/203461062-f75356a8-1a8c-4b6d-b769-16e7b200034d.png)

**Comment by Snakybo** [comment]
Currently, I consider this to be out-of-scope for this addon. However, in the future I may develop a companion addon or new module that allows you to create action bar buttons for bindings.
