### ISSUE TITLE
[improvement] Class and Character selectors in Load Options

### ISSUE THREAD

**Issue by tflo** [Snakybo/Clicked#14]
I’m completely new to Clicked, and I’am using a combination of SpellBinding, MuchMoreMacro and Clique until now. With Clicked I now see a chance to bring all this under one “hood”!

However, there is one issue, which could be a minor issue or a deal breaker:

The main point of using [SpellBinding](https://www.curseforge.com/wow/addons/spellbinding) is that it provides a fine-grained and hierarchic system to make a binding either global, class-specific, or character-specific (even race or faction is possible).

In case you don’t know SpellBinding, here a screenshot to illustrate what I mean:

![SpellBindingGUIsmall](https://user-images.githubusercontent.com/1410282/97743119-7ce2bf80-1ae5-11eb-8625-5b6e9f09364b.jpg)

Clicked provides something comparable with its Load Options (and goes even further with its very special options). But what I’m missing in the Load Options are Class and Character selectors, like SpellBinding offers them.

Looking at the other options Clicked offers, this seems to be something pretty basic and simple, so I’m almost sure I’m missing the obvious here.

I’ve tried with the Spec selectors set to all specs, but this gets soft-translated to other classes’ specs when I open it on a different toon. (Bug?)

The *workaround* I’m currently using is to limit the binding to the availability of a spell that exists for all specs of one class but not for other classes. However, this feels wonky, ugly and just not right, and, in addition, it might not work with all classes or with class changes in future expansions.

Before you ask: Using a different _profile_ for each class/toon is out of range, because I have about 10 different toons/classes and 80–90% of my bindings are global. Using different profiles would mean that in 80–90% of the cases I’d have to repeat every modification or addition I do with every toon (i.e. 10 times).

---

So, any chances to see a class/character selector in  the Load Options? Or did you in fact intend that the Spell Availability selector is used for that?

And, as said, if I’m just missing the obvious and this is already possible, give me a hint ;)

– Tom

**Comment by Snakybo** [comment]
I was going to mention that I originally intended on using a different profile per character, however you have a valid point there. I'm currently working on improving the binding list as in its current state it will be impossible to use when you have abilities from 10 different characters in there. With that rework I'll also look into adding better support for multiple classes.

**Comment by tflo** [comment]
> I was going to mention that I originally intended on using a different profile per character, however you have a valid point there. 

Yep, profiles work only if the toons are vastly different (i.e. not many shared macros/binds). For example different profiles for a healer, a DPS, and the banker, make sense. But not if you have 10 DPS toons which share the bigger part of the macros/binds.

Or, if someone uses the add-on only to bind spells, then profiles are also useful, since spells tend to be different for each class anyway. 

> I'm currently working on improving the binding list as in its current state it will be impossible to use when you have abilities from 10 different characters in there. 

Depends. In my use-case (bigger part of macros/binds shared between classes) the current binding list is perfectly fine. But yes, if you have binds for every other *spell* of each class, then it will get crowded ;) However, for that case there are still profiles…

---

So, what do you propose? Should I go with the Spell selector workaround for the time being? Or any better idea?

**Comment by Snakybo** [comment]
For the time being that would be the best option yeah, I'll update this ticket when there's support for class load options 🙂

**Comment by tflo** [comment]
Great! And maybe also a Character option. Not as essential as a Class option, but as you’re at it… 🙄

Many thanks for this good add-on! Clique is already disabled on all toons. Going to transfer now the macros and bindings from MuchMoreMacro and SpellBinding too 🙂

– Tom

**Comment by tflo** [comment]
I just had another idea that _maybe_ could be an alternative to a Class/Char load option:

You have already a great Copy and Paste button there, which also works between profiles, it seems. 

Now I see the following:

Replace (or supplement) the Copy/Paste button by a “Copy to” button. This “Copy to” button should have a drop-down menu with these properties:

* You can select one or more destination profiles
* A “Select all” and “Deselect all” function
* An option “Copy also binding”
* An option “Overwrite existing with the same name”

This would allow to have tons of profiles and still being able to (relativly) quickly deploy changes to selected/all profiles.

But I have no clue if this feasible within the limits of the libraries you are using. (?)

**Comment by Snakybo** [comment]
Customizable groups and class load options will be in the next major version. No automatic per-character storage, however there will also be a "Character Name" load option which can be used to serve the same purpose.

**Comment by tflo** [comment]
Insanely great! Thank You!

**Comment by tflo** [comment]
0.10.0 is a fantastically great update, many thanks! Special thanks for implementing all the conditions I suggested above, and even more!

Now Clicked definitely is my all-in-on add-on, instead of my former three add-ons. So great!

Thank you!

– Tom
