### ISSUE TITLE
Troubleshooting - bug?

### ISSUE THREAD

**Issue by jermoo** [Snakybo/Clicked#140]
### Describe the bug

when trying to cast adaptive swarm using CTRL-2 (or other binds as well, straight-up 2 does the same thing) I get an error on the screen 'you can't use that here' and the spell doesn't cast. I can click on the spell in the spellbook and it casts as expected. I've tried different binds with the same results. Not sure what I'm doing wrong/missing. 
Thanks in advance. 
Everything else appears to work. I've even taken my leggo off, no joy. 

### Clicked Version

1.9.1

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Lua Errors

none

### Reproduction Steps

1. create an entry with no conditionals or options, bind to a key, select adaptive swarm from the spellbook 

### Last Working Version

unknown

### Debug Output

[Growl_Clicked_Dump.txt](https://github.com/Snakybo/Clicked/files/10075929/Growl_Clicked_Dump.txt)

**Comment by good3n** [comment]
This is due to Blizzard's new "Self Cast Key" feature. If you set it to "None" it should resolve your issue.

You'll find this in the Combat tab in the interface options.

**Comment by jermoo** [comment]
I'll look, it doesn't seem to affect any other spell. but ty

**Comment by jermoo** [comment]
![image](https://user-images.githubusercontent.com/10830153/203607698-bfedc66d-0c24-4c4d-b2a7-55ba44f7cdfc.png)
not set..

**Comment by jermoo** [comment]
I can do all other spells on me or any  other player, just not adaptive swarm

**Comment by Snakybo** [comment]
Importing your profile and it seems to work okay for me
![image](https://user-images.githubusercontent.com/3172140/203672119-24ee9b1c-3f6d-4d34-8c5e-c3936b7dea9c.png)
![image](https://user-images.githubusercontent.com/3172140/203672145-6bbf525a-af2e-408f-883a-80857b6067cf.png)

**Comment by jermoo** [comment]
interesting, ty. at least we know it's not clicked.
