### ISSUE TITLE
Charge spells not working after specialization switch

### ISSUE THREAD

**Issue by Mike-Last** [Snakybo/Clicked#144]
### Describe the bug

On my Evoker when switching specialisations the keys bound to charge skills only output 'Spell not learned'.
A UI 'reload' does not fix it, but exiting the game and loading it again does.

For Example I am on my Evoker as Devastation and switch to Preservation then Dream Breath, Spiritbloom and Firebreath all fail as above.

I suspect this is a Blizzard side bug as I also had issues with weak auras and had to bind multiple triggers, i.e. for Dream Breath 382614 and 355936.

I tried setting up multiple keys with different spell IDs, but iu suspect your addon calls them by name and doesn't respect the ID entered.

### Clicked Version

Clicked 1.9.1

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

1. As a Devastation Evoker switch to Preservation specialisation with Dream Breath talent enabled.
2. Try to cast with a binding linked to Dream Breath
3. See the error 'Spell not learned'

**Comment by Snakybo** [comment]
I also believe this is a Blizzard bug, it also doesn't work if you just type `/cast Dream Breath`. I also tried `/cast 355936`, but that doesn't do anything unfortunately, so your fix of trying to use spell IDs won't work.

I can't really think of a workaround for this at the moment, will look into it a little bit more.
