### ISSUE TITLE
[Bug] Weird Bug With Dispels

### ISSUE THREAD

**Issue by Gennoken** [Snakybo/Clicked#147]
### Describe the bug

Usually i bind my dispels on all my chats in "ALT-LeftClick" mouseover.
The problem is whatever the unite i'm hovering it always casts it on me.

Notes:
- I've tried binding a spell, and a macro same problem.
- I've tried on my Evoker and my Druid same problem.
- All other spells works just fine except dispels.
- For now i've only tested Party Frames
- Iv' tried messing with conditions (friendly/alive..etc) with no luck
- I'm using ElvUI 13.06
- Been using the same Macro/Behavious in "Clique" addon never had this kind of issue.
- The macro used is:
```lua
/cast [@mouseover]SpellName
/tar [@mouseover]
```
Thank you

### Clicked Version

1.10.1

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [ ] Yes
- [X] No

### Reproduction Steps

1. Use macro mentioned above
2. Dispel teammate in party frames
3. it dispels me instead

**Comment by Snakybo** [comment]
That's caused by the self-cast option in the interface settings. In DF the behavior changed, it now always takes priority. To fix this, set the self-cast key in the options to "None".
