### ISSUE TITLE
Feature Request: add tooltips and an "icon" that can be placed on a bar to view currently active spell

### ISSUE THREAD

**Issue by jermoo** [Snakybo/Clicked#148]
## Is your feature request related to a problem?
One user I was helping wanted to be able to see the active/available spell on their bar. 

## Describe the solution you'd like
add tooltip and an "icon" that can be dragged to the bar to view cd and /or default spell. 

## Describe alternatives you've considered
custom macro outside of clicked, but it's too limited in functionality and can't be layered the way clicked can. 

## Additional context
I don't see how this would work ultimately the way the user wanted it. I said I'd suggest it.

**Comment by Snakybo** [comment]
Currently, I consider this to be out-of-scope for this addon. However, in the future I may develop a companion addon or new module that allows you to create action bar buttons for bindings.
