### ISSUE TITLE
Addon doesn't work but only on my paladin

### ISSUE THREAD

**Issue by gotex007** [Snakybo/Clicked#149]
### Describe the bug

It will let me open the window but doesn't actually let me create any macros or anything. Constantly throws errors. Works fine on my hunter, warlock, druid, and demon hunter.

### Clicked Version

1.10.1 PALADIN

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Lua Errors

174x Clicked/Core/BindingProcessor.lua:754: attempt to get length of local 'entries' (a nil value)
[string "@Clicked/Core/BindingProcessor.lua"]:754: in function `IsTalentMatrixValid'
[string "@Clicked/Core/BindingProcessor.lua"]:815: in function `CanBindingLoad'
[string "@Clicked/Core/BindingProcessor.lua"]:473: in function `ReloadActiveBindings'
[string "@Clicked/Core/Clicked.lua"]:122: in function <Clicked/Core/Clicked.lua:117>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@DataStore/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

### Reproduction Steps

1. Load into game as paladin
2. Hear errors
3. Open clicked
4. Hear errors
5. Try creating a macro
6. Hear errors as nothing happens when clicking any of the create buttons
7. Open BugSack to see many of the listed lua error

**Comment by Snakybo** [comment]
Can you run `/run Clicked:UpgradeDatabase(1)` and try again?

**Comment by Snakybo** [comment]
Hm, any chance you can post your SavedVariables?

**Comment by gotex007** [comment]
Github doesn't take .lua files so I had to save it as a .txt. Hope that's fine.
[Clicked.txt](https://github.com/Snakybo/Clicked/files/10223145/Clicked.txt)

**Comment by Snakybo** [comment]
Thanks! Will have a look tomorrow

**Comment by Snakybo** [comment]
This should fix it, not sure what went wrong with your profile: [Clicked.txt](https://github.com/Snakybo/Clicked/files/10237404/Clicked.txt)

**Comment by gotex007** [comment]
I'm having the same problem on my warrior now too.

18x Clicked/Core/BindingProcessor.lua:774: attempt to get length of local 'entries' (a nil value)
[string "@Clicked/Core/BindingProcessor.lua"]:774: in function `IsTalentMatrixValid'
[string "@Clicked/Core/BindingProcessor.lua"]:852: in function `CanBindingLoad'
[string "@Clicked/Core/BindingProcessor.lua"]:474: in function `ReloadActiveBindings'
[string "@Clicked/Core/Clicked.lua"]:122: in function <Clicked/Core/Clicked.lua:117>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by gotex007** [comment]
I'm having the same problems on my monk as well.

64x Clicked/Core/BindingProcessor.lua:774: attempt to get length of local 'entries' (a nil value)
[string "@Clicked/Core/BindingProcessor.lua"]:774: in function `IsTalentMatrixValid'
[string "@Clicked/Core/BindingProcessor.lua"]:852: in function `CanBindingLoad'
[string "@Clicked/Core/BindingProcessor.lua"]:474: in function `ReloadActiveBindings'
[string "@Clicked/Core/Clicked.lua"]:122: in function <Clicked/Core/Clicked.lua:117>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
