### ISSUE TITLE
Not new but can give more insight on "harm" target not allowing mouseover heals in clicked

### ISSUE THREAD

**Issue by nedempst** [Snakybo/Clicked#15]
This seems to be only something that is an issue with druids and forms though I can't be sure.

But anyway as you know in our emails, the issue is that if I have a target and am in  form that has a "harm" spell that can be used it wont allow the use of my mouseover say rejuv or regrowth while I have something "harm" targeted.

I did try a ton of combos but I believe it's still issues with the spec  load or whatever but when I use macros like below it works fine.

/cast [@mouseover,nodead,help] Rejuvenation; [@mouseover,nodead,harm] Sunfire;[@target,nodead,help] Rejuvenation; [@target,nodead,harm] Sunfire

/cast [@mouseover,nodead,help] Rejuvenation; [@target,nodead,harm] Strength of the Wild;[@target,nodead,help] Rejuvenation; [@target,nodead,harm] Strength of the Wild

/cast [@mouseover,nodead,help] Rejuvenation; [@target,nodead,harm] Shred;[@target,nodead,help] Rejuvenation; [@target,nodead,harm] Shred

/cast [@mouseover,nodead,help] Rejuvenation; [@target,nodead,harm] Maul;[@target,nodead,help] Rejuvenation; [@target,nodead,harm] Maul

Just trying to help you figure out what's the issue.  Hope it helps

![image](https://user-images.githubusercontent.com/59960468/97812623-727b1e00-1cbd-11eb-892d-f4b437e56896.png)

**Comment by Snakybo** [comment]
See #11
