### ISSUE TITLE
Infinite loop in  #063c8b3

### ISSUE THREAD

**Issue by Dairyman** [Snakybo/Clicked#154]
### Describe the bug
Never mind. Timer is not Ticker 🤦 .

### Clicked Version

1.10.2

### World of Warcraft Flavor

Dragonflight

**Comment by Snakybo** [comment]
Huh? 😄

**Comment by Dairyman** [comment]
In code you called the handler Ticker and I miss read that as you using `C_Timer.Ticker` and not `C_Timer.Timer`. 😆

**Comment by Dairyman** [comment]
But you could use `C_Timer.After`, which is intended to be used in this situation. `C_Timer.Timer` is when you need the cancel functionality. 🤷
