### ISSUE TITLE
Talent selection on non-english locale not working

### ISSUE THREAD

**Issue by m33shoq** [Snakybo/Clicked#155]
### Describe the bug

Getting issue when trying to select talent for keybind

### Clicked Version

1.10.2

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [ ] Yes
- [X] No

### Lua Errors

5x Clicked/Config/GUI.lua:115: bad argument #3, expected table but got string
[string "=[C]"]: in function `assert'
[string "@Clicked/Config/GUI.lua"]:115: in function `GUI_EditBox'
[string "@Clicked/Config/Bindings.lua"]:859: in function <Clicked/Config/Bindings.lua:808>
[string "@Clicked/Config/Bindings.lua"]:2075: in function <Clicked/Config/Bindings.lua:2073>
[string "@Clicked/Config/Bindings.lua"]:2261: in function <Clicked/Config/Bindings.lua:2247>
[string "@Clicked/Config/Bindings.lua"]:2753: in function <Clicked/Config/Bindings.lua:2739>
[string "=[C]"]: ?
[string "@Bartender4/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...aceBartender4/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Bartender4/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Bartender4/libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Clicked/Config/Bindings.lua"]:2809: in function <Clicked/Config/Bindings.lua:2701>
[string "@Clicked/Config/Bindings.lua"]:2902: in function <Clicked/Config/Bindings.lua:2888>
...
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:1085: in function `Select'
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:1093: in function `SelectByValue'
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:853: in function `ConstructTree'
[string "@Clicked/Config/Bindings.lua"]:3037: in function `BindingConfig_Redraw'
[string "@Clicked/Core/BindingProcessor.lua"]:482: in function `ReloadActiveBindings'
[string "@Clicked/Config/GUI.lua"]:45: in function <Clicked/Config/GUI.lua:26>
[string "=[C]"]: ?
[string "@Bartender4/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...aceBartender4/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Bartender4/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Bartender4/libs/AceGUI-3.0-41/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...r4/libs/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

### Reproduction Steps

1. Check "talent selected" in load conditions
2. Getting error 

### Screenshots

![image](https://user-images.githubusercontent.com/91337254/207502683-7858da2a-8cc9-4749-96bc-72327c46d86b.png)
![image](https://user-images.githubusercontent.com/91337254/207502697-ea011f6a-0136-4882-8d3a-078b582fdb99.png)

**Comment by Snakybo** [comment]
Should be fixed in 1.10.3, sorry about that!
