### ISSUE TITLE
Feature Request: Add conditionals Dragonriding and Dragonridable 

### ISSUE THREAD

**Issue by jermoo** [Snakybo/Clicked#159]
## Is your feature request related to a problem?
Add conditionals Dragonriding and Dragonridable. 

## Describe the solution you'd like
When setting keybinds for dragonriding, the only conditional that seems to work well is [mounted]. Flying or Flyable don't seem to work in Dragonflight. 
It's not been an issue, more of a convenience feature.

## Describe alternatives you've considered
Just used mounted for the conditional and change the group order to have the flying commands at the top. 

## Additional context
[dragonriding], [dragonridable]

**Comment by Snakybo** [comment]
As far as I know there are no macro conditionals available for dragonriding. I'd very much like to add these but without the conditionals in place, there's nothing I can do at this time.

![image](https://user-images.githubusercontent.com/3172140/208956016-6f0c908f-89d5-44f1-8ea0-99e7ba167741.png)

**Comment by jermoo** [comment]
these work
/cast [dragonridable] Highland Drake
/use [dragonriding] surge forward

**Comment by Snakybo** [comment]
Both of those cause the "Unknown macro option" error for me

**Comment by Dairyman** [comment]
They work, cause non-existent macro condition evaluate to true.
```
/cast [dragonridable] Highland Drake
/use [dragonriding] surge forward
```
is the same as
```
/cast [] Highland Drake
/use [] surge forward
```

**Comment by jfdhuiz** [comment]
I am trying to use this method https://us.forums.blizzard.com/en/wow/t/binding-dragonriding-spells-conditionally-to-normal-macros/1423380/6 but when I try to use Surge Forward(Dragonriding) it changes to the spellID and it won't work (on an Evoker). I worked around it by using the macro option but I think its a bug

**Comment by jfdhuiz** [comment]
Opie and M6 also have a neat way to check for if a user is in dragon isles (useful for custom mount macro). It has a condition to check [in:dragon isles] (which also works in instance Nohkud Offensive). Quoting "The <tt>[in:dragon isles]</tt> extended conditional is now satisfied within the Nokhud Offensive instance. If you need to check for non-instanced Dragon Isles, consider using <tt>[in:dragon isles,in:world]</tt>." Looking at the code, it checks for 		[2444]="world/dragon isles/df",
		[2516]="party/dragon isles/nokhud", in OPie\Libs\ActionBook\Conditionals.lua but in Clicked it requires names instead of zone IDs. I went with checking for zones Valdrakken; Thaldraszus; Ohn'ahran Plains; The Azure Span; The Waking Shores; The Forbidden Reach; The Nokhud Offensive but its a bit long for my taste
