### ISSUE TITLE
Some LUA Errors

### ISSUE THREAD

**Issue by nedempst** [Snakybo/Clicked#16]
Hi there as requested in email, and happens usually when zoning but sometimes doing dungeons etc so far.  Some of these might be duplicates just sending anyway

![image](https://user-images.githubusercontent.com/59960468/98060688-2bd82000-1e85-11eb-9d9c-597ac224ca15.png)
![image](https://user-images.githubusercontent.com/59960468/98060719-3c889600-1e85-11eb-92b0-fbfe868943f8.png)
![image](https://user-images.githubusercontent.com/59960468/98060731-47432b00-1e85-11eb-830d-390624320b92.png)
![image](https://user-images.githubusercontent.com/59960468/98060871-95f0c500-1e85-11eb-9a7a-42bfc86803ee.png)

**Comment by Snakybo** [comment]
Should be fixed in 0.10.1, thanks for the report!

**Comment by nedempst** [comment]
Of course your addon is very dear to me :)

------ Original Message ------

**Comment by nedempst** [comment]
Hi. Is it possible to include like an arena conditional to only load a 
particular binding if in an arena or skirmish ?

------ Original Message ------

**Comment by nedempst** [comment]
Hi there.

How about a load thing for if you are in a BG, arena etc?   Toggles for 
different types of content?

Thanks

**Comment by Snakybo** [comment]
I just added that twenty minutes ago 😄

**Comment by nedempst** [comment]
Nice can't wait to d-l it as it would be nice to not have to manually 
toggle :)

------ Original Message ------

**Comment by nedempst** [comment]
Works great now!

------ Original Message ------
