### ISSUE TITLE
Error upon logon:  Clicked\Core\BindingProcessor.lua:800: attempt to index global 'C_ClassTalents' (a nil value)

### ISSUE THREAD

**Issue by rbpaiett** [Snakybo/Clicked#163]
### Describe the bug

I expected it to work and all my bindings are greyed out and nonfunctional.

### Clicked Version

Clicked 1.10.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Lua Errors

Message: Interface\AddOns\Clicked\Core\BindingProcessor.lua:800: attempt to index global 'C_ClassTalents' (a nil value)
Time: Thu Jan  5 21:16:33 2023
Count: 1
Stack: Interface\AddOns\Clicked\Core\BindingProcessor.lua:800: attempt to index global 'C_ClassTalents' (a nil value)
[string "@Interface\AddOns\Clicked\Core\BindingProcessor.lua"]:800: in function `UpdateTalentCacheAndReloadBindings'
[string "@Interface\AddOns\Clicked\Core\BindingProcessor.lua"]:791: in function <Interface\AddOns\Clicked\Core\BindingProcessor.lua:789>
[string "@Interface\SharedXML\C_TimerAugment.lua"]:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: self = <table> {
 ProfileOptions_Open = <function> defined @Interface\AddOns\Clicked\Config\Profile.lua:293
 IsRetail = <function> defined @Interface\AddOns\Clicked\Core\Init.lua:40
 AbilityTooltips_Initialize = <function> defined @Interface\AddOns\Clicked\Core\Tooltips.lua:172
 StatusOutput_Open = <function> defined @Interface\AddOns\Clicked\Debug\StatusOutput.lua:275
 CreateWeakAurasIcon = <function> defined @Interface\AddOns\Clicked\Integrations\WeakAuras.lua:449
 UnregisterComm = <function> defined @Interface\AddOns\Clicked\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:148
 UpdateClickCastHeader = <function> defined @Interface\AddOns\Clicked\UnitFrames\ClickCastHeader.lua:191
 CanUnitBeHostile = <function> defined @Interface\AddOns\Clicked\Core\Utils.lua:1165
 IsWotLK = <function> defined @Interface\AddOns\Clicked\Core\Init.lua:61
 GetLocalizedRaces = <function> defined @Interface\AddOns\Clicked\Core\LocaleUtils.lua:279
 InteractionType = <table> {
 }
 GUI_ToggleHeading = <function> defined @Interface\AddOns\Clicked\Config\GUI.lua:398
 StatusOutput_UpdateHovercastAttributes = <function> defined @Interface\AddOns\Clicked\Debug\StatusOutput.lua:320
 IsFrameBlacklisted = <function> defined @Interface\AddOns\Clicked\UnitFrames\ClickCastFrames.lua:94
 IsStringNilOrEmpty = <function> defined @Interface\AddOns\Clicked\Core\Utils.lua:752
 GetLocalizedClasses = <function> defined @Interface\AddOns\Clicked\Core\LocaleUtils.lua:251
 StatusOutput_Initialize = <function> defined @Interface\AddOns\Clicked\Debug\StatusOutput.lua:256
 GroupState = <table> {
 }
 UnregisterAllComm = <function> defined @Interface\AddOns\Clicked\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:169
 BindingTypes = <table> {
 }
 OnCommProgress = <function> defined @Interface\AddOns\Clicked\Config\Profile.lua:341
 IsMacroCastEnabled = <function> defined @Interface\AddOns\Clicked\Core\Utils.lua:1126
 GetCachedBindingState = <function> defined @Interface\AddOns\Clicked\Core\BindingProcessor.lua:1596
 GUI_MultiselectDropdown = <function> defined @Interface\AddOns\Clicked\Config\GUI.lua:294
 Classic_GetLocalizedTalents = <function> defined @Interface\AddOns\Clicked\Core\LocaleUtils.lua:564
 Classic_GetShapeshiftForms = <function> defined @Interface\AddOns\Clicked\Core\Utils.lua:881
 GetWoWUnitFromUnit = <function> defined @Interface\AddOns\Clicked\Core\Utils.lua:410
 IsSetBonusActive = <function> defined @Interface\AddOns\Clicked\Core\Utils.lua:1012
 GetAvailableShapeshiftForms = <function> defined @Interface\AddOns\Clicked\Core\Utils.lua:910
 IsClassic = <function> defined @Interface\AddOns\Clicked\Core\Init.lua:47
 UpdateMacroFrameHandler = <function> defined @Interface\AddOns\Clicked\Core\CommandProcessor.lua:139
 GetBlacklistGroup = <function> defined @Interface\AddOns\Clicked\Config\Blacklist.lua:171
 GetDataFromString = <function> defined @Interface\AddOns\Clicked\Core\Utils.lua:395
 IsHovercastEnabled = <function> defined @Interface\AddOns\Clicked\Core\Utils.lua:1114
 BlacklistOptions_Refresh = <function> defined @Interface\AddOns\Clicked\Config\Blacklist.lua:296
 GetColorizedString = <function> defined @Interface\AddOns\Clicked\Core\Utils.lua:1223
 SetBlacklistGroup = <function> defined @Interface\AddOns\Clicked\Config\Blacklist.lua:163
 BindingConfig_Initialize = <function> defined @Interface\AddOns\Clicked\Config\

### Reproduction Steps

Logon, Lua Error, bindings not loading or working.

### Last Working Version

Clicked 1.10.3

### Debug Output

Message: Interface\AddOns\Clicked\Debug\StatusOutput.lua:244: attempt to index upvalue 'data' (a nil value)
Time: Thu Jan  5 21:20:35 2023
Count: 1
Stack: Interface\AddOns\Clicked\Debug\StatusOutput.lua:244: attempt to index upvalue 'data' (a nil value)
[string "@Interface\AddOns\Clicked\Debug\StatusOutput.lua"]:244: in function <Interface\AddOns\Clicked\Debug\StatusOutput.lua:239>
[string "@Interface\AddOns\Clicked\Debug\StatusOutput.lua"]:292: in function `StatusOutput_Open'
[string "@Interface\AddOns\Clicked\Core\Clicked.lua"]:86: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:4933: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4596: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4632: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: (*temporary) = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:120
(*temporary) = <table> {
 OnRelease = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:90
 OnWidthSet = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:95
 SetStatusText = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:120
 sizer_se = <unnamed> {
 }
 sizer_e = <unnamed> {
 }
 EnableResize = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:132
 userdata = <table> {
 }
 base = <table> {
 }
 LayoutFunc = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\AceGUI-3.0.lua:656
 SetStatusTable = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:140
 Hide = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:124
 OnHeightSet = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:105
 type = "Frame"
 AceGUIWidgetVersion = 30
 OnAcquire = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:79
 children = <table> {
 }
 SetTitle = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:115
 ApplyStatus = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:146
 titletext = <unnamed> {
 }
 Show = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:128
 statustext = <unnamed> {
 }
 events = <table> {
 }
 frame = <unnamed> {
 }
 sizer_s = <unnamed> {
 }
 titlebg = <unnamed> {
 }
 content = <unnamed> {
 }
 localstatus = <table> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Last generated %s seconds ago"
(*temporary) = <function> defined =[C]:-1
(*temporary) = 1590776.448000
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'data' (a nil value)"
frame = <table> {
 OnRelease = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:90
 OnWidthSet = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:95
 SetStatusText = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:120
 sizer_se = <unnamed> {
 }
 sizer_e = <unnamed> {
 }
 EnableResize = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:132
 userdata = <table> {
 }
 base = <table> {
 }
 LayoutFunc = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\AceGUI-3.0.lua:656
 SetStatusTable = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:140
 Hide = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:124
 OnHeightSet = <function> defined @Interface\AddOns\Clicked\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:105
 type = "Fra

**Comment by rbpaiett** [comment]
Oh sorry, the data dump showed nothing in the clicked datadump but the above lua error appeared.

**Comment by Snakybo** [comment]
Oh, damn I missed that, will fix asap!

**Comment by rbpaiett** [comment]
Excellent!
