### ISSUE TITLE
Bindings don't load correctly anymore

### ISSUE THREAD

**Issue by Mon3yb** [Snakybo/Clicked#165]
### Describe the bug

With one of the last two updates it seems like the loading has been broken at least on my shaman. I didn't try other classes as I'm not sure what triggers it.

As an example I switched from enhancement to restoration and my mouseover purge wasn't loading. Spell was known and I could cast it from my spellbook. After changing the load conditions to never and back (unticking never) it worked.
Then on another occasion Earth Shield was loaded by clicked but I did not know the talent. The load requirement has "Talent Known" in it. Trying to change to never load and back fixed this as well

### Clicked Version

1.10.5

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [ ] Yes
- [X] No

### Lua Errors

none

### Reproduction Steps

1. Go to Talent Tree
2. Swap Talents or Spec
3. Open Clicked and see whats loaded
4. Some spells are loaded even if not known
5. Other spells are unloaded even if known and castable through the action bar

### Last Working Version

-

### Screenshots

![image](https://user-images.githubusercontent.com/2087287/211910944-08f331c9-26ce-4a46-9b96-acaf2ae82584.png)

**Comment by Snakybo** [comment]
Hm, I can't reproduce this. Does it still happen? Can you include the contents of `/cc dump`?

**Comment by Mon3yb** [comment]
I will try to reproduce it. Currently not swapping that much. But I think it happens when I'm importing a talent string.
You need the /cc dump when it happens or just in general?

**Comment by Snakybo** [comment]
When it happens would be great

**Comment by Grosstartine** [comment]
Hello, I have the same issue with this version and the previous one. Half of my bindings are not loaded correctly.
When I change the load condition of one of the binding with this issue the spell works but as soon as I change another load condition the previous one return in an incorrect states.
[grosspoutre_dump_clicked.txt](https://github.com/Snakybo/Clicked/files/10522754/grosspoutre_dump_clicked.txt)

**Comment by Mon3yb** [comment]
Just got the bug again, this time on Healing Wave as an Enhancement Shaman. I can't know this spell and still the keybind overwrites whatever else is configured
[cc_dump_clicked.txt](https://github.com/Snakybo/Clicked/files/10679371/cc_dump_clicked.txt)

**Comment by Mon3yb** [comment]
And it happened again. This time Purify Spirit and Purge overlap. Purify Spirit is a Restoration only ability. The load condition should reflect that as well.
I will try going back a two versions and report if it happens again.
[cc_dump_2.txt](https://github.com/Snakybo/Clicked/files/10760965/cc_dump_2.txt)
