### ISSUE TITLE
Generated macros override replaced action bars

### ISSUE THREAD

**Issue by LarkRanger** [Snakybo/Clicked#167]
### Describe the bug

I created a bind for a button on my primary bar.
The bind works fine.
But, when mounting a dragonriding mount, the entire bar is replaced, annd the Surge Forward ability I have on the same button no longer works. Instead, Clicked takes over and does whatever that bind should do, dismounting me in the process
Is there a way to have Clicked not take over these dragonriding skills, or respect the replaced bar?

### Clicked Version

1.10.16

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

1. Open Clicked.
2. Create a bind for a button on your 1st action bar.
3. Mount a dragonriding mount.
4. Place a dragonriding ability on the same button.
5. Try using the ability - it doesn't work, instead Clicked takes over.

### Debug Output

Version: 1.10.6
Data Version: 2
Project ID: 1
Race: ZandalariTroll
Level: 67
Class: MONK
Specialization: 270 (Mistweaver)
Talents: B4QAP1tpyZCKK6xz/PGFSDdghJhCSCUUiIpkDIJtgIlEEAAAAAAAAAAAASDtkkIJhcgARSJJAAAB
Press Mode: AnyUp
Autogen: False

Possess Bar: disabled
Override Bar: disabled
Vehicle: disabled
Vehicle UI: disabled
Pet Battle: disabled

----- Loaded binding 1 -----
Keybind: F9
Hovercast: true
Action: macro
Identifier: clicked-button-f9

/stopspelltarget
/cast [@mouseover,help,nodead] Renewing Mist

----- Loaded binding 2 -----
Keybind: F4
Hovercast: true
Action: macro
Identifier: clicked-button-f4

/stopspelltarget
/cast [@mouseover,help,nodead] Vivify

----- Loaded binding 3 -----
Keybind: F7
Hovercast: true
Action: macro
Identifier: clicked-button-f7

/stopspelltarget
/cast [@mouseover,help,nodead] Enveloping Mist

----- Loaded binding 4 -----
Keybind: F6
Hovercast: true
Action: macro
Identifier: clicked-button-f6

/stopspelltarget
/cast [@mouseover,help,nodead] Soothing Mist

----- Loaded binding 5 -----
Keybind: F4
Hovercast: false
Action: macro
Identifier: clicked-button-f4

/stopspelltarget
/cast [@target,harm,nodead] Tiger Palm

----- Loaded binding 6 -----
Keybind: F6
Hovercast: false
Action: macro
Identifier: clicked-button-f6

/stopspelltarget
/cast [@target,harm,nodead] Crackling Jade Lightning

----- Loaded binding 7 -----
Keybind: F7
Hovercast: false
Action: macro
Identifier: clicked-button-f7

/stopspelltarget
/cast [@target,harm,nodead] Rising Sun Kick

----- Loaded binding 8 -----
Keybind: F9
Hovercast: false
Action: macro
Identifier: clicked-button-f9

/stopspelltarget
/cast [@target,harm,nodead] Blackout Kick

----- Macro Handler Attributes -----
typerelease-clicked-button-f4: macro
typerelease-clicked-button-f6: macro
macrotext-clicked-button-f9: /stopspelltarget
macrotext-clicked-button-f9: /cast [@target,harm,nodead] Blackout Kick
macrotext-clicked-button-f6: /stopspelltarget
macrotext-clicked-button-f6: /cast [@target,harm,nodead] Crackling Jade Lightning
typerelease-clicked-button-f9: macro
macrotext-clicked-button-f7: /stopspelltarget
macrotext-clicked-button-f7: /cast [@target,harm,nodead] Rising Sun Kick
typerelease-clicked-button-f7: macro
macrotext-clicked-button-f4: /stopspelltarget
macrotext-clicked-button-f4: /cast [@target,harm,nodead] Tiger Palm

----- Hovercast Attributes -----
typerelease-clicked-button-f4: macro
macrotext-clicked-button-f4: /stopspelltarget
macrotext-clicked-button-f4: /cast [@mouseover,help,nodead] Vivify
typerelease-clicked-button-f6: macro
macrotext-clicked-button-f6: /stopspelltarget
macrotext-clicked-button-f6: /cast [@mouseover,help,nodead] Soothing Mist
typerelease-clicked-button-f9: macro
macrotext-clicked-button-f7: /stopspelltarget
macrotext-clicked-button-f7: /cast [@mouseover,help,nodead] Enveloping Mist
typerelease-clicked-button-f7: macro
macrotext-clicked-button-f9: /stopspelltarget
macrotext-clicked-button-f9: /cast [@mouseover,help,nodead] Renewing Mist

----- Registered unit frames -----
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
Boss5TargetFrame
CompactPartyFrameMember1
CompactPartyFrameMember1Buff1
CompactPartyFrameMember1Buff2
CompactPartyFrameMember1Buff3
CompactPartyFrameMember1CenterStatusIcon
CompactPartyFrameMember1Debuff1
CompactPartyFrameMember1Debuff2
CompactPartyFrameMember1Debuff3
CompactPartyFrameMember1DispelDebuff1
CompactPartyFrameMember1DispelDebuff2
CompactPartyFrameMember1DispelDebuff3
CompactPartyFrameMember2
CompactPartyFrameMember2Buff1
CompactPartyFrameMember2Buff2
CompactPartyFrameMember2Buff3
CompactPartyFrameMember2CenterStatusIcon
CompactPartyFrameMember2Debuff1
CompactPartyFrameMember2Debuff2
CompactPartyFrameMember2Debuff3
CompactPartyFrameMember2DispelDebuff1
CompactPartyFrameMember2DispelDebuff2
CompactPartyFrameMember2DispelDebuff3
CompactPartyFrameMember3
CompactPartyFrameMember3Buff1
CompactPartyFrameMember3Buff2
CompactPartyFrameMember3Buff3
CompactPartyFrameMember3CenterStatusIcon
CompactPartyFrameMember3Debuff1
CompactPartyFrameMember3Debuff2
CompactPartyFrameMember3Debuff3
CompactPartyFrameMember3DispelDebuff1
CompactPartyFrameMember3DispelDebuff2
CompactPartyFrameMember3DispelDebuff3
CompactPartyFrameMember4
CompactPartyFrameMember4Buff1
CompactPartyFrameMember4Buff2
CompactPartyFrameMember4Buff3
CompactPartyFrameMember4CenterStatusIcon
CompactPartyFrameMember4Debuff1
CompactPartyFrameMember4Debuff2
CompactPartyFrameMember4Debuff3
CompactPartyFrameMember4DispelDebuff1
CompactPartyFrameMember4DispelDebuff2
CompactPartyFrameMember4DispelDebuff3
CompactPartyFrameMember5
CompactPartyFrameMember5Buff1
CompactPartyFrameMember5Buff2
CompactPartyFrameMember5Buff3
CompactPartyFrameMember5CenterStatusIcon
CompactPartyFrameMember5Debuff1
CompactPartyFrameMember5Debuff2
CompactPartyFrameMember5Debuff3
CompactPartyFrameMember5DispelDebuff1
CompactPartyFrameMember5DispelDebuff2
CompactPartyFrameMember5DispelDebuff3
FocusFrame
FocusFrameToT
PetFrame
PlayerFrame
TargetFrame
TargetFrameToT

----- Registered sidecars -----
ClickedSidecar1 (for PartyMemberFrame1)
ClickedSidecar2 (for PartyMemberFrame1PetFrame)
ClickedSidecar3 (for PartyMemberFrame2)
ClickedSidecar4 (for PartyMemberFrame2PetFrame)
ClickedSidecar5 (for PartyMemberFrame3)
ClickedSidecar6 (for PartyMemberFrame3PetFrame)
ClickedSidecar7 (for PartyMemberFrame4)
ClickedSidecar8 (for PartyMemberFrame4PetFrame)

----- Profile -----
TVzBtTnoqC8VsjP5jEzacCzaC4IcmtVPJsvSfbnil5ZwgA6l6N9BLCGy7gSSPj0YnA4njYAxTsA1)FR8eWTXZXOhPXjmPa71bJKrk4Jj6MLIlORpv(KaVeJwYeb3iijjSvcAWvYa2DmWm9JusjxXImFoKjyHKiT53ZcOqtk4pJ1mXkTB9mdPADefJqxp(YlXiIVEm1nhs8JL3s4PWd38npsi8LzPIF8v)0eLm8hF10ogLer58So71UD)(dAb(LeVIQUrWuJUtrJpHKO0HfjnMK5imIPOHfhIj(WOJMiadUJ4t)YKtM6H(YeVBxCflXFXFNst0b4vK4hWiFIWNYH2sPbiDeO9p4ayruzC7C5Ka8Xye9Bu)uTDtJdOX65nIPhI40itmLaXQAuQsosPi(p8stxtvBBjB0otghAwkrpqxRxlXOZ6M5UvXKN3WGhdl5cLzNb79PEyexsc0RRrCYAASEfygLWdnB6zlbNaJij5EySPCQVIgKno3XxtwYPB74XL7btarleCZ17Kq3sG9xWaK3uVX56RhSPeMQZpmEtVky6HjTWNdju5n(QPExuTXMEymoBonrCESmnk3mAhtfW7vmtG8iFgHZ(o550WnHJ(8qfXc8ytGq)3uwuenOQyqVbMZXTl5ybDfjRZLhJ2zJrIc23u3x9SGZVqOpU(6XHIWHeetKSTDe0umJU9WPmIMLvHrJ8oTq09SFvzH13LcQ5C1RpKckCYqBAevvv4)elmS69POhJMVn(FLvYDV85FpriO8c(VyKMBsc9xMQcKY4KkZ)lN4nXBX5ZMEZ1lUE0S5FEX0zlMnAYPLTluMku5tw(jp)ejg0xR6SNVmCjPQvZyqgl)5Q)HiciCsmBESeuSQ8ewP(UzNoty1SGetxLcp)L0LhzqAvIox5Zyuki9IrNo(Sr3CPgcibPtotTo7XgxTX(XcTcJzT)EjKJ4R1QlAYFn(YRZ5)lNCRw4yB3F2fhBCmCE8qqwA1AWqhzPazPVJSGDKfhzXrwENilgL)nSL5JMD(4sCIrZUcVl2YXVoBXqRYJU2fyzPXREFcxxWsbv1ICKoD7pStZ5iVMY9HHt0CQv1O0cGLb7cSKB7FhCDBflukdPCTdklvRuoFOy1lBsqDOU)mqD7zPh7AD2Ll3s9EJKUs(RguVFzGVJwwtAP9kJEPcK6uIKQur0dGw86I3dKLwd62zOJS0eYYsRLkufNOkSYpdI0fNuS2fhyXbwCGfhy5WawgcT41dxxWstExyThCuV3WDyAU2)HKe1K3fwFRVlSJ(Z)gSVDqJvLSpmCM9Tg)7awQoN9ZPuyvu53WROZXuEVyk2lPWErJ2QfZ8UW6JRlyPIBS0Ux7b9AohzpEJLo25enNA1GBSStWI7DH9raLy7yY7bByFJZSc6TRV4UYY)JXl2RU4x5klDBbT4naxxYsJUYsp4VMJAAU4)BgfTNVYYr2UYs3217kl)w)5C82jnwLY(WaA23I8VdCP6C43DNfhuPM1uyVQrBfJzUZYq8HGSO)HH11rwYtw6upYI7LH5aloWIdS8rhSys5(MYmnafyD2U(7hN9F7IULUaGyL(XBulxYbvwoZiFPTh)F)

**Comment by Snakybo** [comment]
Unfortunately at the moment there is not. The Dragonriding mounts work weirdly and don't use the existing `overridebar` macro conditional, and thus Clicked has no way to determine you're on a Dragonriding mount.

Clicked is set up to disable itself when the various bar overrides are active: pet battle bar, vehicle UI, possess bar, override bar. Dragonriding works differently and effectively just makes you "learn" these abilities every time you mount and it will push them onto your action bar.

**Comment by LarkRanger** [comment]
Thank you very much for explaining.

**Comment by Snakybo** [comment]
No problem :)

There is something you can do if you're willing to put the Dragonriding abilities into Clicked though.

In 10.0.7 there will be a new `advflyable` macro conditional. You could use that in combination with the `mounted` conditional to make a reasonable assumption that you're on a Dragonriding mount. This isn't exactly fool-proof as it will also be valid when you mount any other mount inside of the Dragon Isles, but I think it should be a reasonably safe combination.

Until 10.0.7 releases just using the `mounted` macro conditional will allow you to set up to use the Dragonriding abilities if mounted, and the base abilities if not. This is not a great solution as it will also try to cast the Dragonriding abilities when you're on any other mount in any other zone, but it could work for you.
