### ISSUE TITLE
Dragon Riding

### ISSUE THREAD

**Issue by tharax** [Snakybo/Clicked#168]
### Describe the bug

I want to be able to press "2" while mounted on a Dragon and it to cast "Skyward Ascent".

I can program it to do it while flying, but not when the mount is on the ground (which is possible in game)

### Clicked Version

latest

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

1. Data to Import: BgGAPjJFohhWlFcNj9E1Av/dNBAAAAAAAAAAAAAJJkIlIlkkkkABJFAgkggEIJJRSiUgWiDAAAAAAICIaCA
2. Mount a dragon in Valdrakken
3. Press "2"

**Comment by Snakybo** [comment]
Unfortunately there is no macro conditional to determine whether you're on a Dragonriding mount, and thus no way for Clicked to tell the game that it should cast Skyward Ascent if you're grounded on a Dragonriding mount.

I was thinking of adding support for the `advflyable` macro conditional, which you _could_ then use in combination with the `mounted` conditional to make a reasonable assumption that you're on a dragonriding mount. Of course this is not fool-proof as it will also be valid when you mount any other mount inside of the Dragon Isles, but I think it should be a reasonably safe combination.
