### ISSUE TITLE
2 errors:  ClickCastHeader & AddonCompartmentFrame both nil with latest version.

### ISSUE THREAD

**Issue by rbpaiett** [Snakybo/Clicked#169]
### Describe the bug

I expected the game to load this addon without errors.

These are the errors that appeared when only this addon is loaded:

1.  4x Clicked/UnitFrames/ClickCastHeader.lua:187: attempt to index field 'ClickCastHeader' (a nil value)
[string "@Clicked/UnitFrames/ClickCastHeader.lua"]:187: in function `UpdateClickCastHeaderBlacklist'
[string "@Clicked/Core/Clicked.lua"]:134: in function <Clicked/Core/Clicked.lua:130>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

and ...

2.  4x Clicked/Core/Clicked.lua:63: attempt to index global 'AddonCompartmentFrame' (a nil value)
[string "@Clicked/Core/Clicked.lua"]:63: in function <Clicked/Core/Clicked.lua:62>
[string "@Clicked/Core/Clicked.lua"]:228: in function <Clicked/Core/Clicked.lua:216>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

### Clicked Version

Clicked 1.11.1

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Lua Errors

1.  4x Clicked/UnitFrames/ClickCastHeader.lua:187: attempt to index field 'ClickCastHeader' (a nil value)
[string "@Clicked/UnitFrames/ClickCastHeader.lua"]:187: in function `UpdateClickCastHeaderBlacklist'
[string "@Clicked/Core/Clicked.lua"]:134: in function <Clicked/Core/Clicked.lua:130>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

and ...

2.  4x Clicked/Core/Clicked.lua:63: attempt to index global 'AddonCompartmentFrame' (a nil value)
[string "@Clicked/Core/Clicked.lua"]:63: in function <Clicked/Core/Clicked.lua:62>
[string "@Clicked/Core/Clicked.lua"]:228: in function <Clicked/Core/Clicked.lua:216>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

### Reproduction Steps

1.  Start the game with only Clicked loaded.
That's it.

### Last Working Version

Clicked 1.11.0

### Screenshots

No screenshots needed.

### Debug Output

/clicked dump doesn't work, just shows the Blizz default help comment when a line command doesn't exist.

**Comment by Snakybo** [comment]
Whoops, sorry about that. Should have a fix out soon.

**Comment by rbpaiett** [comment]
Thanks!
