### ISSUE TITLE
Disabling shapeshifting during combat

### ISSUE THREAD

**Issue by Vuhdo** [Snakybo/Clicked#171]
Hey,

(For some unknown reason Curseforge is rejecting my comments, hopefully you don't mind me posting them here.)

For guardian/feral druids we use this macro to ensure that casting Regrowth won't cause you to leave bear/cat form during combat:
```
/run if InCombatLockdown() then SetCVar("autounshift",0) end
/cast Regrowth 
/console autounshift 1
```

Is there a way to do this kind of binding in Clicked?

(P.S. Love your addon, sir, been a proud user since its inception in Shadowlands).

**Comment by Snakybo** [comment]
Hi!

So built-in.. no, not at the moment, however, you can accomplish this by combining three bindings:
![image](https://github.com/Snakybo/Clicked/assets/3172140/92039782-cf59-449e-b6c5-a9920e2a16ac)

The end result will end up looking like this:
![image](https://github.com/Snakybo/Clicked/assets/3172140/5bae24a6-f967-4428-8617-ed4cdf036aa6)

Here's a group you can import to try it out :)
(Click the "Import" button on the `/cc` window)
```
TJ53VTTnqC8)x6tDalOvZaRTpQy7uimhzprLaKHcAtlD2MiuKAKujZ9b)3(ok5Fizhl32emKv43sipE3374X7JsOE0ykzUwvK7(bEkiT8zCqtjExuU8f)oLizzaLCjW0RMeb4YpAxqjMevoqd9OKuUjxWwgKOKusG0c6zSe4lbDhgs(sq4TJVMBsg)NfGXYvYRz67PKPCzkxo3GHn07WyVE7l868bkHL4oNZOmwIwDltuG6z9VfwkUOc5QjjfgRkB1KY1rbMdcrLXHF8tDWeXY0Zb7nsU1FgQYUmJLof9FHMv5gugwiRza(UsReMmbe4AfqkXfFN)rh8aOTLUnwfKsVKsG)bskCNBOoft5WFddTle6I8snzqTA9lSkFRLLC)2Lgb2DRufTRu6m83SuY9WsxHJs6tj5mnwqBCpwL(UsordZlem92Q)dCltyOe)W7OKcSarjJg4Fx)ikzHcZpb3USAxRlqRpEFjBQakZNfkmftCf04dosdVBRz7MZxkE7sSDIqg1FWGQAXCnZvGC6f3wOyPoF760aT76kcyISsXxDFfRvZNI5eXaciXUXVZelDrzNHxUVfCjwAXkzStbOzgSZdpajCyy)A2g(ESJOqy55LEZ15xArzfjrWmM6hUx0nb9A)0vMuECw6dofKE1jfBv(hi)8MhTpSPB9G0gvslocFEKWzc(xzBEDTw6HDAv242LsEQswyMw2d9KAGiH5STrd(7cEEoK2MID9X1KH3EYyN)2xrEvkYyXocC0uR5Sq8hs1JYw0b2R6E5e3mBWL0Cy38kC4xv)PRTUxd1TXV2kz9vLekhVC8qkb8fH7O5GTn5)iplR9B18hYJFH1FYcMucIgXTTRAvHnvP0MwFXTF7Bq44phn8MrJh5hfF34HrJJ8B8(P8CzQcPTEt0bE(rM(AvABpGsuztzTvL14u(6VK)lMmLHt744agCGERpP3Z21vWTOsRBqF8XHDF8yWU3PDao(SvtcKDltGbQK7tXg53(lRMyxa4UeW29wM(TVHHyJcPzbFM9n)6QjVhTaCuHA8YECJBoZQj1SLwNysEvtl9E1rl71)k)Bge)FnU8A)UrdpJlBzE4zC5zCzlThNXLVUXLDCUUXSUJairSHrThrB1eV9g7)mrChdQ8dGW6CAe23pqTgHVcw0eWVh07qQrnM3tqDofhRbw8ao4ZLIwVX4OFa1Not(GF6jFVWtCo9iUtpLChe8heCSN)(gGGpB()ll88LjV)Ff880Fa12pu5B5lPSp1FgY6jFveWQ)rTe0NgxHn0Tn9F)
```

This looks like an interesting feature, will look into adding this built-in
