### ISSUE TITLE
Spells on Same Keybind /w different Conditionals

### ISSUE THREAD

**Issue by 26209** [Snakybo/Clicked#174]
## Is your feature request related to a problem?
When I have a spell bound to a key setup to mouseover and friendly other spells on that same bind do not work regardless if I am mousing over a friendly or any target.

## Describe the solution you'd like
A way for other keybinds to work with the same key because not all the conditions are met (no friendly mouseover, no mouseover).

## Describe alternatives you've considered
Was looking into if an exists conditional could be added or an easier way to bind multiple spells on the same key with less conflicts.

## Additional context
Most of the problems seem to occur with spells that don't require targets.

**Comment by Snakybo** [comment]
You can assign different bindings to the same key and they will all work together, I think how it currently works is the "easiest" to achieve from an user experience point of view, too.

Will close this for now unless you could visualize what exactly your idea is a bit :)
