### ISSUE TITLE
Issue #164 is still an issue 7 months later.

### ISSUE THREAD

**Issue by gotex007** [Snakybo/Clicked#176]
### Describe the bug

Decided to enable clicked again on my monk to see if it works yet and it doesn't. Still the same problem as https://github.com/Snakybo/Clicked/issues/164 and I'm sure it still has the same problem on the warrior still as I remember trying that again a few weeks ago.

### Clicked Version

1.13.2

### World of Warcraft Flavor

Dragonflight

### Lua Errors

First Error:
```2x Clicked/Core/Upgrader.lua:782: attempt to get length of field 'entries' (a nil value)
[string "@Clicked/Core/Upgrader.lua"]:782: in function <Clicked/Core/Upgrader.lua:722>
[string "=[C]"]: in function `xpcall'
[string "@Clicked/Core/Upgrader.lua"]:16: in function <Clicked/Core/Upgrader.lua:14>
[string "@Clicked/Core/Upgrader.lua"]:875: in function `UpgradeDatabase'
[string "@Clicked/Core/Clicked.lua"]:201: in function <Clicked/Core/Clicked.lua:193>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
db = <table> {
 version = 2
 options = <table> {
 }
 nextGroupId = 1
 groups = <table> {
 }
 nextBindingId = 55
 bindings = <table> {
 }
 blacklist = <table> {
 }
}
from = 2
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
}
(for control) = 1
_ = 1
binding = <table> {
 scope = 1
 type = "SPELL"
 action = <table> {
 }
 keybind = "SHIFT-BUTTON1"
 integrations = <table> {
 }
 identifier = "1-binding-1"
 load = <table> {
 }
 targets = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 GetLocalizedTalents = <function> defined @Clicked/Core/LocaleUtils.lua:510
 IsRetail = <function> defined @Clicked/Core/Init.lua:59
 AbilityTooltips_Initialize = <function> defined @Clicked/Core/Tooltips.lua:181
 StatusOutput_Open = <function> defined @Clicked/Debug/StatusOutput.lua:283
 CreateWeakAurasIcon = <function> defined @Clicked/Integrations/WeakAuras.lua:449
 UpdateClickCastHeader = <function> defined @Clicked/UnitFrames/ClickCastHeader.lua:191
 GetLocalizedTargetVitals = <function> defined @Clicked/Core/LocaleUtils.lua:342
 IsWotLK = <function> defined @Clicked/Core/Init.lua:80
 CreateCommandAttributes = <function> defined @Clicked/Core/AttributeHandler.lua:134
 InteractionType = <table> {
 }
 AddonOptions = <table> {
 }
 CommandType = <table> {
 }
 IterateShapeshiftSpecs = <function> defined @Clicked/Core/Utils.lua:782
 StatusOutput_UpdateHovercastAttributes = <function> defined @Clicked/Debug/StatusOutput.lua:328
 IsFrameBlacklisted = <function> defined @Clicked/UnitFrames/ClickCastFrames.lua:105
 IsStringNilOrEmpty = <function> defined @Clicked/Core/Utils.lua:684
 StringUtils = <table> {
 }
 GetLocalizedClasses = <function> defined @Clicked/Core/LocaleUtils.lua:365
 GetBindingRaces = <function> defined @Clicked/Core/Utils.lua:888
 GroupState = <table> {
 }
 BindingTypes = <table> {
 }
 IsMacroCastEnabled = <function> defined @Clicked/Core/Utils.lua:1074
 GetContainingDatabase = <function> defined @Clicked/Core/Database.lua:543
 GetCachedBindingState = <function> defined @Clicked/Core/BindingProcessor.lua:1681
 GUI_MultiselectDropdown = <function> defined @Clicked/Config/GUI.lua:316
 GetLocalizedPvPTalents = <function> defined @Clicked/Core/LocaleUtils.lua:546
 GetWoWUnitFromUnit = <function> defined @Clicked/Core/Utils.lua:304
 Media = <table> {
 }
 IsSetBonusActive = <function> defined @Clicked/Core/Utils.lua:947
 GetLocalizedForms = <function> defined @Clicked/Core/LocaleUtils.lua:582
 GetAvailableShapeshiftForms = <function> defined @Clicked/Core/Utils.lua:826
 ExportFrame = <table> {
 }
 NotifyCombatLockdown = <function> defined @Clicked/Core/Utils.lua:1160
 UpdateMacroFrameHandler =

**Comment by gotex007** [comment]
Second error:

```5x Clicked/Core/BindingProcessor.lua:1031: attempt to get length of local 'entries' (a nil value)
[string "@Clicked/Core/BindingProcessor.lua"]:1031: in function `IsTalentMatrixValid'
[string "@Clicked/Core/BindingProcessor.lua"]:1072: in function `UpdateBindingLoadState'
[string "@Clicked/Core/BindingProcessor.lua"]:599: in function <Clicked/Core/BindingProcessor.lua:572>
[string "@Clicked/Core/BindingProcessor.lua"]:632: in function `ReloadBindings'
[string "@Clicked/Core/BindingProcessor.lua"]:876: in function `UpdateTalentCacheAndReloadBindings'
[string "@Clicked/Core/BindingProcessor.lua"]:818: in function <Clicked/Core/BindingProcessor.lua:816>

Locals:
entries = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of local 'entries' (a nil value)"
talentCache = <table> {
 Honed Reflexes = true
 Improved Execute = true
 Dual Wield Specialization = true
 Rampage = true
 Titan's Torment = true
 Wrath and Fury = true
 Impending Victory = true
 Massacre = true
 War Machine = true
 Ravager = true
 Frothing Berserker = true
 Furious Blows = true
 Bounding Stride = true
 Unbridled Ferocity = true
 Warpaint = true
 Rallying Cry = true
 Double Time = true
 Barbaric Training = true
 Avatar = true
 Slaughtering Strikes = true
 Fresh Meat = true
 Armored to the Teeth = true
 Sudden Death = true
 Cruelty = true
 Improved Whirlwind = true
 Ashen Juggernaut = true
 Wild Strikes = true
 Onslaught = true
 Tenderize = true
 Hurricane = true
 Sidearm = true
 Swift Strikes = true
 Defensive Stance = true
 Recklessness = true
 Bloodthirst = true
 Reckless Abandon = true
 Critical Thinking = true
 Meat Cleaver = true
 Berserker Stance = true
 Overwhelming Rage = true
 Reinforced Plates = true
 Seismic Reverberation = true
 Frenzy = true
 Focus in Chaos = true
 Storm Bolt = true
 Raging Blow = true
 Improved Enrage = true
 Leeching Strikes = true
 Thunderous Words = true
 Spell Reflection = true
 Thunderous Roar = true
 Improved Raging Blow = true
 Enraged Regeneration = true
 Heroic Leap = true
 Pain and Gain = true
 Fast Footwork = true
 Cruel Strikes = true
}
```

**Comment by gotex007** [comment]
Third error:
```10x Clicked/Config/Bindings.lua:186: attempt to concatenate field '?' (a nil value)
[string "@Clicked/Config/Bindings.lua"]:186: in function <Clicked/Config/Bindings.lua:164>
[string "@Clicked/Config/Bindings.lua"]:1071: in function <Clicked/Config/Bindings.lua:1042>
[string "@Clicked/Config/Bindings.lua"]:2437: in function <Clicked/Config/Bindings.lua:2436>
[string "@Clicked/Config/Bindings.lua"]:2613: in function <Clicked/Config/Bindings.lua:2598>
[string "@Clicked/Config/Bindings.lua"]:3147: in function <Clicked/Config/Bindings.lua:3128>
[string "=[C]"]: ?
[string "@Altoholic/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...faceAltoholic/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Altoholic/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Altoholic/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Altoholic/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:200: in function <...Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua:197>

Locals:
type = "LoadOption"
selected = 0
options = <table> {
 true = "On"
 false = "Off"
}
order = <table> {
 1 = "false"
 2 = "true"
}
selectedStr = "0"
(*temporary) = "|cff00ff00"
(*temporary) = nil
(*temporary) = "|r"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate field '?' (a nil value)"
Addon = <table> {
 GetLocalizedTalents = <function> defined @Clicked/Core/LocaleUtils.lua:510
 IsRetail = <function> defined @Clicked/Core/Init.lua:59
 AbilityTooltips_Initialize = <function> defined @Clicked/Core/Tooltips.lua:181
 StatusOutput_Open = <function> defined @Clicked/Debug/StatusOutput.lua:283
 CreateWeakAurasIcon = <function> defined @Clicked/Integrations/WeakAuras.lua:449
 UpdateClickCastHeader = <function> defined @Clicked/UnitFrames/ClickCastHeader.lua:191
 GetLocalizedTargetVitals = <function> defined @Clicked/Core/LocaleUtils.lua:342
 IsWotLK = <function> defined @Clicked/Core/Init.lua:80
 CreateCommandAttributes = <function> defined @Clicked/Core/AttributeHandler.lua:134
 InteractionType = <table> {
 }
 AddonOptions = <table> {
 }
 CommandType = <table> {
 }
 IterateShapeshiftSpecs = <function> defined @Clicked/Core/Utils.lua:782
 StatusOutput_UpdateHovercastAttributes = <function> defined @Clicked/Debug/StatusOutput.lua:328
 IsFrameBlacklisted = <function> defined @Clicked/UnitFrames/ClickCastFrames.lua:105
 IsStringNilOrEmpty = <function> defined @Clicked/Core/Utils.lua:684
 StringUtils = <table> {
 }
 GetLocalizedClasses = <function> defined @Clicked/Core/LocaleUtils.lua:365
 GetBindingRaces = <function> defined @Clicked/Core/Utils.lua:888
 GroupState = <table> {
 }
 BindingTypes = <table> {
 }
 IsMacroCastEnabled = <function> defined @Clicked/Core/Utils.lua:1074
 GetContainingDatabase = <function> defined @Clicked/Core/Database.lua:543
 GetCachedBindingState = <function> defined @Clicked/Core/BindingProcessor.lua:1681
 GUI_MultiselectDropdown = <function> defined @Clicked/Config/GUI.lua:316
 GetLocalizedPvPTalents = <function> defined @Clicked/Core/LocaleUtils.lua:546
 GetWoWUnitFromUnit = <function> defined @Clicked/Core/Utils.lua:304
 Media = <table> {
 }
 IsSetBonusActive = <function> defined @Clicked/Core/Utils.lua:947
 GetLocalizedForms = <function> defined @Clicked/Core/LocaleUtils.lua:582
 GetAvailableShapeshiftForms = <function> defined @Clicked/Core/Utils.lua:826
 ExportFrame = <table> {
 }
 NotifyCombatLockdown = <function> defined @Clicked/Core/Utils.lua:1160
 UpdateMacroFrameHandler = <function> defined @Clicked/Core/CommandProcessor.lua:139
 GetDataFromString = <function> defined @Clicked/Core/Utils.lua:289
 IsHovercastEnabled = <function> defined @Clicked/Core/Utils.lua:1062
 GetColorizedString = <function> defined @Clicked/Core/Utils.lua:1171
 BindingConfig_Initialize = <function> defined @Clicked/Config/Bindings.lua:3335
 SetPendingFrameAttributes = <function> defined @Clicked/Core/AttributeHandler.lua:79
 DeepCopyTable = <function> defined @Clicked/Core/Utils.lua:268
 GetNewBindingTargetTemplate = <function> defined @Clicked/Core/Database.lua:385
 GetInternalBindingType = <function> defined @Clicked/Core/BindingProcessor.lua:1428
 ShowAddonIncompatibilityPopup = <function> defined @Clicked/Core/Utils.lua:245
 CompareBindings = <function> defined @Clicked/Core/Utils.lua:710
 IsBC = <function> defined @Clicked/Core/Init.lua:73
 ProcessActiveBindingsIfPending = <function> defined @In```

**Comment by gotex007** [comment]
### Reproduction Steps

Same issues as https://github.com/Snakybo/Clicked/issues/164 so it's the same steps.

### Screenshots

https://i.imgur.com/9PimKcM.png

**Comment by Snakybo** [comment]
Could you go into the `WTF/Account/<ID>/SavedVariables/` folder, and send me the `Clicked.lua` file?

After that, I can only recommend deleting that file and starting from scratch, there's very likely something very wrong with your profile.

**Comment by gotex007** [comment]
[Clicked.txt](https://github.com/Snakybo/Clicked/files/12694365/Clicked.txt)

I had to upload it as a txt since github doesn't support me uploading lua. I just wonder what went wrong, why the last time you helped me didn't fix everything, and what stops this from happening again provided I do completely restart from scratch (which would be a lot of work. I have a lot of macros across all of the characters the addon chooses to work properly on). I just don't understand what would cause it to randomly break for only a select couple of classes. Fortunately for now it's just warrior and monk that is broken but I actually have so many macros in the addon due to Blizzard's severely limited number of macro slots.

**Comment by Snakybo** [comment]
Ah, I was under the impression it was broken everywhere. Let me see what I can do, and if all else fails you can just reset the profile for those characters, which should hopefully also resolve the issue.

**Comment by gotex007** [comment]
I don't know how to reset the profile for only those characters. I don't see an option for that in the addon but I would also assume that'd resolve the issue if I could just reset the warrior and monk without destroying the macros for all of my other characters.

**Comment by gotex007** [comment]
Still having the same issues. Similar or same errors. It's too many lines for me to read.



First Error:

11x Clicked/Core/BindingProcessor.lua:1036: attempt to get length of local 'entries' (a nil value)
[string "@Clicked/Core/BindingProcessor.lua"]:1036: in function `IsTalentMatrixValid'
[string "@Clicked/Core/BindingProcessor.lua"]:1077: in function `UpdateBindingLoadState'
[string "@Clicked/Core/BindingProcessor.lua"]:599: in function <Clicked/Core/BindingProcessor.lua:572>
[string "@Clicked/Core/BindingProcessor.lua"]:637: in function `ReloadBindings'
[string "@Clicked/Core/BindingProcessor.lua"]:881: in function `UpdateTalentCacheAndReloadBindings'
[string "@Clicked/Core/BindingProcessor.lua"]:823: in function <Clicked/Core/BindingProcessor.lua:821>

Locals:
entries = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of local 'entries' (a nil value)"
talentCache = <table> {
 Life Cocoon = true
 Revival = true
 Mists of Life = true
 Profound Rebuttal = true
 Invigorating Mists = true
 Renewing Mist = true
 Secret Infusion = true
 Zen Pulse = true
 Soothing Mist = true
 Faeline Stomp = true
 Chrysalis = true
 Energizing Brew = true
 Invoke Chi-Ji, the Red Crane = true
 Celerity = true
 Dancing Mists = true
 Dampen Harm = true
 Save Them All = true
 Rising Mist = true
 Mana Tea = true
 Bounce Back = true
 Essence Font = true
 Improved Detox = true
 Thunder Focus Tea = true
 Rapid Diffusion = true
 Legacy of Wisdom = true
 Diffuse Magic = true
 Fatal Touch = true
 Ancient Concordance = true
 Chi Burst = true
 Vivacious Vivification = true
 Ferocity of Xuen = true
 Fast Feet = true
 Transcendence = true
 Spear Hand Strike = true
 Healing Elixir = true
 Ring of Peace = true
 Close to Heart = true
 Resonant Fists = true
 Awakened Faeline = true
 Calming Presence = true
 Veil of Pride = true
 Improved Vivify = true
 Sheilun's Gift = true
 Rising Sun Kick = true
 Tiger's Lust = true
 Teachings of the Monastery = true
 Generous Pour = true
 Celestial Harmony = true
 Enveloping Mist = true
 Paralysis = true
 Improved Touch of Death = true
 Ancient Teachings = true
 Gift of the Celestials = true
}



Second Error:

4x Clicked/Config/Bindings.lua:186: attempt to concatenate field '?' (a nil value)
[string "@Clicked/Config/Bindings.lua"]:186: in function <Clicked/Config/Bindings.lua:164>
[string "@Clicked/Config/Bindings.lua"]:1071: in function <Clicked/Config/Bindings.lua:1042>
[string "@Clicked/Config/Bindings.lua"]:2437: in function <Clicked/Config/Bindings.lua:2436>
[string "@Clicked/Config/Bindings.lua"]:2613: in function <Clicked/Config/Bindings.lua:2598>
[string "@Clicked/Config/Bindings.lua"]:3145: in function <Clicked/Config/Bindings.lua:3126>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <.../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:200: in function <...Ace3/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua:197>

Locals:
type = "LoadOption"
selected = 0
options = <table> {
 true = "On"
 false = "Off"
}
order = <table> {
 1 = "false"
 2 = "true"
}
selectedStr = "0"
(*temporary) = "|cff00ff00"
(*temporary) = nil
(*temporary) = "|r"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate field '?' (a nil value)"
Addon = <table> {
 GetLocalizedTalents = <function> defined @Clicked/Core/LocaleUtils.lua:510
 IsRetail = <function> defined @Clicked/Core/Init.lua:59
 AbilityTooltips_Initialize = <function> defined @Clicked/Core/Tooltips.lua:181
 StatusOutput_Open = <function> defined @Clicked/Debug/StatusOutput.lua:283
 CreateWeakAurasIcon = <function> defined @Clicked/Integrations/WeakAuras.lua:449
 UpdateClickCastHeader = <function> defined @Clicked/UnitFrames/ClickCastHeader.lua:191
 GetLocalizedTargetVitals = <function> defined @Clicked/Core/LocaleUtils.lua:342
 IsWotLK = <function> defined @Clicked/Core/Init.lua:80
 CreateCommandAttributes = <function> defined @Clicked/Core/AttributeHandler.lua:134
 InteractionType = <table> {
 }
 AddonOptions = <table> {
 }
 CommandType = <table> {
 }
 IterateShapeshiftSpecs = <function> defined @Clicked/Core/Utils.lua:800
 StatusOutput_UpdateHovercastAttributes = <function> defined @Clicked/Debug/StatusOutput.lua:328
 IsFrameBlacklisted = <function> defined @Clicked/UnitFrames/ClickCastFrames.lua:105
 IsStringNilOrEmpty = <function> defined @Clicked/Core/Utils.lua:702
 StringUtils = <table> {
 }
 GetLocalizedClasses = <function> defined @Clicked/Core/LocaleUtils.lua:365
 GetBindingRaces = <function> defined @Clicked/Core/Utils.lua:906
 GroupState = <table> {
 }
 BindingTypes = <table> {
 }
 BindingConfig_Close = <function> defined @Clicked/Config/Bindings.lua:3458
 IsMacroCastEnabled = <function> defined @Clicked/Core/Utils.lua:1090
 GetContainingDatabase = <function> defined @Clicked/Core/Database.lua:549
 GetCachedBindingState = <function> defined @Clicked/Core/BindingProcessor.lua:1686
 GUI_MultiselectDropdown = <function> defined @Clicked/Config/GUI.lua:316
 GetLocalizedPvPTalents = <function> defined @Clicked/Core/LocaleUtils.lua:546
 GetWoWUnitFromUnit = <function> defined @Clicked/Core/Utils.lua:322
 Media = <table> {
 }
 IsSetBonusActive = <function> defined @Clicked/Core/Utils.lua:965
 GetLocalizedForms = <function> defined @Clicked/Core/LocaleUtils.lua:582
 GetAvailableShapeshiftForms = <function> defined @Clicked/Core/Utils.lua:844
 ExportFrame = <table> {
 }
 NotifyCombatLockdown = <function> defined @Clicked/Core/Utils.lua:1176
 UpdateMacroFrameHandler = <function> defined @Clicked/Core/CommandProcessor.lua:139
 KeyLayouts = <table> {
 }
 GetDataFromString = <function> defined @Clicked/Core/Utils.lua:307
 IsHovercastEnabled = <function> defined @Clicked/Core/Utils.lua:1078
 BindingConfig_IsOpen = <function> defined @Clicked/Config/Bindings.lua:3380
 GetColorizedString = <function> defined @Clicked/Core/Utils.lua:1187
 BindingConfig_Initialize = <function> defined @Clicked/Config/Bindings.lua:3359
 SetPendingFrameAttributes = <function> defined @Clicked/Core/AttributeHandler.lua:79
 DeepCopyTable = <function> defined @Clicked/Core/Utils.lua:286
 GetNewBindingTargetTemplate = <function> defined @Clicked/Core/Database.lua:391
 GetInternalBindingType = <function> defined @Clicked/Core/BindingProcessor.lua:1433
 ShowAddonIncompatibilityPopup = <function> defined @Clicked/Core/Utils.lua

**Comment by jermoo** [comment]
what happens if you disable all addons except Clicked, remove and re-add the spell you're trying to bind? Are you creating a custom macro or just adding a known spell? if you're creating a custom macro post that here.

**Comment by gotex007** [comment]
Steps with me enabling on my monk again to see if it's working yet:
1. open with /clicked
2. [see a bunch of fake/ghost macros and 2 that don't actually work](https://i.imgur.com/lma2uj7.png)
3. click new
4. click "Cast a spell"
5. get error:

```
4x Clicked/Core/BindingProcessor.lua:1043: attempt to get length of local 'entries' (a nil value)
[string "@Clicked/Core/BindingProcessor.lua"]:1043: in function `IsTalentMatrixValid'
[string "@Clicked/Core/BindingProcessor.lua"]:1099: in function `UpdateBindingLoadState'
[string "@Clicked/Core/BindingProcessor.lua"]:604: in function <Clicked/Core/BindingProcessor.lua:577>
[string "@Clicked/Core/BindingProcessor.lua"]:639: in function `ReloadBindings'
[string "@Clicked/Core/BindingProcessor.lua"]:895: in function `UpdateTalentCacheAndReloadBindings'
[string "@Clicked/Core/BindingProcessor.lua"]:825: in function <Clicked/Core/BindingProcessor.lua:823>

Locals:
entries = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of local 'entries' (a nil value)"
cache = <table> {
 Peaceweaver = true
 Grapple Weapon = true
}
```



When I look at those two macros that don't work, they're [missing the final tab ](https://i.imgur.com/tQX4Cpx.png)that should show the macro (e.g. /use [@mouseover] Resuscitate) and when I click on the "Load conditions" tab it opens the tab but [is broken, missing options like spell known](https://i.imgur.com/7kYlhpu.png), and it throws an error:

```
7x Clicked/Config/Bindings.lua:230: attempt to concatenate field '?' (a nil value)
[string "@Clicked/Config/Bindings.lua"]:230: in function <Clicked/Config/Bindings.lua:208>
[string "@Clicked/Config/Bindings.lua"]:1115: in function <Clicked/Config/Bindings.lua:1086>
[string "@Clicked/Config/Bindings.lua"]:2508: in function <Clicked/Config/Bindings.lua:2507>
[string "@Clicked/Config/Bindings.lua"]:2680: in function <Clicked/Config/Bindings.lua:2666>
[string "@Clicked/Config/Bindings.lua"]:3227: in function <Clicked/Config/Bindings.lua:3208>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <.../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:200: in function <...Ace3/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua:197>

Locals:
type = "LoadOption"
selected = 0
options = <table> {
 true = "On"
 false = "Off"
}
order = <table> {
 1 = "false"
 2 = "true"
}
selectedStr = "0"
(*temporary) = "|cff00ff00"
(*temporary) = nil
(*temporary) = "|r"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate field '?' (a nil value)"
Addon = <table> {
 GetLocalizedTalents = <function> defined @Clicked/Core/LocaleUtils.lua:485
 IsRetail = <function> defined @Clicked/Core/Init.lua:77
 AbilityTooltips_Initialize = <function> defined @Clicked/Core/Tooltips.lua:181
 StatusOutput_Open = <function> defined @Clicked/Debug/StatusOutput.lua:281
 CreateWeakAurasIcon = <function> defined @Clicked/Integrations/WeakAuras.lua:451
 UpdateClickCastHeader = <function> defined @Clicked/UnitFrames/ClickCastHeader.lua:193
 GetLocalizedTargetVitals = <function> defined @Clicked/Core/LocaleUtils.lua:318
 IsWotLK = <function> defined @Clicked/Core/Init.lua:101
 CreateCommandAttributes = <function> defined @Clicked/Core/AttributeHandler.lua:134
 InteractionType = <table> {
 }
 AddonOptions = <table> {
 }
 CommandType = <table> {
 }
 IterateShapeshiftSpecs = <function> defined @Clicked/Core/Utils.lua:808
 StatusOutput_UpdateHovercastAttributes = <function> defined @Clicked/Debug/StatusOutput.lua:326
 IsFrameBlacklisted = <function> defined @Clicked/UnitFrames/ClickCastFrames.lua:107
 IsStringNilOrEmpty = <function> defined @Clicked/Core/Utils.lua:710
 StringUtils = <table> {
 }
 GetLocalizedClasses = <function> defined @Clicked/Core/LocaleUtils.lua:341
 GetBindingRaces = <function> defined @Clicked/Core/Utils.lua:914
 GroupState = <table> {
 }
 EXPANSION_LEVEL = 10
 BindingTypes = <table> {
 }
 BindingConfig_Close = <function> defined @Clicked/Config/Bindings.lua:3538
 IsMacroCastEnabled = <function> defined @Clicked/Core/Utils.lua:1098
 SafeCall = <function> defined @Clicked/Core/Init.lua:65
 GetCachedBindingState = <function> defined @Clicked/Core/BindingProcessor.lua:1693
 GUI_MultiselectDropdown = <function> defined @Clicked/Config/GUI.lua:316
 GetLocalizedPvPTalents = <function> defined @Clicked/Core/LocaleUtils.lua:521
 GetKeybindModifiersAndKey = <function> defined @Clicked/Core/Utils.lua:641
 Media = <table> {
 }
 IsSetBonusActive = <function> defined @Clicked/Core/Utils.lua:973
 GetLocalizedForms = <function> defined @Clicked/Core/LocaleUtils.lua:557
 GetAvailableShapeshiftForms = <function> defined @Clicked/Core/Utils.lua:852
 ExportFrame = <table> {
 }
 NotifyCombatLockdown = <function> defined @Clicked/Core/Utils.lua:1184
 UpdateMacroFrameHandler = <function> defined @Clicked/Core/CommandProcessor.lua:142
 KeyLayouts = <table> {
 }
 GetDataFromString = <function> defined @Clicked/Core/Utils.lua:325
 IsHovercastEnabled = <function> defined @Clicked/Core/Utils.lua:1086
 BindingConfig_IsOpen = <function> defined @Clicked/Config/Bindings.lua:3460
 IsCata = <function> defined @Clicked/Core/Init.lua:109
 BindingConfig_Initialize = <function> defined @Clicked/Config/Bindings.lua:3439
 SetPendingFrameAttributes = <function> defined @Clicked/Core/AttributeHandler.lua:79
 DeepCopyTable = <function> defined @Clicked/Core/Utils.lua:304
 GetNewBindingTargetTemplate = <function> defined @Clicked/Core/Database.lua:385
 GetActiveBindings = <function> defined @Clicked/Core/BindingProcessor.lua:1700
 ShowAddonIncompatibilityPopup = <function> defined @Clicked/Core/Utils.lua:281
 C
```


It has just been broken this whole time but ONLY on my monk and warrior. the addon works perfectly fine on every other character.

**Comment by gotex007** [comment]
With the prepatch breaking so much and making me have to redo so much, I've decided to delete the settings file in WTF and start from scratch after making comprehensive notes in a txt file for every character so I can remake all of their macros. This should resolve the issue and if it doesn't, I'll open a new ticket with a non-corrupted settings file.
