### ISSUE TITLE
[ADDON_ACTION_BLOCKED]

### ISSUE THREAD

**Issue by nechyu** [Snakybo/Clicked#177]
### Describe the bug

When you click the Elementium Pocket Anvil trinket in the bind, it gives this error.

### Clicked Version

1.13.3

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Lua Errors

4x [ADDON_ACTION_BLOCKED] Модификация 'Clicked' пыталась вызвать защищенную функцию 'Button:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:189: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/EncounterJournalDataProvider.lua"]:44: in function `RefreshAllData'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:587: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:586>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:590: in function `OnMapChanged'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:245: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:243>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2936: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2779: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2644: in function <FrameXML/UIParent.lua:2640>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3246: in function `ShowUIPanel'
[string "@FrameXML/QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@FrameXML/QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:442: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
Skipped (In Encounter)

### Reproduction Steps

Go to DK.
Select Elementium Pocket Anvil
Press it several times.

**Comment by Snakybo** [comment]
I don't think this is actually caused by Clicked as the error log indicates it's something on the world map that's the source of the error. It also never calls `SetPassThroughButtons` on anything.

It could be that it is related to Clicked, but unfortunately taint issues are very hard to debug and the error log does not give me any information unfortunately :/
