### ISSUE TITLE
/clicked profile not working

### ISSUE THREAD

**Issue by jermoo** [Snakybo/Clicked#178]
### Describe the bug

the title says it all, not sure what's up.. addon works perfectly otherwise. 
testing on the PRT  10.2 but went back to retail and it does the same thing.. 

### Clicked Version

10.13.3

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

goto chat
type /clicked profile
nothing happens. 

### Last Working Version

unknown

### Debug Output

Version: 1.13.3
Data Version: 6
Project ID: 1
Race: NightElf
Level: 70
Class: DRUID
Specialization: 105 (Restoration)
Talents: BkGAORarfDaLt4uMx8TYOtl8GIJJRpEJSAAAEJBAAAAAAAAAAAAIESiggEAJJJJCSaJAAAAAAiAAAA
Press Mode: AnyUp
Autogen: False

Possess Bar: disabled
Override Bar: disabled
Vehicle: disabled
Vehicle UI: disabled
Pet Battle: disabled

----- Registered unit frames -----
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
Boss5TargetFrame
CompactArenaFrameMember1
CompactArenaFrameMember1Buff1
CompactArenaFrameMember1Buff2
CompactArenaFrameMember1Buff3
CompactArenaFrameMember1CenterStatusIcon
CompactArenaFrameMember1Debuff1
CompactArenaFrameMember1Debuff2
CompactArenaFrameMember1Debuff3
CompactArenaFrameMember1DispelDebuff1
CompactArenaFrameMember1DispelDebuff2
CompactArenaFrameMember1DispelDebuff3
CompactArenaFrameMember2
CompactArenaFrameMember2Buff1
CompactArenaFrameMember2Buff2
CompactArenaFrameMember2Buff3
CompactArenaFrameMember2CenterStatusIcon
CompactArenaFrameMember2Debuff1
CompactArenaFrameMember2Debuff2
CompactArenaFrameMember2Debuff3
CompactArenaFrameMember2DispelDebuff1
CompactArenaFrameMember2DispelDebuff2
CompactArenaFrameMember2DispelDebuff3
CompactArenaFrameMember3
CompactArenaFrameMember3Buff1
CompactArenaFrameMember3Buff2
CompactArenaFrameMember3Buff3
CompactArenaFrameMember3CenterStatusIcon
CompactArenaFrameMember3Debuff1
CompactArenaFrameMember3Debuff2
CompactArenaFrameMember3Debuff3
CompactArenaFrameMember3DispelDebuff1
CompactArenaFrameMember3DispelDebuff2
CompactArenaFrameMember3DispelDebuff3
CompactArenaFrameMember4
CompactArenaFrameMember4Buff1
CompactArenaFrameMember4Buff2
CompactArenaFrameMember4Buff3
CompactArenaFrameMember4CenterStatusIcon
CompactArenaFrameMember4Debuff1
CompactArenaFrameMember4Debuff2
CompactArenaFrameMember4Debuff3
CompactArenaFrameMember4DispelDebuff1
CompactArenaFrameMember4DispelDebuff2
CompactArenaFrameMember4DispelDebuff3
CompactArenaFrameMember5
CompactArenaFrameMember5Buff1
CompactArenaFrameMember5Buff2
CompactArenaFrameMember5Buff3
CompactArenaFrameMember5CenterStatusIcon
CompactArenaFrameMember5Debuff1
CompactArenaFrameMember5Debuff2
CompactArenaFrameMember5Debuff3
CompactArenaFrameMember5DispelDebuff1
CompactArenaFrameMember5DispelDebuff2
CompactArenaFrameMember5DispelDebuff3
CompactArenaFramePet1
CompactArenaFramePet1Buff1
CompactArenaFramePet1Buff2
CompactArenaFramePet1Buff3
CompactArenaFramePet1CenterStatusIcon
CompactArenaFramePet1Debuff1
CompactArenaFramePet1Debuff2
CompactArenaFramePet1Debuff3
CompactArenaFramePet1DispelDebuff1
CompactArenaFramePet1DispelDebuff2
CompactArenaFramePet1DispelDebuff3
CompactArenaFramePet2
CompactArenaFramePet2Buff1
CompactArenaFramePet2Buff2
CompactArenaFramePet2Buff3
CompactArenaFramePet2CenterStatusIcon
CompactArenaFramePet2Debuff1
CompactArenaFramePet2Debuff2
CompactArenaFramePet2Debuff3
CompactArenaFramePet2DispelDebuff1
CompactArenaFramePet2DispelDebuff2
CompactArenaFramePet2DispelDebuff3
CompactArenaFramePet3
CompactArenaFramePet3Buff1
CompactArenaFramePet3Buff2
CompactArenaFramePet3Buff3
CompactArenaFramePet3CenterStatusIcon
CompactArenaFramePet3Debuff1
CompactArenaFramePet3Debuff2
CompactArenaFramePet3Debuff3
CompactArenaFramePet3DispelDebuff1
CompactArenaFramePet3DispelDebuff2
CompactArenaFramePet3DispelDebuff3
CompactArenaFramePet4
CompactArenaFramePet4Buff1
CompactArenaFramePet4Buff2
CompactArenaFramePet4Buff3
CompactArenaFramePet4CenterStatusIcon
CompactArenaFramePet4Debuff1
CompactArenaFramePet4Debuff2
CompactArenaFramePet4Debuff3
CompactArenaFramePet4DispelDebuff1
CompactArenaFramePet4DispelDebuff2
CompactArenaFramePet4DispelDebuff3
CompactArenaFramePet5
CompactArenaFramePet5Buff1
CompactArenaFramePet5Buff2
CompactArenaFramePet5Buff3
CompactArenaFramePet5CenterStatusIcon
CompactArenaFramePet5Debuff1
CompactArenaFramePet5Debuff2
CompactArenaFramePet5Debuff3
CompactArenaFramePet5DispelDebuff1
CompactArenaFramePet5DispelDebuff2
CompactArenaFramePet5DispelDebuff3
CompactPartyFrameMember1
CompactPartyFrameMember1Buff1
CompactPartyFrameMember1Buff2
CompactPartyFrameMember1Buff3
CompactPartyFrameMember1CenterStatusIcon
CompactPartyFrameMember1Debuff1
CompactPartyFrameMember1Debuff2
CompactPartyFrameMember1Debuff3
CompactPartyFrameMember1DispelDebuff1
CompactPartyFrameMember1DispelDebuff2
CompactPartyFrameMember1DispelDebuff3
CompactPartyFrameMember2
CompactPartyFrameMember2Buff1
CompactPartyFrameMember2Buff2
CompactPartyFrameMember2Buff3
CompactPartyFrameMember2CenterStatusIcon
CompactPartyFrameMember2Debuff1
CompactPartyFrameMember2Debuff2
CompactPartyFrameMember2Debuff3
CompactPartyFrameMember2DispelDebuff1
CompactPartyFrameMember2DispelDebuff2
CompactPartyFrameMember2DispelDebuff3
CompactPartyFrameMember3
CompactPartyFrameMember3Buff1
CompactPartyFrameMember3Buff2
CompactPartyFrameMember3Buff3
CompactPartyFrameMember3CenterStatusIcon
CompactPartyFrameMember3Debuff1
CompactPartyFrameMember3Debuff2
CompactPartyFrameMember3Debuff3
CompactPartyFrameMember3DispelDebuff1
CompactPartyFrameMember3DispelDebuff2
CompactPartyFrameMember3DispelDebuff3
CompactPartyFrameMember4
CompactPartyFrameMember4Buff1
CompactPartyFrameMember4Buff2
CompactPartyFrameMember4Buff3
CompactPartyFrameMember4CenterStatusIcon
CompactPartyFrameMember4Debuff1
CompactPartyFrameMember4Debuff2
CompactPartyFrameMember4Debuff3
CompactPartyFrameMember4DispelDebuff1
CompactPartyFrameMember4DispelDebuff2
CompactPartyFrameMember4DispelDebuff3
CompactPartyFrameMember5
CompactPartyFrameMember5Buff1
CompactPartyFrameMember5Buff2
CompactPartyFrameMember5Buff3
CompactPartyFrameMember5CenterStatusIcon
CompactPartyFrameMember5Debuff1
CompactPartyFrameMember5Debuff2
CompactPartyFrameMember5Debuff3
CompactPartyFrameMember5DispelDebuff1
CompactPartyFrameMember5DispelDebuff2
CompactPartyFrameMember5DispelDebuff3
CompactPartyFramePet1
CompactPartyFramePet1Buff1
CompactPartyFramePet1Buff2
CompactPartyFramePet1Buff3
CompactPartyFramePet1CenterStatusIcon
CompactPartyFramePet1Debuff1
CompactPartyFramePet1Debuff2
CompactPartyFramePet1Debuff3
CompactPartyFramePet1DispelDebuff1
CompactPartyFramePet1DispelDebuff2
CompactPartyFramePet1DispelDebuff3
CompactPartyFramePet2
CompactPartyFramePet2Buff1
CompactPartyFramePet2Buff2
CompactPartyFramePet2Buff3
CompactPartyFramePet2CenterStatusIcon
CompactPartyFramePet2Debuff1
CompactPartyFramePet2Debuff2
CompactPartyFramePet2Debuff3
CompactPartyFramePet2DispelDebuff1
CompactPartyFramePet2DispelDebuff2
CompactPartyFramePet2DispelDebuff3
CompactPartyFramePet3
CompactPartyFramePet3Buff1
CompactPartyFramePet3Buff2
CompactPartyFramePet3Buff3
CompactPartyFramePet3CenterStatusIcon
CompactPartyFramePet3Debuff1
CompactPartyFramePet3Debuff2
CompactPartyFramePet3Debuff3
CompactPartyFramePet3DispelDebuff1
CompactPartyFramePet3DispelDebuff2
CompactPartyFramePet3DispelDebuff3
CompactPartyFramePet4
CompactPartyFramePet4Buff1
CompactPartyFramePet4Buff2
CompactPartyFramePet4Buff3
CompactPartyFramePet4CenterStatusIcon
CompactPartyFramePet4Debuff1
CompactPartyFramePet4Debuff2
CompactPartyFramePet4Debuff3
CompactPartyFramePet4DispelDebuff1
CompactPartyFramePet4DispelDebuff2
CompactPartyFramePet4DispelDebuff3
CompactPartyFramePet5
CompactPartyFramePet5Buff1
CompactPartyFramePet5Buff2
CompactPartyFramePet5Buff3
CompactPartyFramePet5CenterStatusIcon
CompactPartyFramePet5Debuff1
CompactPartyFramePet5Debuff2
CompactPartyFramePet5Debuff3
CompactPartyFramePet5DispelDebuff1
CompactPartyFramePet5DispelDebuff2
CompactPartyFramePet5DispelDebuff3
FocusFrame
FocusFrameToT
Grid2LayoutHeader1UnitButton1
Grid2LayoutHeader1UnitButton10
Grid2LayoutHeader1UnitButton11
Grid2LayoutHeader1UnitButton12
Grid2LayoutHeader1UnitButton13
Grid2LayoutHeader1UnitButton14
Grid2LayoutHeader1UnitButton15
Grid2LayoutHeader1UnitButton16
Grid2LayoutHeader1UnitButton17
Grid2LayoutHeader1UnitButton18
Grid2LayoutHeader1UnitButton19
Grid2LayoutHeader1UnitButton2
Grid2LayoutHeader1UnitButton20
Grid2LayoutHeader1UnitButton21
Grid2LayoutHeader1UnitButton22
Grid2LayoutHeader1UnitButton23
Grid2LayoutHeader1UnitButton24
Grid2LayoutHeader1UnitButton25
Grid2LayoutHeader1UnitButton26
Grid2LayoutHeader1UnitButton27
Grid2LayoutHeader1UnitButton28
Grid2LayoutHeader1UnitButton29
Grid2LayoutHeader1UnitButton3
Grid2LayoutHeader1UnitButton30
Grid2LayoutHeader1UnitButton31
Grid2LayoutHeader1UnitButton32
Grid2LayoutHeader1UnitButton33
Grid2LayoutHeader1UnitButton34
Grid2LayoutHeader1UnitButton35
Grid2LayoutHeader1UnitButton36
Grid2LayoutHeader1UnitButton37
Grid2LayoutHeader1UnitButton38
Grid2LayoutHeader1UnitButton39
Grid2LayoutHeader1UnitButton4
Grid2LayoutHeader1UnitButton40
Grid2LayoutHeader1UnitButton5
Grid2LayoutHeader1UnitButton6
Grid2LayoutHeader1UnitButton7
Grid2LayoutHeader1UnitButton8
Grid2LayoutHeader1UnitButton9
PetFrame
PlayerFrame
SUFHeaderpartyUnitButton1
SUFUnitfocus
SUFUnitfocustarget
SUFUnitpet
SUFUnitplayer
SUFUnittarget
SUFUnittargettarget
SUFUnittargettargettarget
TargetFrame
TargetFrameToT

----- Registered sidecars -----
ClickedSidecar1 (for PartyMemberFrame1)
ClickedSidecar2 (for PartyMemberFrame1PetFrame)
ClickedSidecar3 (for PartyMemberFrame2)
ClickedSidecar4 (for PartyMemberFrame2PetFrame)
ClickedSidecar5 (for PartyMemberFrame3)
ClickedSidecar6 (for PartyMemberFrame3PetFrame)
ClickedSidecar7 (for PartyMemberFrame4)
ClickedSidecar8 (for PartyMemberFrame4PetFrame)

----- Saved Global Variables -----
lodJlK4cUKkli14cUGIYpTmZbiJYsTOIZm)8IZpZIl4KYmVuYmV0lgOYkjUGtVO8lTaOSZl1kkXDq89mL48Zqi8DcIQHksozMEgLuEQGiJljGAjoad

----- Saved Profile Variables -----
T4yupiimmq4Ft8I)aqtmeJ8Y0xBYWvGg3Ax2QI8V3nGxAU0V7UwObEagDnIGjMKrYxede7iEkxqkyy8NEnjFIDoOVPq92xV9uw3Xtv0H1Vyktcd9N2J1Ux0rqjQfy1Qr4B46fzHHH9Z9KT5mnXO7U4OrQuufPI4vkUPdetbBSgppllD8zjeTjnGScTGzMCyXNwFepnnRlyDUTc()

**Comment by jermoo** [comment]
I edited the config file directly and got it working but the average person probably won't know to do that.

**Comment by Snakybo** [comment]
I switched those subcommands out for a general `/clicked opt[ions]` because I've always had trouble getting them to work correctly, often enough it would just open the settings page and not the specific category.
