### ISSUE TITLE
Issue with loading bindings on toons with stances but not specialization

### ISSUE THREAD

**Issue by Squishes** [Snakybo/Clicked#18]
This error happened on a low level rogue that had learned stealth:
x11  Clicked\Core\Utils.lua:238: bad argument #1 to 'unpack' (table expected, got nil)
Stack: [string "=[C]"]: in function 'unpack'
[string "@Clicked\Core\Utils.lua"]:238: in function 'GetShapeshiftFormsForSpecId'
[string "@Clicked\Core\BindingProcessor.lua"]:810: in function 'validationFunc'
[string "@Clicked\Core\BindingProcessor.lua"]:642: in function 'ValidateTriStateLoadOption'
[string "@Clicked\Core\BindingProcessor.lua"]:816: in function 'CanBindingLoad'
[string "@Clicked\Core\BindingProcessor.lua"]:594: in function 'ReloadActiveBindings'
[string "@Clicked\Core\Clicked-0.10.0.lua"]:69: in function <Clicked\Core\Clicked.lua:65>
[string "=[C]"]: ?
[string "@RealUI_Bugs\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ugs\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@RealUI_Bugs\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function 'Fire'
[string "@Bartender4\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
Time: 2020/11/03 20:39:24 Index: 1/1
RealUI Version: 2.2.4
Locals:
None

I was able to fix it by modifying Utils.lua to include the initial IDs for each class listed here: https://wow.gamepedia.com/SpecializationID

I think I made a pull request to add my changes; I've never used Github before, so not sure if I did it correctly.

**Comment by Squishes** [comment]
#17

**Comment by Snakybo** [comment]
Fixed in 0.10.1, thanks!
