### ISSUE TITLE
changing runes in SoD doesn't trigger spell known check

### ISSUE THREAD

**Issue by whitter392** [Snakybo/Clicked#185]
### Describe the bug

spell known seems to work for checking which runes are currently active. however, loading binds based on spell known for runes requires a reload.

### Clicked Version

1.14

### World of Warcraft Flavor

Classic

### Tried with only Clicked enabled

- [ ] Yes
- [X] No

### Reproduction Steps

set a spell known condition for bind based on rune
change rune
bind is not updated unless you reload

**Comment by Snakybo** [comment]
Hey, I don't play SoD so I can't test this myself, but I think I have a patch that should fix this. Would you be able to try the pre-release version to see if it works?

https://github.com/Snakybo/Clicked/releases/tag/1.14.1-beta

**Comment by whitter392** [comment]
it could use a check when the equipment is changed in those slots in case the rune is different on the other item. idk if it's too complicated. the weakauras spell known trigger does work for this case

**Comment by Snakybo** [comment]
Good catch, will add that in :)

**Comment by Snakybo** [comment]
Got another pre-release version that should do that:

https://github.com/Snakybo/Clicked/releases/tag/1.14.1-beta-2
