### ISSUE TITLE
[SoD] Target of target to Blacklist catalog

### ISSUE THREAD

**Issue by Hessutar** [Snakybo/Clicked#193]
Heya! Would it be possible to add Target of target to the blacklist catalog? Atleast in the SoD version it seems to be missing from the blacklistable frames. Thank you in advance!

![image](https://github.com/Snakybo/Clicked/assets/5693510/4d87cf93-4fe1-4c4f-a44c-7bfeb735f052)

-Hessutar

**Comment by Snakybo** [comment]
Good catch! This is fixed in the next update :)
