### ISSUE TITLE
Cataclysm Mage Not Working Correctly

### ISSUE THREAD

**Issue by Morituriii** [Snakybo/Clicked#196]
### Describe the bug

When playing with the mage class, either all skills are active when logging in (ignoring current class spec load condition and even if the spell is keybind or not) or everything is greyed out and de-active. This issue does not seem to be present in any other class that I've encountered.

Screenshot 1: Shows how it looks like when logging into the game when having the addon enabled on mage class.

I have tried making a new Mage profile, but the problem persist. 

### Clicked Version

Clicked 1.14.9

### World of Warcraft Flavor

Cataclysm

### Tried with only Clicked enabled

- [x] Yes
- [ ] No

### Reproduction Steps

1: Create / Select Mage class
2: Login
3: Open up Clicked keybind window
4: Observe.

### Last Working Version

Pre Cataclysm.

### Screenshots

![image](https://github.com/Snakybo/Clicked/assets/106593890/4f2761eb-fcc6-46e2-8bae-f54711cc00d8)

**Comment by Morituriii** [comment]
This problem persists, I tried an older version, 1.14,8, and same issue there. I did notice that if you go into NEW -> AUTOMATICALLY IMPORT FROM SPELLBOOK -> CREATE, it seems to "fix" the issue and the addon is usable, but this needs to be done on every login.

**Comment by Aeceon** [comment]
I logged on my level 80 Mage on Cataclysm who has no talents selected and received this error:

>Clicked/Core/BindingProcessor.lua:887: table index is nil
>[string "@Clicked/Core/BindingProcessor.lua"]:887: in function `UpdateTalentCacheAndReloadBindings'
>[string "@Clicked/Core/BindingProcessor.lua"]:825: in function <Clicked/Core/BindingProcessor.lua:823>

It's this code:

```lua
		for tab = 1, GetNumTalentTabs() do
			for index = 1, GetNumTalents(tab) do
				local name, _, _, _, rank  = GetTalentInfo(tab, index)
				talentCache[name] = rank > 0
			end
		end
```

I believe it might be an issue on Blizzards end. GetTalentInfo(1,21) is returning "nil" for its name. GetTalentInfo(1,22) is Improved Arcane Explosion. There are only 21 talents in the Arcane tree.

A temporary fix:

```lua
				if name then
					talentCache[name] = rank > 0
				end
```

**Comment by Snakybo** [comment]
Thanks, I've been pretty busy lately so haven't gotten around to this. This should be fixed next release :)
