### ISSUE TITLE
Additional Lua errors 10.2

### ISSUE THREAD

**Issue by nedempst** [Snakybo/Clicked#20]
![image](https://user-images.githubusercontent.com/59960468/98151224-ca5a9480-1f0a-11eb-865d-66f0c10e92f7.png)

**Comment by nedempst** [comment]
Just got it zoning into naztajar

**Comment by Snakybo** [comment]
Thanks so much, fixed :)

**Comment by nedempst** [comment]
No worries just one day give Midian the druid a kudos in the version 
notes haha :)

------ Original Message ------

**Comment by Snakybo** [comment]
Hey that's not a bad idea 😄
