### ISSUE TITLE
Clicked doesn't seem to recognize Cell Unit Frames

### ISSUE THREAD

**Issue by ZINK-ZINK** [Snakybo/Clicked#200]
### Describe the bug

Clicked works properly with other Frames, but not with the Addon: Cell

https://www.curseforge.com/wow/addons/cell

### Clicked Version

1.15.1

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [ ] Yes
- [X] No

### Lua Errors

.

### Reproduction Steps

.

**Comment by Snakybo** [comment]
This is a missing feature on Cell's side and seems to be intended.

See: https://github.com/enderneko/Cell?tab=readme-ov-file#not-supported-and-probably-wont-be-included-in-the-future

Unfortunately I can't do anything to fix this on my side
