### ISSUE TITLE
Import bug

### ISSUE THREAD

**Issue by geraint425** [Snakybo/Clicked#201]
### Describe the bug

When importing from spellbook automatically, it gives an error.

### Clicked Version

1.15.1

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [ ] Yes
- [X] No

### Lua Errors

2x Clicked/Config/Bindings.lua:2735: table index is nil
[string "@Clicked/Config/Bindings.lua"]:2735: in function <Clicked/Config/Bindings.lua:2678>
[string "@Clicked/Config/Bindings.lua"]:2961: in function <Clicked/Config/Bindings.lua:2960>
[string "=[C]"]: ?
[string "@Clicked/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Clicked/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Clicked/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Clicked/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...cked/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Locals:
identifier = "IMPORT_SPELLBOOK"
item = nil
pendingSpells = <table> {
 393262 = true
 372608 = true
 131225 = true
 372610 = true
}
pendingGroups = <table> {
 Общие = 136830
}
groups = <table> {
}
(for state) = <table> {
 117952 = <table> {
 }
 115450 = <table> {
 }
 131225 = <table> {
 }
 393262 = <table> {
 }
 115546 = <table> {
 }
 372608 = <table> {
 }
 372610 = <table> {
 }
 198898 = <table> {
 }
 131228 = <table> {
 }
 122783 = <table> {
 }
 424187 = <table> {
 }
 115181 = <table> {
 }
 388615 = <table> {
 }
 131229 = <table> {
 }
 322507 = <table> {
 }
 116680 = <table> {
 }
 382499 = <table> {
 }
 393273 = <table> {
 }
 115294 = <table> {
 }
 403092 = <table> {
 }
 382501 = <table> {
 }
 131232 = <table> {
 }
 137639 = <table> {
 }
 393276 = <table> {
 }
 445424 = <table> {
 }
 152175 = <table> {
 }
 119582 = <table> {
 }
 115008 = <table> {
 }
 424197 = <table> {
 }
 116841 = <table> {
 }
 393279 = <table> {
 }
 373262 = <table> {
 }
 247483 = <table> {
 }
 325197 = <table> {
 }
 131204 = <table> {
 }
 393283 = <table> {
 }
 373586 = <table> {
 }
 354462 = <table> {
 }
 374990 = <table> {
 }
 115313 = <table> {
 }
 131206 = <table> {
 }
 424142 = <table> {
 }
 413050 = <table> {
 }
 354464 = <table> {
 }
 376777 = <table> {
 }
 113656 = <table> {
 }
 354465 = <table> {
 }
 123904 = <table> {
 }
 132578 = <table> {
 }
 159895 = <table> {
 }
 116844 = <table> {
 }
 354467 = <table> {
 }
 373274 = <table> {
 }
 354468 = <table> {
 }
 115203 = <table> {
 }
 388193 = <table> {
 }
 159897 = <table> {
 }
 101545 = <table> {
 }
 159898 = <table> {
 }
 109132 = <table> {
 }
 159899 = <table> {
 }
 424153 = <table> {
 }
 367416 = <table> {
 }
 159900 = <table> {
 }
 322729 = <table> {
 }
 392983 = <table> {
 }
 119381 = <table> {
 }
 116847 = <table> {
 }
 432254 = <table> {
 }
 443028 = <table> {
 }
 159902 = <table> {
 }
 387184 = <table> {
 }
 410071 = <table> {
 }
 393222 = <table> {
 }
 324312 = <table> {
 }
 432257 = <table> {
 }
 116095 = <table> {
 }
 115175 = <table> {
 }
 322118 = <table> {
 }
 432258 = <table> {
 }
 431709 = <table> {
 }
 399491 = <table> {
 }
 159901 = <table> {
 }
 410074 = <table> {
 }
 424163 = <table> {
 }
 116705 = <table> {
 }
 212051 = <table> {
 }
 124682 = <table> {
 }
 233759 = <table> {
 }
 125439 = <table> {
 }
 6603 = <table> {
 }
 322101 = <table> {
 }
 115078 = <table> {
 }
 393256 = <table> {
 }
 100784 = <table> {
 }
 159896 = <table> {
 }
 383366 = <table> {
 }
 325153 = <table> {
 }
 115151 = <table> {
 }
 410078 = <table> {
 }
 424167 = <table> {
 }
 115176 = <table> {
 }
 122470 = <table> {
 }
 436854 = <table> {
 }
 122278 = <table> {
 }
 218164 = <table> {
 }
 116849 = <table> {
 }
 410080 = <table> {
 }
 123986 = <table> {
 }
 322109 = <table> {
 }
 129597 = <table> {
 }
 354463 = <table> {
 }
 107428 = <table> {
 }
 115310 = <table> {
 }
 121253 = <table> {
 }
 100780 = <table> {
 }
 125883 = <table> {
 }
 115315 = <table> {
 }
 383359 = <table> {
 }
 393267 = <table> {
 }
 131205 = <table> {
 }
 116670 = <table> {
 }
 101643 = <table> {
 }
 393764 = <table> {
 }
 383363 = <table> {
 }
 115399 = <table> {
 }
 425782 = <table> {
 }
 131222 = <table> {
 }
 461404 = <table> {
 }
 361584 = <table> {
 }
 131231 = <table> {
 }
 393766 = <table> {
 }
 126892 = <table> {
 }
 115178 = <table> {
 }
 119996 = <table> {
 }
 101546 = <table> {
 }
 354469 = <table> {
 }
 354466 = <table> {
 }
}
(for control) = 198898
_ = 198898
spell = <table> {
 specId = 269
 name = "Песнь Чи-Цзи"
 tabIcon = 608953
 tabName = "Танцующая с ветром"
 icon = 332402
}
(*temporary) = nil
(*temporary) = <table> {
 specId = 269
 name = "Песнь Чи-Цзи"
 tabIcon = 608953
 tabName = "Танцующая с ветром"
 icon = 332402
}
(*temporary) = false
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }

### Reproduction Steps

1. Opened the addon.
2. Pressed New
3. clicked Create next to Automativcally import from spellbook
4. Lua error

**Comment by Snakybo** [comment]
Thanks, will release a fix now
