### ISSUE TITLE
Do not reset focus and editing progress on widgets when reloading bindings

### ISSUE THREAD

**Issue by m33shoq** [Snakybo/Clicked#204]
## Is your feature request related to a problem?
Currently on every event that may change load of a bindings(e.g. `GROUP_ROSTER_UPDATE` or `ZONE_CHANGED`) it resets the focus on widgets.

If you start writing something in editbox or choosing values in dropdown the event will reset your progress on editing.

I find this frustrating especially when trying to change the binding in a raid before a boss when a raid leader shuffles frames for the upcoming boss and each such frame move results in `GROUP_ROSTER_UPDATE` that makes modifing bindings during the shuffle impossible 

## Describe the solution you'd like
Do not reset focus and editing progress on widgets when reloading bindings

## Additional context
![Wow_c4K63tDGM7](https://github.com/user-attachments/assets/6ec6d1bc-8d0d-4134-923e-ef895c1135cc)

**Comment by Snakybo** [comment]
Yeah, this is a larger grip that I've been slowly working on, unfortunately it requires close to a total rewrite of the UI there so it'll take some time.

**Comment by Snakybo** [comment]
Fixed in 1.16.0 :)
