### ISSUE TITLE
Characters that don't already have macros can't make "cast a spell" ones.

### ISSUE THREAD

**Issue by gotex007** [Snakybo/Clicked#205]
### Describe the bug

Characters that don't already have macros can't make new ones apparently. Throws an error and the actions tab doesn't load.

It still works fine on the two characters I have already made macros on since I deleted my settings to start over with the prepatch.

### Clicked Version

1.15.3

### World of Warcraft Flavor

Dragonflight

### Tried with only Clicked enabled

- [ ] Yes
- [ ] No

### Lua Errors

8x Clicked/Config/SpellLibrary.lua:90: 'for' limit must be a number
[string "@Clicked/Config/SpellLibrary.lua"]:90: in function <Clicked/Config/SpellLibrary.lua:32>
[string "=(tail call)"]: ?
[string "@Clicked/Config/SpellLibrary.lua"]:236: in function `GetSpells'
[string "@Clicked/Config/Bindings.lua"]:1180: in function `CreateOptions'
[string "@Clicked/Config/Bindings.lua"]:1197: in function <Clicked/Config/Bindings.lua:1033>
[string "@Clicked/Config/Bindings.lua"]:1720: in function <Clicked/Config/Bindings.lua:1710>
[string "@Clicked/Config/Bindings.lua"]:3054: in function <Clicked/Config/Bindings.lua:3041>
[string "=[C]"]: ?
[string "@Clicked/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Clicked/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Clicked/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Clicked/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Clicked/Config/Bindings.lua"]:3116: in function <Clicked/Config/Bindings.lua:2982>
...
[string "@Clicked/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:1325: in function `Select'
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:1330: in function `SelectByPath'
[string "@Clicked/Widgets/AceGUIContainer-ClickedTreeGroup.lua"]:1349: in function `SelectByBindingOrGroup'
[string "@Clicked/Config/Bindings.lua"]:2948: in function <Clicked/Config/Bindings.lua:2684>
[string "@Clicked/Config/Bindings.lua"]:2967: in function <Clicked/Config/Bindings.lua:2966>
[string "=[C]"]: ?
[string "@Clicked/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Clicked/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Clicked/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Clicked/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...cked/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Locals:
result = <table> {
 698 = <table> {
 }
 6353 = <table> {
 }
 702 = <table> {
 }
 59752 = <table> {
 }
 5740 = <table> {
 }
 108416 = <table> {
 }
 111771 = <table> {
 }
 27243 = <table> {
 }
 108503 = <table> {
 }
 980 = <table> {
 }
 126 = <table> {
 }
 1122 = <table> {
 }
 265187 = <table> {
 }
 5019 = <table> {
 }
 333889 = <table> {
 }
 196277 = <table> {
 }
 6201 = <table> {
 }
 1098 = <table> {
 }
 80240 = <table> {
 }
 387976 = <table> {
 }
 125439 = <table> {
 }
 111898 = <table> {
 }
 20707 = <table> {
 }
 342601 = <table> {
 }
 324536 = <table> {
 }
 17962 = <table> {
 }
 116858 = <table> {
 }
 17877 = <table> {
 }
 152108 = <table> {
 }
 83958 = <table> {
 }
 264119 = <table> {
 }
 264130 = <table> {
 }
 196447 = <table> {
 }
 105174 = <table> {
 }
 386833 = <table> {
 }
 267171 = <table> {
 }
 382499 = <table> {
 }
 6789 = <table> {
 }
 264178 = <table> {
 }
 29893 = <table> {
 }
 267211 = <table> {
 }
 5782 = <table> {
 }
 316099 = <table> {
 }
 172 = <table> {
 }
 382501 = <table> {
 }
 1714 = <table> {
 }
 334275 = <table> {
 }
 104316 = <table> {
 }
 234153 = <table> {
 }
 6603 = <table> {
 }
 686 = <table> {
 }
 104773 = <table> {
 }
 30283 = <table> {
 }
 755 = <table> {
 }
 111400 = <table> {
 }
 5697 = <table> {
 }
 119898 = <table> {
 }
}
activeTabName = "Affliction"
activetabIcon = 136145
count = nil
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = <table> {
 shouldHide = false
 offSpecID = 267
 name = "Destruction"
 numSpellBookItems = 13
 specID = 267
 iconID = 136186
 isGuild = false
 itemIndexOffset = 150
}
(*temporary) = 163
(*temporary) = 163
(*temporary) = 1
(*temporary) = 163
(*temporary) = <table> {
 skillLineIndex = 5
 itemType = 1
 isOffSpec = true
 subName = ""
 actionID = 77220
 name = "Mastery: Chaotic Energies"
 iconID = 135799
 isPassive = true
 spellID = 77220
}
(*temporary) = <table> {
 skillLineIndex = 5
 itemType = 1
 isOffSpec = true
 subName = ""
 actionID = 77220
 name = "Mastery: Chaotic Energies"
 iconID = 135799
 isPassive = true
 spellID = 77220
}
(*temporary) = <table> {
 shouldHide = false
 offSpecID = 267
 name = "Destruction"
 numSpellBookItems = 13
 specID = 267
 iconID = 136186
 isGuild = false
 itemIndexOffset = 150
}
(*temporary) = "'for' limit must be a number"
Addon = <table> {
 InteractionType = <table> {
 }
 AddonOptions = <table> {
 }
 CommandType = <table> {
 }
 StringUtils = <table> {
 }
 GroupState = <table> {
 }
 EXPANSION_LEVEL = 11
 BindingTypes = <table> {
 }
 Media = <table> {
 }
 ExportFrame = <table> {
 }
 KeyLayouts = <table> {
 }
 L = <table> {
 }
 TOOLTIP_SHOW_DELAY = 0.300000
 TargetHostility = <table> {
 }
 db = <table> {
 }
 DATA_VERSION = 10
 SpellLibrary = <table> {
 }
 KeyboardSizes = <table> {
 }
 KeyVisualizer = <table> {
 }
 KeyboardLayouts = <table> {
 }
 ImportFrame = <table> {
 }
 ProfileOptions = <table> {
 }
 EXPANSION = <table> {
 }
 BindingScope = <table> {
 }
 MACRO_FRAME_HANDLER_NAME = "ClickedMacroFrameHandler"
 TargetUnits = <table> {
 }
 BlacklistOptions = <table> {
 }
 ClickCastHeader = ClickCastHeader {
 }
 TargetVitals = <table> {
 }
}

### Reproduction Steps

1. log into a character with no macros yet created (I tried both my druid and warlock)
2. create one for either type of "cast a spell"
3. error thrown and action tab doesn't load

### Last Working Version

1.15.2

### Screenshots

![mTzxxsL](https://github.com/user-attachments/assets/dd478a3f-7a29-4bb2-b448-34c3c7d9a65a)

**Comment by gotex007** [comment]
Actually my monk is throwing the same error despite already having a character macro on him that I forgot I had made. The error is still the exact same too with affliction and destruction mentioned. I don't know why it doesn't affect my hunter and paladin though.

**Comment by Snakybo** [comment]
Whoops, pushed a new release that fixes this, thanks!
