### ISSUE TITLE
I can't use skyriding abilities if a Clicked macro is in the same keybind. The [noflying] and [nobonusbar:5] conditionals don't seem to be working.

### ISSUE THREAD

**Issue by gotex007** [Snakybo/Clicked#206]
### Describe the bug

I don't know if this is a Clicked issue or a Blizzard issue, but it's causing issues with skyriding where I can't Whirling Surge because I have a Clicked macro for Purify Disease also on the 5 key.

I tried playing around with built in conditional tickboxes in Clicked itself and just couldn't figure out a way to make it work.

### Clicked Version

1..15.3b

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [ ] Yes
- [ ] No

### Reproduction Steps

One macro I was using prior to prepatch was this:

/use [@mouseover,help,nochanneling,noflying][@target,help,nochanneling,noflying][@focus,help,nochanneling,noflying][@player,nochanneling,noflying]Purify Disease
/use [flying]Whirling Surge

Replacing [flying] with [nobonusbar:5] also does not work.

### Last Working Version

Before prepatch. I don't know which version.

**Comment by Snakybo** [comment]
Try the following:
![image](https://github.com/user-attachments/assets/8cff212a-5541-4df8-87a2-bd391fda8573)

![image](https://github.com/user-attachments/assets/15bca141-44c3-47f2-ac27-cb0706a4430c)

**Comment by gotex007** [comment]
Aerial Halt seems to work, but Whirling Surge does not.

**Comment by tharax** [comment]
@Snakybo still having issues, if I don't have spells for 1-4 then it won't default to allow me using my action bars.

For example, on my warrior I can use Avatar (`ALT-2`) but not Charge (`1`):
<img width="914" alt="image" src="https://github.com/user-attachments/assets/4b575b9c-7b86-4df4-b743-77592d9b4283">

<img width="547" alt="image" src="https://github.com/user-attachments/assets/6b60ffe7-0872-4fdf-8a8e-b9ad600c88b9">

**Comment by Snakybo** [comment]
@tharax the game does not allow for a binding to "fall back" to action bars if no match is found. That's unfortunately a game limitation. The macro conditions are always active and if the binding is loaded it will always eat up your input.

**Comment by tharax** [comment]
@Snakybo interesting, so the "Load conditions" tab can switch on/off a keybinding, but the "Macro conditions" tab can't? Are load conditions checked via a different method, or they are never part of a macro?

**Comment by gotex007** [comment]
Okay for some reason today it works just fine without me changing anything. Hurray? I guess?

**Comment by kdar** [comment]
I wonder if we could add more things to the load conditions, so stuff like skyriding works the way @tharax is saying. We could listen to PLAYER_MOUNT_DISPLAY_CHANGED event and then use C_MountJournal.GetMountInfoByID to get the mount information, which tells us whether we are skyriding or not. Then we could load the skyriding bindings which will override the action bar, and then unload it when we're not skyriding. Or maybe for all edge cases, the loading conditions could be user supplied LUA script?
