### ISSUE TITLE
Weird bug where the UI gets stuck and overlays on top of stuff. I'm not sure how to describe it.

### ISSUE THREAD

**Issue by gotex007** [Snakybo/Clicked#207]
### Describe the bug

~~After some time messing with Clicked stuff, randomly a tab of a macro will just get stuck existing on top of every macro and tab in a macro that I click on.~~ It throws no error when this triggers and it exists until a reload. While the tab is overlayed, clicking on the overlayed part attempts to interact with it, but clicking on the part of the menu that isn't visually covered by the overlay interacts with the actual macro tab. For example, in the screenshots below the Load conditions tab lets me interact with the visible tick boxes but if I click above them it interacts with the overlayed text box.

It does NOT cover the "New" menu though, despite that menu appearing in the same place, but it will cover anything in the macro you make. It also does not cover a "Group".

~~I do not know how to intentionally trigger it. I just know that it eventually happens if I'm messing around in Clicked for awhile.~~ It has happened a handful of times now so I decided to report it even though it throws no error. It didn't really start happening until I had fully replaced all the macros I had before I deleted my settings file to start over fresh.

### Clicked Version

1.15.3b

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [ ] Yes
- [ ] No

### Lua Errors

There is no error when it happens.

### Reproduction Steps

1. Click "New" (happens with any macro, does not need to be a new one)
2. Click "Cast a spell" (any macro type appears to work)
3. Click "Load conditions"
4. Click "Race" twice to make it "Multiple" (any tickbox with "Multiple" appears to work)
5. Select any combination of options you want, so long as you select a new one or unselect the default and select it again
6. Click on a different tab in that same macro, as long as it is not "Action"
7. The tab you selected is now overlayed when you look at any tab in any macro, but not when looking at the "New" menu or at a "Group"

### Last Working Version

This never happened prior to the prepatch I think.

### Screenshots

It's not specific to this macro or this tab, but in this instance [this is the tab that bugged out](https://i.imgur.com/9FIrCZt.png).

You can see that while I'm looking at an unrelated macro, that tab overlays on everything.
[Action](https://imgur.com/OQNrUOO) [Targets](https://imgur.com/EthXz4K) [Load conditions](https://imgur.com/wucxNLe) [Macro conditions](https://imgur.com/4HhOVVZ) [Status](https://imgur.com/Oxy5o3C)

For some reason it DOESN'T overlay on top of [a group](https://imgur.com/iAuaSLZ) or the ["New" menu](https://imgur.com/zYbRXrg).

**Comment by Snakybo** [comment]
Fixed in 1.16.0 :)
