### ISSUE TITLE
After I select "Target Unit Frame" on a new binding, there is no option under "Target" to add a spell

### ISSUE THREAD

**Issue by Gandrage3** [Snakybo/Clicked#209]
### Describe the bug

After I select "Target Unit Frame" on a new binding, there is no option under "Target" to add a spell. I can bind the key, but i cant select a spell from the spellbook

### Clicked Version

Latest

### World of Warcraft Flavor

Classic

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

1) Try and make a new keybind for Target Unit Frame

### Screenshots

![clicked](https://github.com/user-attachments/assets/7cbe5c31-f746-4b5d-b3ba-e79a0c3de444)

**Comment by Snakybo** [comment]
Should be fixed in the next release, thanks :)
