### ISSUE TITLE
Some interface warping...

### ISSUE THREAD

**Issue by nedempst** [Snakybo/Clicked#21]
Some situations where the interface gets muddled and you can't select the right thing due to the overlap.  Can easily fix with a ui reload  but you probably wanted some details so here ya go 👍 
![image](https://user-images.githubusercontent.com/59960468/98193998-5e534d00-1f59-11eb-96ff-81b56f610050.png)

![image](https://user-images.githubusercontent.com/59960468/98194029-6dd29600-1f59-11eb-804c-d80a2504abf7.png)

**Comment by Snakybo** [comment]
Woah, I'll look into that 🤔

**Comment by Snakybo** [comment]
Did you see this again? I haven't been able to reproduce it

**Comment by nedempst** [comment]
Yes a few times usually when I'm mucking around the ui a lot for extended
periods of time.

I just reload ui and it fixes

**Comment by nedempst** [comment]
Got this one as I went out of a winning skirmish



------ Original Message ------

**Comment by nedempst** [comment]
Hi there.

Is there a way to get clicked to disable when you say go into a vehicle 
or thing with "funtion buttons" ?  I dont think I noticed it before but 
for some reason now I think it's causing those buttons to not work while 
in vehicle...

Let me know if you can check this.

------ Original Message ------

**Comment by Snakybo** [comment]
It already disables when in a vehicle or you're possessed, did that not happen somewhere?

**Comment by nedempst** [comment]
The only one that it doesn't seem to function in and disable is the BG 
seething shore. LOL.

------ Original Message ------

**Comment by nedempst** [comment]
Just a thought. But when you are configuring your "targets"; wouldn't it 
be a good idea to make it slightly more intuitive. Like if you click on 
alive, harm, heal etc for a first bind like a mouseover and then add 
another one for target, wouldn't it be OK to assume to default it to the 
same instead of having to manually type all that in again :) ?

Just a thought :)

------ Original Message ------

**Comment by Snakybo** [comment]
I agree, that's a great idea

**Comment by nedempst** [comment]
How about when you are duplicating you get a dialog that asks "How many 
duplicates did you want to make?"

Also if you have a group selected, and you create a bind, it will put it 
in that group by default.

Would help when setting up a new toon.

------ Original Message ------

**Comment by nedempst** [comment]
Anyway to add  a shadowdance stance so I don't have to use a macro ?

------ Original Message ------

**Comment by nedempst** [comment]
Hi there.

100% BTW I disabled Clicked and was able to use the vehicle binds set up 
in the action bar keybinds but if it's loaded it's holding the keys even 
when vehicle is loaded.

Thanks!

------ Original Message ------

**Comment by Snakybo** [comment]
> Anyway to add  a shadowdance stance so I don't have to use a macro ?

Do you currently use a macro with a `[form]` modifier? If so I can add it.

>100% BTW I disabled Clicked and was able to use the vehicle binds set up in the action bar keybinds but if it's loaded it's holding the keys even when vehicle is loaded.

:/ I'll look into it

**Comment by nedempst** [comment]
Going to test this more it seems to look like it will work but so far 
never seems to work on a frame with BUTTON2?

I will test some more to be sure but might be an issue with how it works 
with frame clicks / items.



------ Original Message ------
