### ISSUE TITLE
Random crash MacOS when inputting text

### ISSUE THREAD

**Issue by nedempst** [Snakybo/Clicked#211]
### Describe the bug

When I try to create a new spell so far, it does this sometimes after a few seconds, the wow max window will start clocking and I will have to force close.  It happens quite frequently and only when I am interfacing inside the clicked UI as I mentioned. 

This is on the beta not retail but no drop down there. 

### Clicked Version

Latest

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

As described above just go in and muck around and Inoticed sometimes the text will stop tying and restart, then a few seconds later it will clock and will force me restarting the game. 

### Last Working Version

Unsure

**Comment by Dajova** [comment]
I have noticed the same now... specifically when using the search bar. i write something and then try to remove the text by marking it and delete it... but instead, it hangs the game for some reason. no error or anything, it just... completely freezes the game and forcing me to close ethe game from task manager.

**Comment by Snakybo** [comment]
I noticed the same, will look at this and fix it :)

**Comment by Snakybo** [comment]
Fixed in 1.16.0!
