### ISSUE TITLE
Can't seem to create dragon riding abilities can only import

### ISSUE THREAD

**Issue by nedempst** [Snakybo/Clicked#212]
### Describe the bug

As above.  Beta only.  MacOS version.

### Clicked Version

latest

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [ ] Yes
- [X] No

### Reproduction Steps

Trying to create doesn't seem to recognize the ids as I doesn't create or find the abilities.  This is on my warlock.  Will try on other specs.

### Last Working Version

Unsure

**Comment by Snakybo** [comment]
Should be fixed in 1.16.0
