### ISSUE TITLE
Cancelaura does not convert spell id to spell name

### ISSUE THREAD

**Issue by jgersti** [Snakybo/Clicked#216]
### Describe the bug

Cancelaura does not convert the spell id to a spell name inside the generated macro.
`/cancelaura` does only work with spell names.

### Clicked Version

1.15.6

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

Create a cancelaura binding using a spell id => macro contains spell id and will not work.

**Comment by Snakybo** [comment]
Thanks, I'm working on a bigger UI rework at the moment and I'll make sure this is fixed with that :)

**Comment by Snakybo** [comment]
Fixed in 1.16.0 :)
