### ISSUE TITLE
Cancelaura does not accept Spell Names as Input

### ISSUE THREAD

**Issue by jgersti** [Snakybo/Clicked#217]
### Describe the bug

Cancelaura bindings do only accept spell id like inputs. Spell names are silently ignored. 
Combined with #216 this makes this binding type inoperable.

### Clicked Version

1.15.6

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

Create a cancelaura binding and enter the spell name of a cancelable buff (i.e Slow Fall) => nothing happens

**Comment by Snakybo** [comment]
Fixed in 1.16.0 :)
