### ISSUE TITLE
OR-option for unit frame targets

### ISSUE THREAD

**Issue by oliverfischer83** [Snakybo/Clicked#22]
Hi clicked-team, really love your addon and I'm using it extensively.

In my use case I need to create macros which look like this: /use [@mouseover,help] Blessing of Freedom; [@player] Blessing of Freedom (combination of unit frame target and self target)

I currently didn't find a way to create such a macro within a single binding. There is a workaround to create both macros separately and bind them to the same key (that status window helps a lot when defining the order).

Is it possible to create one or multiple OR-options in the target window, when the first option is "unit frame"?

Cheers,
Oliver

**Comment by Snakybo** [comment]
Hm, yeah. Right now I intended creating multiple bindings for the same ability to serve the OR purpose. However I do like the idea of multiple target sets within one binding to serve as an OR.

For the `Unit Frame` target specifically, I can look into allowing additional targets after it.
