### ISSUE TITLE
Target the unit and Open the unit menu are not loading

### ISSUE THREAD

**Issue by medtryx** [Snakybo/Clicked#221]
### Describe the bug

When selecting create "Target the unit" or  "Open the unit menu" they remain unloaded no matter what keybind you add to them or load settings are selected. This is true for previously existing binds and any new binds created. 

### Clicked Version

1.16.0

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

1. Click Create for Target the unit or open the unit menu.
2. Add a keybind.
3. It remains unloaded.

### Last Working Version

Every previous version I've used. 

### Screenshots

![image](https://github.com/user-attachments/assets/72194afe-9f03-4545-b261-4540ee2b6ca3)

### Debug Output

Version: 1.16.0
Data Version: 11
Project ID: 1
Race: NightElf
Level: 80
Class: DRUID
Talents: CgGAqvgeoHLefPLb/Pa8nkKXDBAAAAAAAAAAAAmxYmZmlZsMzMjxYhhZmFLAMGMzMT0MzMzMzYWgNGAAAAAAAGDYZbmNMmlRgpAAQA2YmZA
Specialization: 104 (Guardian)
Press Mode: AnyUp
Autogen: False

Possess Bar: disabled
Override Bar: disabled
Vehicle: disabled
Vehicle UI: disabled
Pet Battle: disabled

----- Unloaded binding 1 -----
Type: UNIT_SELECT
Keybind: BUTTON1
Scope: 1

Load state:
  value = false

----- Unloaded binding 3 -----
Type: UNIT_MENU
Keybind: BUTTON2
Scope: 1

Load state:
  value = false

----- Unloaded binding 4 -----
Type: UNIT_SELECT
Keybind: '
Scope: 1

Load state:
  value = false

----- Unloaded binding 5 -----
Type: UNIT_MENU
Keybind: Z
Scope: 1

Load state:
  value = false

----- Registered unit frames -----
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
Boss5TargetFrame
CompactArenaFrameMember1
CompactArenaFrameMember1Buff1
CompactArenaFrameMember1Buff2
CompactArenaFrameMember1Buff3
CompactArenaFrameMember1CenterStatusIcon
CompactArenaFrameMember1Debuff1
CompactArenaFrameMember1Debuff2
CompactArenaFrameMember1Debuff3
CompactArenaFrameMember1DispelDebuff1
CompactArenaFrameMember1DispelDebuff2
CompactArenaFrameMember1DispelDebuff3
CompactArenaFrameMember2
CompactArenaFrameMember2Buff1
CompactArenaFrameMember2Buff2
CompactArenaFrameMember2Buff3
CompactArenaFrameMember2CenterStatusIcon
CompactArenaFrameMember2Debuff1
CompactArenaFrameMember2Debuff2
CompactArenaFrameMember2Debuff3
CompactArenaFrameMember2DispelDebuff1
CompactArenaFrameMember2DispelDebuff2
CompactArenaFrameMember2DispelDebuff3
CompactArenaFrameMember3
CompactArenaFrameMember3Buff1
CompactArenaFrameMember3Buff2
CompactArenaFrameMember3Buff3
CompactArenaFrameMember3CenterStatusIcon
CompactArenaFrameMember3Debuff1
CompactArenaFrameMember3Debuff2
CompactArenaFrameMember3Debuff3
CompactArenaFrameMember3DispelDebuff1
CompactArenaFrameMember3DispelDebuff2
CompactArenaFrameMember3DispelDebuff3
CompactArenaFrameMember4
CompactArenaFrameMember4Buff1
CompactArenaFrameMember4Buff2
CompactArenaFrameMember4Buff3
CompactArenaFrameMember4CenterStatusIcon
CompactArenaFrameMember4Debuff1
CompactArenaFrameMember4Debuff2
CompactArenaFrameMember4Debuff3
CompactArenaFrameMember4DispelDebuff1
CompactArenaFrameMember4DispelDebuff2
CompactArenaFrameMember4DispelDebuff3
CompactArenaFrameMember5
CompactArenaFrameMember5Buff1
CompactArenaFrameMember5Buff2
CompactArenaFrameMember5Buff3
CompactArenaFrameMember5CenterStatusIcon
CompactArenaFrameMember5Debuff1
CompactArenaFrameMember5Debuff2
CompactArenaFrameMember5Debuff3
CompactArenaFrameMember5DispelDebuff1
CompactArenaFrameMember5DispelDebuff2
CompactArenaFrameMember5DispelDebuff3
CompactArenaFramePet1
CompactArenaFramePet1Buff1
CompactArenaFramePet1Buff2
CompactArenaFramePet1Buff3
CompactArenaFramePet1CenterStatusIcon
CompactArenaFramePet1Debuff1
CompactArenaFramePet1Debuff2
CompactArenaFramePet1Debuff3
CompactArenaFramePet1DispelDebuff1
CompactArenaFramePet1DispelDebuff2
CompactArenaFramePet1DispelDebuff3
CompactArenaFramePet2
CompactArenaFramePet2Buff1
CompactArenaFramePet2Buff2
CompactArenaFramePet2Buff3
CompactArenaFramePet2CenterStatusIcon
CompactArenaFramePet2Debuff1
CompactArenaFramePet2Debuff2
CompactArenaFramePet2Debuff3
CompactArenaFramePet2DispelDebuff1
CompactArenaFramePet2DispelDebuff2
CompactArenaFramePet2DispelDebuff3
CompactArenaFramePet3
CompactArenaFramePet3Buff1
CompactArenaFramePet3Buff2
CompactArenaFramePet3Buff3
CompactArenaFramePet3CenterStatusIcon
CompactArenaFramePet3Debuff1
CompactArenaFramePet3Debuff2
CompactArenaFramePet3Debuff3
CompactArenaFramePet3DispelDebuff1
CompactArenaFramePet3DispelDebuff2
CompactArenaFramePet3DispelDebuff3
CompactArenaFramePet4
CompactArenaFramePet4Buff1
CompactArenaFramePet4Buff2
CompactArenaFramePet4Buff3
CompactArenaFramePet4CenterStatusIcon
CompactArenaFramePet4Debuff1
CompactArenaFramePet4Debuff2
CompactArenaFramePet4Debuff3
CompactArenaFramePet4DispelDebuff1
CompactArenaFramePet4DispelDebuff2
CompactArenaFramePet4DispelDebuff3
CompactArenaFramePet5
CompactArenaFramePet5Buff1
CompactArenaFramePet5Buff2
CompactArenaFramePet5Buff3
CompactArenaFramePet5CenterStatusIcon
CompactArenaFramePet5Debuff1
CompactArenaFramePet5Debuff2
CompactArenaFramePet5Debuff3
CompactArenaFramePet5DispelDebuff1
CompactArenaFramePet5DispelDebuff2
CompactArenaFramePet5DispelDebuff3
CompactPartyFrameMember1
CompactPartyFrameMember1Buff1
CompactPartyFrameMember1Buff2
CompactPartyFrameMember1Buff3
CompactPartyFrameMember1CenterStatusIcon
CompactPartyFrameMember1Debuff1
CompactPartyFrameMember1Debuff2
CompactPartyFrameMember1Debuff3
CompactPartyFrameMember1DispelDebuff1
CompactPartyFrameMember1DispelDebuff2
CompactPartyFrameMember1DispelDebuff3
CompactPartyFrameMember2
CompactPartyFrameMember2Buff1
CompactPartyFrameMember2Buff2
CompactPartyFrameMember2Buff3
CompactPartyFrameMember2CenterStatusIcon
CompactPartyFrameMember2Debuff1
CompactPartyFrameMember2Debuff2
CompactPartyFrameMember2Debuff3
CompactPartyFrameMember2DispelDebuff1
CompactPartyFrameMember2DispelDebuff2
CompactPartyFrameMember2DispelDebuff3
CompactPartyFrameMember3
CompactPartyFrameMember3Buff1
CompactPartyFrameMember3Buff2
CompactPartyFrameMember3Buff3
CompactPartyFrameMember3CenterStatusIcon
CompactPartyFrameMember3Debuff1
CompactPartyFrameMember3Debuff2
CompactPartyFrameMember3Debuff3
CompactPartyFrameMember3DispelDebuff1
CompactPartyFrameMember3DispelDebuff2
CompactPartyFrameMember3DispelDebuff3
CompactPartyFrameMember4
CompactPartyFrameMember4Buff1
CompactPartyFrameMember4Buff2
CompactPartyFrameMember4Buff3
CompactPartyFrameMember4CenterStatusIcon
CompactPartyFrameMember4Debuff1
CompactPartyFrameMember4Debuff2
CompactPartyFrameMember4Debuff3
CompactPartyFrameMember4DispelDebuff1
CompactPartyFrameMember4DispelDebuff2
CompactPartyFrameMember4DispelDebuff3
CompactPartyFrameMember5
CompactPartyFrameMember5Buff1
CompactPartyFrameMember5Buff2
CompactPartyFrameMember5Buff3
CompactPartyFrameMember5CenterStatusIcon
CompactPartyFrameMember5Debuff1
CompactPartyFrameMember5Debuff2
CompactPartyFrameMember5Debuff3
CompactPartyFrameMember5DispelDebuff1
CompactPartyFrameMember5DispelDebuff2
CompactPartyFrameMember5DispelDebuff3
CompactPartyFramePet1
CompactPartyFramePet1Buff1
CompactPartyFramePet1Buff2
CompactPartyFramePet1Buff3
CompactPartyFramePet1CenterStatusIcon
CompactPartyFramePet1Debuff1
CompactPartyFramePet1Debuff2
CompactPartyFramePet1Debuff3
CompactPartyFramePet1DispelDebuff1
CompactPartyFramePet1DispelDebuff2
CompactPartyFramePet1DispelDebuff3
CompactPartyFramePet2
CompactPartyFramePet2Buff1
CompactPartyFramePet2Buff2
CompactPartyFramePet2Buff3
CompactPartyFramePet2CenterStatusIcon
CompactPartyFramePet2Debuff1
CompactPartyFramePet2Debuff2
CompactPartyFramePet2Debuff3
CompactPartyFramePet2DispelDebuff1
CompactPartyFramePet2DispelDebuff2
CompactPartyFramePet2DispelDebuff3
CompactPartyFramePet3
CompactPartyFramePet3Buff1
CompactPartyFramePet3Buff2
CompactPartyFramePet3Buff3
CompactPartyFramePet3CenterStatusIcon
CompactPartyFramePet3Debuff1
CompactPartyFramePet3Debuff2
CompactPartyFramePet3Debuff3
CompactPartyFramePet3DispelDebuff1
CompactPartyFramePet3DispelDebuff2
CompactPartyFramePet3DispelDebuff3
CompactPartyFramePet4
CompactPartyFramePet4Buff1
CompactPartyFramePet4Buff2
CompactPartyFramePet4Buff3
CompactPartyFramePet4CenterStatusIcon
CompactPartyFramePet4Debuff1
CompactPartyFramePet4Debuff2
CompactPartyFramePet4Debuff3
CompactPartyFramePet4DispelDebuff1
CompactPartyFramePet4DispelDebuff2
CompactPartyFramePet4DispelDebuff3
CompactPartyFramePet5
CompactPartyFramePet5Buff1
CompactPartyFramePet5Buff2
CompactPartyFramePet5Buff3
CompactPartyFramePet5CenterStatusIcon
CompactPartyFramePet5Debuff1
CompactPartyFramePet5Debuff2
CompactPartyFramePet5Debuff3
CompactPartyFramePet5DispelDebuff1
CompactPartyFramePet5DispelDebuff2
CompactPartyFramePet5DispelDebuff3
FocusFrame
FocusFrameToT
PetFrame
PlayerFrame
TargetFrame
TargetFrameToT

----- Registered sidecars -----
ClickedSidecar1 (for PartyMemberFrame1)
ClickedSidecar2 (for PartyMemberFrame1PetFrame)
ClickedSidecar3 (for PartyMemberFrame2)
ClickedSidecar4 (for PartyMemberFrame2PetFrame)
ClickedSidecar5 (for PartyMemberFrame3)
ClickedSidecar6 (for PartyMemberFrame3PetFrame)
ClickedSidecar7 (for PartyMemberFrame4)
ClickedSidecar8 (for PartyMemberFrame4PetFrame)

----- Saved Global Variables -----
1WCSoiqiqqa0VjA8d4sSsZzXQwoj3fwHnIab48e)6fiXIzYw82bkCfuPgzqXu4H4AhV5uwcEmRuGmPWwm3ufqp56DjVT4KVCQ)y2g2V4D1ZHfnRNeVw8MmMazfJ11s54RyPEIRzS2Ny9VzmON)uUjAmFa0qVZ9EqXVp

----- Saved Profile Variables -----
TFv3YPnpq0hNVB)ij9bGeiz80IjfbTt70ruz5fqtKLCLLG4ErE27UYHGjT1jDMEtz8njG0(ZzxD29mWhWNZz(6sGZkD2vkn(H1oBOScVWZzA16n(Da9xEgNTfCvkRHNoyaNLPm5kZAYY0yC0wro9)cBW4H4h3k0bGFjNvbAqshMrHDLUwKH563BHYu5fgjmNWgAwfMjcCPtth3Y20)htxq7vLXOH4OXcpfdPwuv125rZwKmQBVBmj6UiFlHG8RFrWwQf1GlXCd15oyh7xu2is6iqvLGuj0QVl8uB(a0tpVtyJxhHCM1eQYeUFhgygyT4PSbFlOklB)q9Zi26kAdJbpdghI3Zr0Ggev5bH2VP7AwRFRXUZ0boA6WPIcyggVIwwobY9U67FUdEHgm(i0Bv(4rofCGXAlbxtRMnmD0rLZEG4BQJVBnaL(oWObWXdY1sW3v9Utvu0nnOCB58)Y4xUrymG(O82f3Wg85wRRQZr0NZ3tsxEZSPlUD5TdNn)tlNoB5SHhnWf9lV2ikuYRFPHHDc3eBExZDsBrMORETtipE7bTiBSE1lSbzVvp27cQ845c5(PYcH0z)W(My8BrYbBwW8WxLHkVT4HVgp)rc(tg7fU1GFHr5hUYdURevXnRIGt0ecSX6HIJdEIKEItWTQUvyj9LKRMMY(ss6hworvjx((aurqBIWDh2vOTwA8SaKZOCtXpcIjI7Njm3fzs3dYa5ZuxoYAPYtrH3fkJ4b3(68ddE7qVxiV7PJUf8hoPjtxt7iIT77GAsuGZUCX85tJllKifTvZlUoNTinz(s243n(Q57BirIMdwh0XTxn07TkCmUI42FcFfWwgUFE81dx8o8UnwSK1kFDZ1XhQh9FSH2xh50BS4mPK6X)SlhfEFlB37)LXfj1nfGNNEgfKErUErUErUErUtsrUZ7f5(tf5oJ3Li3KXPl(xsI7Cki9sC9sC9sC9sCNKsCx0lX96L4(p(P1VG7cki9YB9YB9YB9YBNKYBVPxE71lV9z(j0VDJMgkPsiIvQaxyqHf1AdKJeu1kfGZjysTM3c1JOfz4xWRToGb6v0t8hfodX2Xl8wlX2IEG7bufI4i0gfs1PU8g7UeZv2IsSBxq7aUSbdzASRRvXsIoG)J

**Comment by Snakybo** [comment]
Yep noticed this too, will have a new version released tonight :)
