### ISSUE TITLE
Some strange bug occurs

### ISSUE THREAD

**Issue by amaxcz** [Snakybo/Clicked#227]
### Describe the bug

race condition

### Clicked Version

1.16.4 from curseforge for Classic SoD

### World of Warcraft Flavor

Classic

### Tried with only Clicked enabled

- [ ] Yes
- [X] No

### Lua Errors

536x Clicked/Conditions/LoadConditions.lua:485: Usage: IsSpellKnownOrOverridesKnown(spellID[, isPet])
[string "=[C]"]: in function `IsSpellKnownOrOverridesKnown'
[string "@Clicked/Conditions/LoadConditions.lua"]:485: in function <Clicked/Conditions/LoadConditions.lua:479>
[string "=[C]"]: in function `xpcall'
[string "@Clicked/Core/Init.lua"]:68: in function `SafeCall'
[string "@Clicked/Core/BindingProcessor.lua"]:1027: in function `UpdateBindingLoadState'
[string "@Clicked/Core/BindingProcessor.lua"]:592: in function `DoReloadBindings'
[string "@Clicked/Core/BindingProcessor.lua"]:611: in function <Clicked/Core/BindingProcessor.lua:573>
[string "@Clicked/Core/BindingProcessor.lua"]:833: in function `ReloadBindingsImmediate'
[string "@Clicked/Core/Clicked.lua"]:143: in function `cb'
[string "@Clicked/Core/BindingProcessor.lua"]:937: in function `DoUpdateTalentCache'
[string "@Clicked/Core/BindingProcessor.lua"]:946: in function `UpdateTalentCache'
[string "@Clicked/Core/Clicked.lua"]:141: in function <Clicked/Core/Clicked.lua:133>
[string "=[C]"]: ?
[string "@AtlasLootClassic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AtlasLootClassic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Attune/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...aceAttune/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "Faerie Fire (Feral)"

### Reproduction Steps

...

**Comment by amaxcz** [comment]
`24x ...faceClicked/BindingConfig/Tabs/Condition.lua:125: Dependency not found: specialization
[string "=[C]"]: in function `assert'
[string "@Clicked/BindingConfig/Tabs/Condition.lua"]:125: in function <...faceClicked/BindingConfig/Tabs/Condition.lua:116>
[string "=(tail call)"]: ?
[string "@Clicked/BindingConfig/Conditions/MultiselectDrawer.lua"]:84: in function <...icked/BindingConfig/Conditions/MultiselectDrawer.lua:54>
[string "=[C]"]: in function `xpcall'
[string "@Clicked/Core/Init.lua"]:68: in function `SafeCall'
[string "@Clicked/BindingConfig/Tabs/Condition.lua"]:62: in function <...faceClicked/BindingConfig/Tabs/Condition.lua:53>
[string "=[C]"]: in function `xpcall'
[string "@Clicked/Core/Init.lua"]:68: in function `SafeCall'
[string "@Clicked/BindingConfig/Pages/Binding.lua"]:294: in function `RedrawTab'
[string "@Clicked/BindingConfig/Tabs/Condition.lua"]:106: in function <...faceClicked/BindingConfig/Tabs/Condition.lua:98>
[string "@Clicked/BindingConfig/Helpers.lua"]:534: in function <Clicked/BindingConfig/Helpers.lua:523>
[string "=[C]"]: ?
[string "@Attune/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Attune/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Attune/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Attune/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...ne/Libs/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

Locals:
(*temporary) = false
(*temporary) = "Dependency not found: specialization"
`

**Comment by Snakybo** [comment]
Hm, will have a look, thanks
