### ISSUE TITLE
Unable to click-bind summoning of mounts

### ISSUE THREAD

**Issue by PatTheMav** [Snakybo/Clicked#228]
### Describe the bug

A few versions back it was possible to create bindings for the summoning of mounts by simply entering the name of the mount into the spell name input field (their "spell" names were also autocompleted.

After an update to the auto-completion system this is not possible anymore, as the mounts are not recognised as spells anymore.

Existing bindings _do_ work however, and even though the "Target spell" label will be coloured red, the spell ID will still be present (e.g. "122708" for the "Grand Expedition Yak").

I've resorted to using custom macros instead which are functionally identical, I just lose out on the simple player state/load condition UI available for other click bindings (e.g. to use a single binding to summon a different mount based on stance).

### Clicked Version

Clicked 1.16.4

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

1. Open "Clicked" interface
2. Click "New"
3. Select "Cast a spell" under "Create a new binding"
4. Click into "Target spell" text input field
5. Start typing name of a collected mount (e.g. "Black Primal Raptor")
6. Observe that only spells from the sellback are provided in the auto-complete list but no mount

**Comment by Snakybo** [comment]
In the next update I've added support for custom spells when it's an exact name match, so if you type "Grand Expedition Yak" it'll show up in the autofill window and no longer be red.
