### ISSUE TITLE
Standard wow icons for custom macros

### ISSUE THREAD

**Issue by oliverfischer83** [Snakybo/Clicked#23]
Hi clicked-team.

In my use cases I'm using multiple custom macros (Action: Run a macro) and I noticed the optional custom icon field, where you can point to a custom icon in the interface directory. It's hard for me to re-design (or copy) those wow icons in order to have them selected there.

Is it possible to select all the standard wow icons like in the standard wow macro menu (/m)?

Cheers,
Oliver

**Comment by Squishes** [comment]
It does use the standard wow icons; you just need to find the name of the icon you want to use, which can be the hard part. You  can search for most things on wowhead. It will have the icon's name listed on the ability or item that you search, which you simply enter after the "Interface\ICONS\" part.

Here's where to see it on wowhead:
![firefox_2020-11-10_16-54-23](https://user-images.githubusercontent.com/7941752/98751773-9a314c80-2375-11eb-99c0-820b90c7ac55.png)
So to use the above icon, you would enter Interface\ICONS\inv_farm_herbseed in the icon input box.

The only icons I've had issues finding so far are the hunter pet command icons (attack, follow, passive, etc).

Though I agree it would be easier if we had a selection window like the base game macro UI provides. I hope this at least helps you set these up until Snakybo can add something better, if he chooses.

**Comment by oliverfischer83** [comment]
Thanks a lot, that really helps.

**Comment by Snakybo** [comment]
Thanks @Squishes :)

An icon picker is on my list as I agree the text field for icons is, eh.. not ideal.
