### ISSUE TITLE
Compatibility with other unit frame addons (question)

### ISSUE THREAD

**Issue by CPyle** [Snakybo/Clicked#231]
I currently use Vuhdo unit frames, and Clicked works perfectly fine with it. I am not sure if this is because Vuhdo has legacy support for "Clique" mode or if it would work out of the box.

I would prefer to use Cell for unit frames now, but the author of Cell has explicitly stated they will not support external click casting addons, and Clicked is too good for me to give up. I don't want to split my bindings across multiple addons.

Is adding support for other raid frames something that would be in scope for Clicked? Is writing a "bridge" addon myself to hook those frames and register them with Clicked a big lift or would it be fairly simple?

Thanks!

**Comment by Snakybo** [comment]
This is an issue with Cell — Unit frames have to register themselves for use by addons like Clicked. See [this](https://github.com/enderneko/Cell?tab=readme-ov-file#not-supported-and-probably-wont-be-included-in-the-future) in the Cell description, so it's something they're actively not wanting to support.

I did however see something a while ago about someone making a custom Cell snippet that makes it work with Clicked, but you'll have to search on the Cell Discord I believe.

**Comment by Snakybo** [comment]
Ah, here it is: https://discord.com/channels/1122747237546610760/1268727594841538651

**Comment by CPyle** [comment]
Thanks, this was very helpful! Cell has a "snippets" feature where you can just insert code that will run after the addon loads its frames, this works.
