### ISSUE TITLE
1.16.6 - Click casting on unit frames broken

### ISSUE THREAD

**Issue by CPyle** [Snakybo/Clicked#232]
### Describe the bug

The 1.16.6 update broke click casting on frames for me

### Clicked Version

1.16.6

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Reproduction Steps

1. Set up a unit frame targetted ability in 1.16.5 so that it works.
2. Update to 1.16.6
3. ---> The binding will no longer work

### Last Working Version

1.16.5

**Comment by Toludin** [comment]
+1, 1.16.6 broke a lot of my binds. Some things still worked (keyboard binds, L/R click) but I know shift-R click, ctrl-R click, F11 (which is one of the keys on the side of my mouse) all didn't work. Had to roll back to 1.16.5 to fix it.

**Comment by Hayato2846** [comment]
Yep, can confirm. Shift + LClick doesnt work

**Comment by Snakybo** [comment]
Hm, that's not good. What unit frames are you using?
