### ISSUE TITLE
Stutter when entering a new area while ElvUI + Clicked are enabled

### ISSUE THREAD

**Issue by Terroosh** [Snakybo/Clicked#234]
### Describe the bug

I have been trying to figure out what has been causing me to stutter every-time I enter a different area(when the area text at the top changes) and I've narrowed it down to an interaction between ElvUI and Clicked. When these two are enabled together the stuttering occurs. Flying around in a zone becomes constant stuttering as you enter and exit areas in the zone. ElvUI by itself does not cause stuttering and Clicked by itself does not cause stuttering. Only when the two are enabled does the stuttering start.

### Clicked Version

1.16.7

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [X] Yes
- [ ] No

### Lua Errors

No lua errors

### Reproduction Steps

Enable ElvUI
Enable Clicked
Stutter Happens

### Screenshots

Video below but It's a lot more noticeable in person than on a recording. Stutter happens right before the area text appears.
Edit: Added better example, please download the file as google's video player processing makes it less noticeable. 
https://drive.google.com/file/d/1LByM22RhXvhecbks6p09pY2r1DlLvHk5/view?usp=sharing

**Comment by Snakybo** [comment]
Hm, it's definitely because of the new subzone and indoor zone support. I'll disable those for now until I can fix this properly.
