### ISSUE TITLE
CPU Usage skyrocketing ?

### ISSUE THREAD

**Issue by Aishuu87** [Snakybo/Clicked#236]
### Describe the bug

All of the sudden, my Clicked CPU Usage has started to skyrocket real bad, making me loose frame every second. I don't really know what's going on, since I didn't really tried to edit anything for a while, and it was working fine before that :/

I saw it go to 50% with 25% memory usage. Doing absolutely nothing while taking this screenshot btw.

![2024-09-24 20_46_23-Window](https://github.com/user-attachments/assets/f1354f03-d003-470e-b94c-1b3b4656d82b)

### Clicked Version

1.16.7

### World of Warcraft Flavor

Retail

### Tried with only Clicked enabled

- [ ] Yes
- [X] No

### Reproduction Steps

I used Addon CPU Usage to monitor cpu load

**Comment by Snakybo** [comment]
Hm, I'll disable the subzone and indoor zone feature until I can address these issues properly, thanks
