### ISSUE TITLE
Add spell casts to tooltip similar to healbot

### ISSUE THREAD

**Issue by h2oboi89** [Snakybo/Clicked#25]
Especially useful if playing multiple characters. I can't always keep all the key bindings straight. Tooltip is nice reminder of what is going on.

**Comment by Snakybo** [comment]
Can you attach a screenshot of what you're referring to? :)

**Comment by Snakybo** [comment]
![image](https://user-images.githubusercontent.com/3172140/99129182-29a45d00-260d-11eb-8cd8-329b1f4f7e9d.png)

Is it this?

**Comment by h2oboi89** [comment]
Close. 

Here are screenshots from my setup: https://imgur.com/a/BF2ogL9
I don't even care about the mana costs, just want the `<Button>: <Action>` bits that adjust as you hit the various modifiers (Shift, Alt, Ctrl).

Current thought was to add it to the standard game tooltip that pops up when you hover over a unit or unit frame.

**Comment by Snakybo** [comment]
Oh that's pretty neat. Does it only show mouse buttons or also keyboard buttons? I'll look into adding something like this in the future.

**Comment by h2oboi89** [comment]
Healbot is mouse only, so only mouse buttons.
