### ISSUE TITLE
Mod Macros

### ISSUE THREAD

**Issue by furtrade** [Snakybo/Clicked#28]
Mod Conditionals within macros don't work. e.g.
```
/cast [mod] schism
/cast smite
```

In this example 'schism' wont cast.

**Comment by Snakybo** [comment]
That makes sense, it will only listen for the exact keybind that you assign to it, so assigning `Q` to a binding won't cause `SHIFT-Q` to activate that binding, even if there is no explicit keybind for `SHIFT-Q`.
