### ISSUE TITLE
Left and right click stop functioning in the ingame world after combat

### ISSUE THREAD

**Issue by Sugarpixie** [Snakybo/Clicked#29]
## Describe the bug
I started having this issue yesterday after updating to version 0.11.0. My Clicked bindings all work fine, but as soon as combat ends, I can no longer use left or right click to interact with the game world. It still works fine in the game menu and my action bars, but I can't rightclick a corpse to loot, or left click a mob to target it. Rotating the camera with left or right mouse button does not work either. Reloading the UI fixes the issue, but it reappears as soon as I've left combat again after fighting something.

I've turned off every addon I have installed and can reproduce the issue reliably with just Clicked and ClickedMedia enabled. I'll add my /cc dump at the bottom of this report, in the screenshots section. Please let me know if there's anything else I can deliver to you to help identify the cause, I'd be more than happy to help. Thanks in advance!

## General information
* **Clicked Version:** 0.11.0
* **WoW Version:** Retail
* **Did it work before?** Yes in version 0.10.3

## Expected behavior
I should still be able to rotate my camera and interact with the in-game world by using the left and right mouse button.

## Reproduction
1. Pull anything nearby to start combat.
2. Kill the mob.
3. After combat ends, left and right click no longer work in the ingame world, both to interact with it and to rotate the camera.

## Screenshots
CC dump log:

Version: 0.11.0
Race: Worgen
Level: 50
Class: DRUID
Specialization: 102
Talents: 1/1 2/3 3/1 4/2 5/1 6/1 7/1
Mode: AnyUp

Possess Bar: disabled
Vehicle: disabled
Vehicle UI: disabled
Pet Battle: disabled

----- Loaded binding 1 -----
Keybind: BUTTON3
Hovercast: false
Action: macro
Identifier: clicked-mouse-3

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,nodead,exists,form:1] Growl; [@target,harm,exists,form:1] Growl

----- Loaded binding 2 -----
Keybind: BUTTON4
Hovercast: true
Action: macro
Identifier: 4

/click ClickedStopCastingButton
/use [@mouseover,harm] Solar Beam

----- Loaded binding 3 -----
Keybind: BUTTON4
Hovercast: false
Action: macro
Identifier: clicked-mouse-4

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,exists] Solar Beam; [@target,harm,nodead,exists] Solar Beam; [@player] Solar Beam

----- Loaded binding 4 -----
Keybind: SHIFT-BUTTON3
Hovercast: true
Action: macro
Identifier: 3

/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Starfire; [@mouseover,help] Wild Growth

----- Loaded binding 5 -----
Keybind: SHIFT-BUTTON3
Hovercast: false
Action: macro
Identifier: clicked-mouse-shift3

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,nodead,exists] Starfire; [@mouseover,help,exists] Wild Growth; [@target,harm,exists] Starfire

----- Loaded binding 6 -----
Keybind: CTRL-BUTTON1
Hovercast: true
Action: macro
Identifier: 1

/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Sunfire; [@mouseover,help] Rejuvenation

----- Loaded binding 7 -----
Keybind: CTRL-BUTTON1
Hovercast: false
Action: macro
Identifier: clicked-mouse-ctrl1

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,nodead,exists,form:1] Mangle; [@mouseover,harm,nodead,exists] Sunfire; [@mouseover,help,exists] Rejuvenation; [@target,harm,nodead,exists] Sunfire; [@target,help,nodead,exists] Rejuvenation; [@target,harm,exists,form:1] Mangle; [@player] Rejuvenation

----- Loaded binding 8 -----
Keybind: CTRL-BUTTON3
Hovercast: true
Action: macro
Identifier: 3

/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Moonfire; [@mouseover,help,form:0/1/2/4] Regrowth

----- Loaded binding 9 -----
Keybind: CTRL-BUTTON3
Hovercast: false
Action: macro
Identifier: clicked-mouse-ctrl3

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,nodead,exists] Moonfire; [@mouseover,help,exists,form:0/1/2/4] Regrowth; [@target,harm,nodead,exists] Moonfire

----- Loaded binding 10 -----
Keybind: SHIFT-BUTTON1
Hovercast: true
Action: macro
Identifier: 1

/click ClickedStopCastingButton
/use [@mouseover,help] Lifebloom; [@mouseover] Wrath

----- Loaded binding 11 -----
Keybind: SHIFT-BUTTON1
Hovercast: false
Action: macro
Identifier: clicked-mouse-shift1

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,nodead,exists,form:1] Ironfur; [@mouseover,help,exists] Lifebloom; [@target,harm,exists,form:1] Ironfur

----- Loaded binding 12 -----
Keybind: BUTTON1
Hovercast: true
Action: target
Identifier: 1

----- Loaded binding 13 -----
Keybind: CTRL-BUTTON2
Hovercast: true
Action: macro
Identifier: 2

/click ClickedStopCastingButton
/use [@mouseover,help] Swiftmend

----- Loaded binding 14 -----
Keybind: CTRL-BUTTON2
Hovercast: false
Action: macro
Identifier: clicked-mouse-ctrl2

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,nodead,exists,form:1] Thrash; [@mouseover,help,exists] Swiftmend; [@target,help,nodead,exists] Swiftmend; [@target,harm,exists,form:1] Thrash; [@player] Swiftmend

----- Loaded binding 15 -----
Keybind: SHIFT-BUTTON2
Hovercast: true
Action: macro
Identifier: 2

/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Starsurge

----- Loaded binding 16 -----
Keybind: SHIFT-BUTTON2
Hovercast: false
Action: macro
Identifier: clicked-mouse-shift2

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,nodead,exists,form:1] Maul; [@target,harm,exists,form:1] Maul

----- Loaded binding 17 -----
Keybind: BUTTON2
Hovercast: true
Action: menu
Identifier: 2

----- Macro Handler Attributes -----
type2: menu
shift-macrotext1: /click ClickedStopCastingButton
shift-macrotext1: /use [@mouseover,help] Lifebloom; [@mouseover] Wrath
type4: macro
ctrl-macrotext1: /click ClickedStopCastingButton
ctrl-macrotext1: /use [@mouseover,harm,nodead] Sunfire; [@mouseover,help] Rejuvenation
shift-macrotext2: /click ClickedStopCastingButton
shift-macrotext2: /use [@mouseover,harm,nodead] Starsurge
macrotext4: /click ClickedStopCastingButton
macrotext4: /use [@mouseover,harm] Solar Beam
shift-type2: macro
ctrl-type2: macro
ctrl-type1: macro
ctrl-macrotext2: /click ClickedStopCastingButton
ctrl-macrotext2: /use [@mouseover,help] Swiftmend
shift-type3: macro
type1: target
shift-type1: macro
ctrl-macrotext3: /click ClickedStopCastingButton
ctrl-macrotext3: /use [@mouseover,harm,nodead] Moonfire; [@mouseover,help,form:0/1/2/4] Regrowth
ctrl-type3: macro
shift-macrotext3: /click ClickedStopCastingButton
shift-macrotext3: /use [@mouseover,harm,nodead] Starfire; [@mouseover,help] Wild Growth

----- Hovercast Attributes -----
type2: menu
shift-macrotext1: /click ClickedStopCastingButton
shift-macrotext1: /use [@mouseover,help] Lifebloom; [@mouseover] Wrath
type4: macro
ctrl-macrotext1: /click ClickedStopCastingButton
ctrl-macrotext1: /use [@mouseover,harm,nodead] Sunfire; [@mouseover,help] Rejuvenation
shift-macrotext2: /click ClickedStopCastingButton
shift-macrotext2: /use [@mouseover,harm,nodead] Starsurge
macrotext4: /click ClickedStopCastingButton
macrotext4: /use [@mouseover,harm] Solar Beam
shift-type2: macro
ctrl-type2: macro
ctrl-type1: macro
ctrl-macrotext2: /click ClickedStopCastingButton
ctrl-macrotext2: /use [@mouseover,help] Swiftmend
shift-type3: macro
type1: target
shift-type1: macro
ctrl-macrotext3: /click ClickedStopCastingButton
ctrl-macrotext3: /use [@mouseover,harm,nodead] Moonfire; [@mouseover,help,form:0/1/2/4] Regrowth
ctrl-type3: macro
shift-macrotext3: /click ClickedStopCastingButton
shift-macrotext3: /use [@mouseover,harm,nodead] Starfire; [@mouseover,help] Wild Growth

----- Registered unit frames -----
PlayerFrame
PetFrame
TargetFrame
TargetFrameToT
FocusFrame
FocusFrameToT
PartyMemberFrame1
PartyMemberFrame1PetFrame
PartyMemberFrame2
PartyMemberFrame2PetFrame
PartyMemberFrame3
PartyMemberFrame3PetFrame
PartyMemberFrame4
PartyMemberFrame4PetFrame
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
CompactRaidFrame1Buff1
CompactRaidFrame1Debuff1
CompactRaidFrame1DispelDebuff1
CompactRaidFrame1Buff2
CompactRaidFrame1Debuff2
CompactRaidFrame1DispelDebuff2
CompactRaidFrame1Buff3
CompactRaidFrame1Debuff3
CompactRaidFrame1DispelDebuff3
CompactRaidFrame1

**Comment by Snakybo** [comment]
Oh that's not good. I'll look at that immediately, thanks! Does it happen all the time after combat?

**Comment by Sugarpixie** [comment]
> Oh that's not good. I'll look at that immediately, thanks! Does it happen all the time after combat?

Yeah, I can reproduce the issue consistently after every combat end. Thanks very much for such a quick response! Let me know if there's any other log or something you need.

**Comment by Snakybo** [comment]
Any chance you could upload the saved variables file? `WOW_FOLDER/WTF/Account/YOUR_ACCOUNT/SavedVariables/Clicked.Lua`

**Comment by Snakybo** [comment]
I'm fairly certain I fixed it, will do a dungeon or two before updating on Curse/WoWI

**Comment by Sugarpixie** [comment]
> I'm fairly certain I fixed it, will do a dungeon or two before updating on Curse/WoWI

I downloaded the latest revision and installed it manually to test, seems the issue is fixed! Thanks very much for such a swift response! Great addon, makes my life as a reformed Druid main so much easier with all the form switching! ❤️👏

**Comment by Snakybo** [comment]
Cheers :)
