### ISSUE TITLE
Clicked just stoped working for no reason.

### ISSUE THREAD

**Issue by Alctroz** [Snakybo/Clicked#30]
## Describe the bug
I have 2 wow accounts, I open them once per time.
On the main one the clicked is working fine, but on the second account yesterday from nowhere (no updates, no filles change)  all the skills that were on Clicked stopped working. They are all there, all set up but they dont respond.

## General information
* **Clicked Version:** Clicked-0.11.1.zip
* **WoW Version:** Retail
* **Did it work before?** Yes, 2 days ago.
## Expected behavior
Nothing is working on the second account.

## Screenshots
![image](https://user-images.githubusercontent.com/62766929/99845612-b2fae880-2b53-11eb-913d-11fcdc9ec45d.png)
![image](https://user-images.githubusercontent.com/62766929/99845626-b8583300-2b53-11eb-8946-a278caa375bb.png)
![image](https://user-images.githubusercontent.com/62766929/99845668-ca39d600-2b53-11eb-9fc3-3a646e6d25d3.png)
![image](https://user-images.githubusercontent.com/62766929/99845679-cf972080-2b53-11eb-866a-4221e29dfd21.png)
![image](https://user-images.githubusercontent.com/62766929/99845699-d58d0180-2b53-11eb-8109-a223af907acb.png)
![image](https://user-images.githubusercontent.com/62766929/99845711-d9208880-2b53-11eb-835a-32a09807a4c6.png)

**Comment by Snakybo** [comment]
Can you type `/clicked dump` in the chat and post the contents of that window here?

**Comment by Alctroz** [comment]
Version: 0.11.1
Race: Troll
Level: 50
Class: DRUID
Specialization: 105
Talents: 1/3 2/3 3/1 4/3 5/2 6/2 7/1
Mode: AnyUp

Possess Bar: disabled
Vehicle: disabled
Vehicle UI: disabled
Pet Battle: disabled

----- Loaded binding 1 -----
Keybind: `
Hovercast: false
Action: macro
Identifier: clicked-button-`

/stopcasting
/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,exists,form:0] Wild Charge; [@target,exists,form:0] Wild Charge; Wild Charge

----- Loaded binding 2 -----
Keybind: SHIFT-6
Hovercast: false
Action: macro
Identifier: clicked-button-shift6

/click ClickedStopCastingButton
/use Dash

----- Loaded binding 3 -----
Keybind: E
Hovercast: false
Action: macro
Identifier: clicked-button-e

/click ClickedStopCastingButton
/cast [@mouseover,help,nodead] Wild Growth; [form:2] Rake; [form:4] Sunfire; [@player] Wild Growth

----- Loaded binding 4 -----
Keybind: G
Hovercast: false
Action: macro
Identifier: clicked-button-g

/click ClickedStopCastingButton
/castsequence [combat] Healthstone, Healing Potion, Healing Potion

----- Loaded binding 5 -----
Keybind: F
Hovercast: false
Action: macro
Identifier: clicked-button-f

/click ClickedStopCastingButton
/use [@mouseover,help][@target,nodead][@player] Heart Essence

----- Loaded binding 6 -----
Keybind: SHIFT-]
Hovercast: false
Action: macro
Identifier: clicked-button-shift]

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Revive; [@target,help,nodead] Revive; [@player] Revive

----- Loaded binding 7 -----
Keybind: SHIFT-8
Hovercast: false
Action: macro
Identifier: clicked-button-shift8

/click ClickedStopCastingButton
/use Stampeding Roar

----- Loaded binding 8 -----
Keybind: SHIFT-7
Hovercast: false
Action: macro
Identifier: clicked-button-shift7

/stopcasting
/click ClickedStopCastingButton
/use Prowl

----- Loaded binding 9 -----
Keybind: Q
Hovercast: false
Action: macro
Identifier: clicked-button-q

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Cenarion Ward; [@target,help,nodead] Cenarion Ward; [@player] Cenarion Ward

----- Loaded binding 10 -----
Keybind: SHIFT-MOUSEWHEELUP
Hovercast: false
Action: macro
Identifier: clicked-button-shiftmousewheelup

/click ClickedStopCastingButton
/use 14

----- Loaded binding 11 -----
Keybind: 3
Hovercast: false
Action: macro
Identifier: clicked-button-3

/click ClickedStopCastingButton
/cast [@mouseover,help,nodead] Lifebloom; [form:2] Swipe ; [form:4] Wrath; [@player] Lifebloom

----- Loaded binding 12 -----
Keybind: 5
Hovercast: false
Action: macro
Identifier: clicked-button-5

/click ClickedStopCastingButton
/cast [@mouseover,help,nodead] Regrowth; [form:2] Ferocious Bite; [form:4] Starsurge; [@player] Regrowth

----- Loaded binding 13 -----
Keybind: 4
Hovercast: false
Action: macro
Identifier: clicked-button-4

/click ClickedStopCastingButton
/cast [@mouseover,help,nodead] Rejuvenation; [form:2] Shred; [form:4] Starfire; [@player] Rejuvenation

----- Loaded binding 14 -----
Keybind: V
Hovercast: false
Action: macro
Identifier: clicked-button-v

/click ClickedStopCastingButton
/use Typhoon

----- Loaded binding 15 -----
Keybind: SHIFT-Q
Hovercast: false
Action: macro
Identifier: clicked-button-shiftq

/click ClickedStopCastingButton
/use Efflorescence

----- Loaded binding 16 -----
Keybind: ;
Hovercast: false
Action: macro
Identifier: clicked-button-;

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Innervate; [@target,help,nodead] Innervate; [@player] Innervate

----- Loaded binding 17 -----
Keybind: SHIFT-[
Hovercast: false
Action: macro
Identifier: clicked-button-shift[

/click ClickedStopCastingButton
/use Revitalize

----- Loaded binding 18 -----
Keybind: SHIFT-E
Hovercast: false
Action: macro
Identifier: clicked-button-shifte

/click ClickedStopCastingButton
/cast [@mouseover,help,nodead] Swiftmend; [form:2] Rip; [form:4] ; [@player] Swiftmend

----- Loaded binding 19 -----
Keybind: SHIFT-MOUSEWHEELDOWN
Hovercast: false
Action: macro
Identifier: clicked-button-shiftmousewheeldown

/click ClickedStopCastingButton
/cancelform

----- Loaded binding 20 -----
Keybind: BUTTON3
Hovercast: true
Action: macro
Identifier: 3

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Nature's Cure

----- Loaded binding 21 -----
Keybind: BUTTON3
Hovercast: false
Action: macro
Identifier: clicked-mouse-3

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Nature's Cure; [@target,help,nodead] Nature's Cure; [@player] Nature's Cure

----- Macro Handler Attributes -----
macrotext-clicked-button-shift8: /click ClickedStopCastingButton
macrotext-clicked-button-shift8: /use Stampeding Roar
macrotext-clicked-button-shift]: /click ClickedStopCastingButton
macrotext-clicked-button-shift]: /use [@mouseover,help,nodead] Revive; [@target,help,nodead] Revive; [@player] Revive
type-clicked-button-3: macro
macrotext-clicked-button-shiftmousewheeldown: /click ClickedStopCastingButton
macrotext-clicked-button-shiftmousewheeldown: /cancelform
macrotext-clicked-button-f: /click ClickedStopCastingButton
macrotext-clicked-button-f: /use [@mouseover,help][@target,nodead][@player] Heart Essence
type-clicked-button-shift]: macro
type-clicked-button-g: macro
macrotext-clicked-button-shift7: /stopcasting
macrotext-clicked-button-shift7: /click ClickedStopCastingButton
macrotext-clicked-button-shift7: /use Prowl
type-clicked-button-shiftmousewheelup: macro
macrotext-clicked-button-shiftmousewheelup: /click ClickedStopCastingButton
macrotext-clicked-button-shiftmousewheelup: /use 14
type-clicked-button-q: macro
macrotext-clicked-button-`: /stopcasting
macrotext-clicked-button-`: /startattack [@target,harm]
macrotext-clicked-button-`: /click ClickedStopCastingButton
macrotext-clicked-button-`: /use [@mouseover,exists,form:0] Wild Charge; [@target,exists,form:0] Wild Charge; Wild Charge
macrotext-clicked-button-e: /click ClickedStopCastingButton
macrotext-clicked-button-e: /cast [@mouseover,help,nodead] Wild Growth; [form:2] Rake; [form:4] Sunfire; [@player] Wild Growth
type-clicked-button-`: macro
type-clicked-button-4: macro
type-clicked-button-f: macro
type-clicked-button-;: macro
type-clicked-mouse-3: macro
type-clicked-button-shift8: macro
macrotext-clicked-button-5: /click ClickedStopCastingButton
macrotext-clicked-button-5: /cast [@mouseover,help,nodead] Regrowth; [form:2] Ferocious Bite; [form:4] Starsurge; [@player] Regrowth
macrotext-clicked-button-3: /click ClickedStopCastingButton
macrotext-clicked-button-3: /cast [@mouseover,help,nodead] Lifebloom; [form:2] Swipe ; [form:4] Wrath; [@player] Lifebloom
type-clicked-button-e: macro
type-clicked-button-shift[: macro
macrotext-clicked-button-shiftq: /click ClickedStopCastingButton
macrotext-clicked-button-shiftq: /use Efflorescence
macrotext-clicked-mouse-3: /click ClickedStopCastingButton
macrotext-clicked-mouse-3: /use [@mouseover,help,nodead] Nature's Cure; [@target,help,nodead] Nature's Cure; [@player] Nature's Cure
type-clicked-button-shiftmousewheeldown: macro
macrotext-clicked-button-shifte: /click ClickedStopCastingButton
macrotext-clicked-button-shifte: /cast [@mouseover,help,nodead] Swiftmend; [form:2] Rip; [form:4] ; [@player] Swiftmend
macrotext-clicked-button-v: /click ClickedStopCastingButton
macrotext-clicked-button-v: /use Typhoon
macrotext-clicked-button-shift[: /click ClickedStopCastingButton
macrotext-clicked-button-shift[: /use Revitalize
type-clicked-button-shift6: macro
type-clicked-button-shiftq: macro
type-clicked-button-v: macro
macrotext-clicked-button-;: /click ClickedStopCastingButton
macrotext-clicked-button-;: /use [@mouseover,help,nodead] Innervate; [@target,help,nodead] Innervate; [@player] Innervate
macrotext-clicked-button-q: /click ClickedStopCastingButton
macrotext-clicked-button-q: /use [@mouseover,help,nodead] Cenarion Ward; [@target,help,nodead] Cenarion Ward; [@player] Cenarion Ward
type-clicked-button-shifte: macro
type-clicked-button-5: macro
type-clicked-button-shift7: macro
macrotext-clicked-button-4: /click ClickedStopCastingButton
macrotext-clicked-button-4: /cast [@mouseover,help,nodead] Rejuvenation; [form:2] Shred; [form:4] Starfire; [@player] Rejuvenation
macrotext-clicked-button-shift6: /click ClickedStopCastingButton
macrotext-clicked-button-shift6: /use Dash
macrotext-clicked-button-g: /click ClickedStopCastingButton
macrotext-clicked-button-g: /castsequence [combat] Healthstone, Healing Potion, Healing Potion

----- Hovercast Attributes -----
type3: macro
macrotext3: /click ClickedStopCastingButton
macrotext3: /use [@mouseover,help,nodead] Nature's Cure

----- Registered unit frames -----
ElvUF_Boss5
ElvUF_Raid40Group1UnitButton4
ElvUF_PartyGroup1UnitButton3Pet
ElvUF_Raid40Group1UnitButton3
ElvUF_Raid40Group4UnitButton3
ElvUF_Raid40Group4UnitButton2
ElvUF_PartyGroup1UnitButton2Target
ElvUF_Raid40Group2UnitButton1
ElvUF_TankUnitButton1Target
ElvUF_PartyGroup1UnitButton5Target
ElvUF_Arena5
ElvUF_RaidGroup2UnitButton5
ElvUF_TankUnitButton1
ElvUF_RaidGroup6UnitButton5
ElvUF_AssistUnitButton1Target
ElvUF_RaidGroup6UnitButton3
ElvUF_RaidGroup6UnitButton2
ElvUF_Boss3
ElvUF_PartyGroup1UnitButton6Pet
ElvUF_PartyGroup1UnitButton4Target
ElvUF_RaidpetGroup1UnitButton4
ElvUF_RaidGroup5UnitButton5
ElvUF_AssistUnitButton1
ElvUF_Raid40Group8UnitButton2
ElvUF_RaidGroup5UnitButton4
ElvUF_Raid40Group6UnitButton3
ElvUF_Arena2
ElvUF_RaidGroup3UnitButton2
ElvUF_TargetTarget
ElvUF_RaidGroup5UnitButton3
ElvUF_RaidGroup5UnitButton2
ElvUF_Arena4
ElvUF_RaidpetGroup1UnitButton2
ElvUF_RaidGroup4UnitButton4
ElvUF_RaidGroup2UnitButton2
ElvUF_RaidGroup4UnitButton5
ElvUF_Raid40Group1UnitButton6
ElvUF_Raid40Group5UnitButton5
ElvUF_RaidGroup4UnitButton2
ElvUF_Raid40Group1UnitButton5
ElvUF_Raid40Group8UnitButton4
ElvUF_PartyGroup1UnitButton1
ElvUF_RaidGroup3UnitButton5
ElvUF_PartyGroup1UnitButton3
ElvUF_Raid40Group5UnitButton3
ElvUF_Boss2
ElvUF_Arena1
ElvUF_RaidGroup2UnitButton4
ElvUF_Focus
ElvUF_RaidpetGroup2UnitButton5
ElvUF_Raid40Group4UnitButton4
ElvUF_RaidGroup1UnitButton4
ElvUF_Arena3
ElvUF_PartyGroup1UnitButton2Pet
ElvUF_RaidGroup1UnitButton3
ElvUF_RaidGroup1UnitButton2
ElvUF_Raid40Group5UnitButton2
ElvUF_RaidGroup6UnitButton1
ElvUF_PartyGroup1UnitButton4
ElvUF_Raid40Group2UnitButton5
ElvUF_RaidGroup4UnitButton1
ElvUF_Raid40Group7UnitButton5
ElvUF_Raid40Group2UnitButton4
ElvUF_Raid40Group6UnitButton5
ElvUF_RaidGroup3UnitButton1
ElvUF_Raid40Group2UnitButton3
ElvUF_PartyGroup1UnitButton4Pet
ElvUF_RaidGroup2UnitButton1
ElvUF_Raid40Group2UnitButton2
ElvUF_Boss4
ElvUF_RaidGroup1UnitButton5
ElvUF_Raid40Group6UnitButton2
ElvUF_Target
ElvUF_RaidGroup6UnitButton4
ElvUF_PartyGroup1UnitButton1Target
ElvUF_Raid40Group3UnitButton2
ElvUF_PartyGroup1UnitButton3Target
ElvUF_RaidGroup1UnitButton6
ElvUF_Raid40Group8UnitButton5
ElvUF_FocusTarget
ElvUF_RaidpetGroup2UnitButton4
ElvUF_RaidpetGroup2UnitButton3
ElvUF_PetTarget
ElvUF_Raid40Group5UnitButton1
ElvUF_Raid40Group3UnitButton3
ElvUF_Player
ElvUF_RaidpetGroup1UnitButton5
ElvUF_RaidpetGroup1UnitButton3
ElvUF_RaidGroup4UnitButton3
ElvUF_RaidpetGroup2UnitButton1
ElvUF_PartyGroup1UnitButton5Pet
ElvUF_Raid40Group7UnitButton3
ElvUF_RaidGroup3UnitButton4
ElvUF_Raid40Group4UnitButton1
ElvUF_Raid40Group7UnitButton4
ElvUF_Raid40Group6UnitButton4
ElvUF_Raid40Group7UnitButton1
ElvUF_Raid40Group7UnitButton2
ElvUF_PartyGroup1UnitButton6Target
ElvUF_PartyGroup1UnitButton1Pet
ElvUF_PartyGroup1UnitButton2
ElvUF_Raid40Group5UnitButton4
ElvUF_Pet
ElvUF_PartyGroup1UnitButton5
ElvUF_RaidGroup3UnitButton3
ElvUF_TargetTargetTarget
ElvUF_Boss1
ElvUF_Raid40Group8UnitButton1
ElvUF_RaidGroup5UnitButton1
ElvUF_Raid40Group1UnitButton2
ElvUF_RaidGroup1UnitButton1
ElvUF_RaidGroup2UnitButton3
ElvUF_RaidpetGroup2UnitButton2
ElvUF_Raid40Group3UnitButton5
ElvUF_RaidpetGroup1UnitButton1
ElvUF_PartyGroup1UnitButton6
ElvUF_Raid40Group3UnitButton4
ElvUF_Raid40Group3UnitButton1
ElvUF_Raid40Group8UnitButton3
ElvUF_Raid40Group6UnitButton1
ElvUF_Raid40Group4UnitButton5
ElvUF_Raid40Group1UnitButton1
PlayerFrame
PetFrame
TargetFrame
TargetFrameToT
FocusFrame
FocusFrameToT
PartyMemberFrame1
PartyMemberFrame1PetFrame
PartyMemberFrame2
PartyMemberFrame2PetFrame
PartyMemberFrame3
PartyMemberFrame3PetFrame
PartyMemberFrame4
PartyMemberFrame4PetFrame
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
CompactRaidFrame1Buff1
CompactRaidFrame1Debuff1
CompactRaidFrame1DispelDebuff1
CompactRaidFrame1Buff2
CompactRaidFrame1Debuff2
CompactRaidFrame1DispelDebuff2
CompactRaidFrame1Buff3
CompactRaidFrame1Debuff3
CompactRaidFrame1DispelDebuff3
CompactRaidFrame1
CompactRaidFrame2Buff1
CompactRaidFrame2Debuff1
CompactRaidFrame2DispelDebuff1
CompactRaidFrame2Buff2
CompactRaidFrame2Debuff2
CompactRaidFrame2DispelDebuff2
CompactRaidFrame2Buff3
CompactRaidFrame2Debuff3
CompactRaidFrame2DispelDebuff3
CompactRaidFrame2

**Comment by Alctroz** [comment]
There is nothing into it

**Comment by Alctroz** [comment]
![image](https://user-images.githubusercontent.com/62766929/99851666-34577880-2b5e-11eb-8099-544af521f0b9.png)

**Comment by Alctroz** [comment]
On the main account is showing a lot of text into that command, on the one that isnt working, nothing is showing

**Comment by Snakybo** [comment]
Woah that's interesting. Can you type `/console scriptErrors 1` and then `/reload` or relog? Does a Lua Error window pop up by any chance?

**Comment by Alctroz** [comment]
Nothing happen, do u wanna come to the discord so I can stream it for u?

**Comment by Alctroz** [comment]
What should I do to fix it? t-t

**Comment by Snakybo** [comment]
Can you try installing these two addons and see if a window with an error shows up?
* https://www.curseforge.com/wow/addons/bug-grabber
* https://www.curseforge.com/wow/addons/bugsack

Additionally, though I don't think it will solve anything, try re-installing Clicked and creating a new profile on the account that doesn't work (`/cc profile`) and check if that _does_ work. If it does please send the `Clicked.lua` file in your `WTF/Account/SECONDARY_ACCOUNT/SavedVariables/Clicked.lua` (the number in the account folder will correspond with what it says in the launcher (WOW1, WOW3, WOW5, etc, so if your secondary account is listed as WOW3 then `some number#3` will be the right folder)

**Comment by Snakybo** [comment]
Also, please try disabling all other addons and see if it still won't work.

**Comment by Alctroz** [comment]
Just woke up, I'm trying first to turn off all addons.

The lua error showed up: 
**Page 1:**
Message: Interface\AddOns\Clicked\Core\Utils.lua:256: bad argument #1 to 'match' (string expected, got nil)
Time: Sat Nov 21 16:54:56 2020
Count: 1
Stack: Interface\AddOns\Clicked\Core\Utils.lua:256: bad argument #1 to 'match' (string expected, got nil)
[string "=[C]"]: in function `match'
[string "@Interface\AddOns\Clicked\Core\Utils.lua"]:256: in function `CreateAttributeIdentifier'
[string "@Interface\AddOns\Clicked\Core\BindingProcessor.lua"]:492: in function `Process'
[string "@Interface\AddOns\Clicked\Core\BindingProcessor.lua"]:510: in function <Interface\AddOns\Clicked\Core\BindingProcessor.lua:474>
[string "@Interface\AddOns\Clicked\Core\BindingProcessor.lua"]:600: in function `ReloadActiveBindings'
[string "@Interface\AddOns\Clicked\Core\Clicked.lua"]:69: in function <Interface\AddOns\Clicked\Core\Clicked.lua:65>
[string "=[C]"]: ?
[string "@Interface\AddOns\Clicked\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ked\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Clicked\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Clicked\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ce\AddOns\Clicked\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Page 2:**
Message: Interface\AddOns\Clicked\Core\Utils.lua:256: bad argument #1 to 'match' (string expected, got nil)
Time: Sat Nov 21 16:55:27 2020
Count: 3
Stack: Interface\AddOns\Clicked\Core\Utils.lua:256: bad argument #1 to 'match' (string expected, got nil)
[string "=[C]"]: in function `match'
[string "@Interface\AddOns\Clicked\Core\Utils.lua"]:256: in function `CreateAttributeIdentifier'
[string "@Interface\AddOns\Clicked\Core\BindingProcessor.lua"]:492: in function `Process'
[string "@Interface\AddOns\Clicked\Core\BindingProcessor.lua"]:510: in function <Interface\AddOns\Clicked\Core\BindingProcessor.lua:474>
[string "@Interface\AddOns\Clicked\Core\BindingProcessor.lua"]:600: in function `?'
[string "@Interface\AddOns\Clicked\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ked\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Clicked\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ked\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Clicked\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Clicked\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ce\AddOns\Clicked\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Alctroz** [comment]
[Clicked.lua.zip](https://github.com/Snakybo/Clicked/files/5578294/Clicked.lua.zip)

**Comment by Snakybo** [comment]
That's incredibly useful, thanks! I'll look at it right now, will let you know in a bit

**Comment by Alctroz** [comment]
Cheering for u! <3

**Comment by Snakybo** [comment]
Okay, so the issue here is that it seems like the `-` key breaks it, I'll work on fixing that, but if you want to quickly get it working again you should be able to rebind Rebirth to another key until that's fixed

**Comment by Alctroz** [comment]
Hmm.. the problem is only Rebirth? I tried but looks like none of the skills set on Clicked ( on the second account is working).
On my main account is also a druid, with the same spell in the same keybinds D:

**Comment by Snakybo** [comment]
If I rebind Rebirth from `-` to `=` it works fine without any errors, as do all other bindings:
![image](https://user-images.githubusercontent.com/3172140/99887232-f4b68c80-2c42-11eb-815c-3faf4b877d36.png)

I will work on a fix in the meantime

**Comment by Alctroz** [comment]
Hmmmm, it worked.
Nice, ty so much sr. I'll tyr to counter that error putting the rebirth on normal macro!

Ty so much for the attention
