### ISSUE TITLE
Healer Binding not working for DoTs

### ISSUE THREAD

**Issue by AdrianDutu** [Snakybo/Clicked#31]
## Describe the bug
I want to set up a Healing Binding for the Shadow Priest's DoTs. Basically put it on mouseover, then target. 
How I set it up:
1. Action panel: Cast a spell, select the spell from spellbook and bind it
2. Targets panel: 
 - Unit frame target: Hostile, Alive
 - Binding Targets: Target, Hostile, Alive OR No One
3. Conditions panel: Class Priest
4. Status: Nothing modified there

This does not apply the DoTs on mouseover It does however put it on target. I tried all the DoTs: Vampiric Touch, Shadow Word: Pain or Devouring Plague.

## General information
* **Clicked Version:** 0.11.2
* **WoW Version:** Retail
* **Did it work before?** I didn't tried it before.
* **Does it occur with all other addons disabled?** Yes

## Expected behavior
Put dots on mouseover target, then targeted target.

## Reproduction
1. Setup the binding as described above.
2. Try it with mouseover

## Screenshots

![1](https://user-images.githubusercontent.com/4824201/100594550-1cb88680-32fa-11eb-8d84-54368cf5f22d.PNG)
![2](https://user-images.githubusercontent.com/4824201/100594553-1d511d00-32fa-11eb-8734-b8adf62475ac.PNG)
![3](https://user-images.githubusercontent.com/4824201/100594556-1d511d00-32fa-11eb-8235-d405cd361c9e.PNG)
![4](https://user-images.githubusercontent.com/4824201/100594557-1de9b380-32fa-11eb-91be-d4643ee62e83.PNG)

**Comment by Snakybo** [comment]
Do you want to apply it by mouseover on 3D units in the world, or just by hovering over their unit frame? The setup you've posted works fine for me: I can apply VT by hovering over a target/boss/focus frame or by just targeting someone.

If you want to be able to also select targets by hovering over them in the world try adding the Mouseover target before Target:
![image](https://user-images.githubusercontent.com/3172140/100643975-0252cd00-333b-11eb-8c1d-1191f7e1b08e.png)

Let me know if that helps

**Comment by AdrianDutu** [comment]
Oh, this is what I was looking for. Thank you!

**Comment by AdrianDutu** [comment]
@Snakybo I'll ask here since it's not really an issue, but how exactly do custom macros work?
For example I want to set up something like always cast Power Infusion before Void Eruption if Power Infusion is not on CD.
Can I do that with the custom macros?

Do I need to put a blizz like macro in the macro text (like /cast Power Infusion) and then select Run Last? But where do I specify what to run after?

**Comment by Snakybo** [comment]
Custom macros basically allow you to just that, they're indeed just regular Blizz macros so `/cast Power Infusion` will do the trick. The run first/run last options are in reference to the auto-generated binding macros. So if you have a binding for Void Eruption/Void Bolt and then create another binding on the same key that is a custom macro you can make that run before or after the Void Eruption cast.

For what you're describing you probably want to use run fist, you can also see what it generates on the "Status" page of the binding when it's loaded.

I am looking to add some more customization with combining multiple casts on the same key so you should be able to achieve this without creating a custom macro sometime soon™.
