### ISSUE TITLE
Selecting multiple specs for loading

### ISSUE THREAD

**Issue by AdrianDutu** [Snakybo/Clicked#32]
## Is your feature request related to a problem?
No.

## Describe the solution you'd like
At the moment, when selecting a talent specialization under load conditions, you can choose only one. But there are situations where you want to choose more than one, but not all the specs available.
For example: Shadow Mend is a spell available to Shadow Priest and Disc Priest but not Holy Priest.
It would be good to be able to select both Shadow and Disc as specs that will load this Binding.

## Describe alternatives you've considered
I can see this working only by duplicating the same binding but changing the loading spec.

**Comment by Snakybo** [comment]
You can click on the checkbox twice (it turns gray) to enable multi-selection in the dropdown
