### ISSUE TITLE
No binds working on when in air.

### ISSUE THREAD

**Issue by twin2** [Snakybo/Clicked#33]
## Describe the bug
Doing a quest called air supremacy is one example where it happens.(https://shadowlands.wowhead.com/quest=60929/air-supremacy)

When i use my spear and mount the mob in the sky. none of my keybinds work.

This issue also happens for me in the maw when i get picked up by the tier4 elite assasin.(not sure of name on top of my head sorry.)

## General information
[0.11.2]
* **WoW Version:** Retail
* **Did it work before?**  Not sure, never had the situation happen.
* **Does it occur with all other addons disabled?** No

## Reproduction
Not sure what the easiest way to test it is. i guess the maw tier4?

**Comment by Snakybo** [comment]
Yep, I noticed that as well today. Will be fixed in the next update, thanks 👍
