### ISSUE TITLE
Vuhdo support

### ISSUE THREAD

**Issue by gunters63** [Snakybo/Clicked#35]
Clicked bindings do not work with Vuhdo . 
This is intended because Vuhdo has its own binding system out of the box.

Vuhdos binding system though can be disabled with a special Clique configuration setting.
Which worked fine for me with Clique.

I tried to use this Clique compatibility setting for Clicked, but it works unreliably. I did not find out yet what conditions trigger working/not working.

**Comment by gunters63** [comment]
I should have assigned label enhancement, it is clearly not a bug. How can I change a label on Github? :)

**Comment by Snakybo** [comment]
Hi! I don't use VuhDo myself, but I did briefly test it using that option to enable Clique compatibility and that seemed to work fine, so if it works unreliably it's definitely a bug.

If you can find a pattern or reproduction steps that break it I'll be sure to check it out

**Comment by gunters63** [comment]
Thanks for the feedback, I will try to find out :)

**Comment by Snakybo** [comment]
@gunters63 did you ever run into this issue again?

**Comment by gunters63** [comment]
Sorry, I have paused playing Classic currently :) (and are playing Retail).

But I think the issue can be reproduced easily.
Just load Vuhdo, activate the Clique compatibility mode (Options-General-Misc) and try to bind something with Clicked.
