### ISSUE TITLE
Mouse locking up

### ISSUE THREAD

**Issue by Esvi84** [Snakybo/Clicked#37]
While having healing spells bound to BUTTON1 und BUTTON2, so left and right mouse button, when ever I click right on the edge of the unit frame, my mouse disappears, locks up and does not let me use it until I reload my UI

## General information
* **Clicked Version:** 0.12.1
* **WoW Version:** Retail
* **Did it work before?** Never used the Addon before
* **Does it occur with all other addons disabled?** Yes

## Expected behavior
Casting the Spell I bound to the mouse button

## Reproduction
1. Bind healing spell to mouse button 1 or 2
2. Click on edge of unitframe

## Screenshot
![f37a5c4e0c7d21a6629862a7956bf65c](https://user-images.githubusercontent.com/75613578/101339595-f0af7f00-387e-11eb-9d01-a5f622684fc1.png)
](url)

## Dump
Version: 0.12.1
Race: Orc
Level: 60
Class: SHAMAN
Specialization: 264
Talents: 1/2 2/1 3/1 4/1 5/1 6/3 7/3
Mode: AnyDown

Possess Bar: disabled
Override Bar: disabled
Vehicle: disabled
Vehicle UI: disabled
Pet Battle: disabled

----- Loaded binding 1 -----
Keybind: SHIFT-R
Hovercast: true
Action: macro
Identifier: clicked-button-shiftr

/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Wind Shear

----- Loaded binding 2 -----
Keybind: C
Hovercast: true
Action: macro
Identifier: clicked-button-c

/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Hex

----- Loaded binding 3 -----
Keybind: SHIFT-C
Hovercast: true
Action: macro
Identifier: clicked-button-shiftc

/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Hex

----- Loaded binding 4 -----
Keybind: F
Hovercast: true
Action: macro
Identifier: clicked-button-f

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Chain Heal

----- Loaded binding 5 -----
Keybind: H
Hovercast: true
Action: macro
Identifier: clicked-button-h

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Water Walking

----- Loaded binding 6 -----
Keybind: ALT-T
Hovercast: true
Action: macro
Identifier: clicked-button-altt

/click ClickedStopCastingButton
/use [@mouseover,help,dead] Ancestral Spirit

----- Loaded binding 7 -----
Keybind: CTRL-BUTTON1
Hovercast: true
Action: target
Identifier: 1

----- Loaded binding 8 -----
Keybind: MOUSEWHEELUP
Hovercast: true
Action: macro
Identifier: clicked-button-mousewheelup

/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Purge

----- Loaded binding 9 -----
Keybind: F1
Hovercast: true
Action: macro
Identifier: clicked-button-f1

/click ClickedStopCastingButton
/script SetRaidTarget("target",8)

----- Loaded binding 10 -----
Keybind: 3
Hovercast: true
Action: macro
Identifier: clicked-button-3

/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Frost Shock

----- Loaded binding 11 -----
Keybind: F3
Hovercast: true
Action: macro
Identifier: clicked-button-f3

/click ClickedStopCastingButton
/script SetRaidTarget("target",1)

----- Loaded binding 12 -----
Keybind: F4
Hovercast: true
Action: macro
Identifier: clicked-button-f4

/click ClickedStopCastingButton
/script SetRaidTarget("target",2)

----- Loaded binding 13 -----
Keybind: BUTTON4
Hovercast: true
Action: macro
Identifier: 4

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Healing Wave

----- Loaded binding 14 -----
Keybind: F2
Hovercast: true
Action: macro
Identifier: clicked-button-f2

/click ClickedStopCastingButton
/script SetRaidTarget("target",7)

----- Loaded binding 15 -----
Keybind: R
Hovercast: true
Action: macro
Identifier: clicked-button-r

/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Wind Shear

----- Loaded binding 16 -----
Keybind: SHIFT-S
Hovercast: true
Action: macro
Identifier: clicked-button-shifts

/click ClickedStopCastingButton
/use [@mouseover,nodead] Primordial Wave

----- Loaded binding 17 -----
Keybind: BUTTON2
Hovercast: true
Action: macro
Identifier: 2

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Healing Surge

----- Loaded binding 18 -----
Keybind: SHIFT-BUTTON1
Hovercast: true
Action: macro
Identifier: 1

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Healing Wave

----- Loaded binding 19 -----
Keybind: BUTTON1
Hovercast: true
Action: macro
Identifier: 1

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Riptide

----- Loaded binding 20 -----
Keybind: CTRL-BUTTON2
Hovercast: true
Action: menu
Identifier: 2

----- Loaded binding 21 -----
Keybind: SHIFT-BUTTON2
Hovercast: true
Action: macro
Identifier: 2

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Earth Shield

----- Loaded binding 22 -----
Keybind: MOUSEWHEELDOWN
Hovercast: true
Action: macro
Identifier: clicked-button-mousewheeldown

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Purify Spirit

----- Loaded binding 23 -----
Keybind: SHIFT-R
Hovercast: false
Action: macro
Identifier: clicked-button-shiftr

/click ClickedStopCastingButton
/use [@focus,harm,nodead] Wind Shear

----- Loaded binding 24 -----
Keybind: C
Hovercast: false
Action: macro
Identifier: clicked-button-c

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Hex; [@target,harm,nodead] Hex

----- Loaded binding 25 -----
Keybind: SHIFT-C
Hovercast: false
Action: macro
Identifier: clicked-button-shiftc

/click ClickedStopCastingButton
/use [@focus,harm,nodead] Hex

----- Loaded binding 26 -----
Keybind: F
Hovercast: false
Action: macro
Identifier: clicked-button-f

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Chain Heal; [@target,help,nodead] Chain Heal; [@player] Chain Heal

----- Loaded binding 27 -----
Keybind: H
Hovercast: false
Action: macro
Identifier: clicked-button-h

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Water Walking; [@target,help,nodead] Water Walking; [@player] Water Walking

----- Loaded binding 28 -----
Keybind: ALT-T
Hovercast: false
Action: macro
Identifier: clicked-button-altt

/click ClickedStopCastingButton
/use [@mouseover,help,dead] Ancestral Spirit; [@target,help,dead] Ancestral Spirit

----- Loaded binding 29 -----
Keybind: MOUSEWHEELUP
Hovercast: false
Action: macro
Identifier: clicked-button-mousewheelup

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Purge; [@target,harm,nodead] Purge; [@player] Purge

----- Loaded binding 30 -----
Keybind: F1
Hovercast: false
Action: macro
Identifier: clicked-button-f1

/click ClickedStopCastingButton
/script SetRaidTarget("target",8)

----- Loaded binding 31 -----
Keybind: 3
Hovercast: false
Action: macro
Identifier: clicked-button-3

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,harm,nodead] Frost Shock; [@target,harm,nodead] Frost Shock

----- Loaded binding 32 -----
Keybind: SHIFT-<
Hovercast: false
Action: macro
Identifier: clicked-button-shift<

/click ClickedStopCastingButton
/use Flametongue Weapon

----- Loaded binding 33 -----
Keybind: F4
Hovercast: false
Action: macro
Identifier: clicked-button-f4

/click ClickedStopCastingButton
/script SetRaidTarget("target",2)

----- Loaded binding 34 -----
Keybind: BUTTON4
Hovercast: false
Action: macro
Identifier: clicked-mouse-4

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Healing Wave; [@target,help,nodead] Healing Wave; [@player] Healing Wave

----- Loaded binding 35 -----
Keybind: ALT-<
Hovercast: false
Action: macro
Identifier: clicked-button-alt<

/click ClickedStopCastingButton
/use Windfury Weapon

----- Loaded binding 36 -----
Keybind: F2
Hovercast: false
Action: macro
Identifier: clicked-button-f2

/click ClickedStopCastingButton
/script SetRaidTarget("target",7)

----- Loaded binding 37 -----
Keybind: SHIFT-S
Hovercast: false
Action: macro
Identifier: clicked-button-shifts

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Primordial Wave; [@target,harm,nodead] Primordial Wave; [@player] Primordial Wave

----- Loaded binding 38 -----
Keybind: F3
Hovercast: false
Action: macro
Identifier: clicked-button-f3

/click ClickedStopCastingButton
/script SetRaidTarget("target",1)

----- Loaded binding 39 -----
Keybind: SHIFT-BUTTON1
Hovercast: false
Action: macro
Identifier: clicked-mouse-shift1

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Healing Wave; [@target,help,nodead] Healing Wave; [@player] Healing Wave

----- Loaded binding 40 -----
Keybind: R
Hovercast: false
Action: macro
Identifier: clicked-button-r

/startattack [@target,harm]
/click ClickedStopCastingButton
/use [@target,harm,nodead] Wind Shear

----- Loaded binding 41 -----
Keybind: MOUSEWHEELDOWN
Hovercast: false
Action: macro
Identifier: clicked-button-mousewheeldown

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Purify Spirit; [@target,help,nodead] Purify Spirit; [@player] Purify Spirit

----- Loaded binding 42 -----
Keybind: SHIFT-BUTTON2
Hovercast: false
Action: macro
Identifier: clicked-mouse-shift2

/click ClickedStopCastingButton
/use [@mouseover,help,nodead] Earth Shield; [@target,help,nodead] Earth Shield; [@player] Earth Shield

----- Loaded binding 43 -----
Keybind: SHIFT-3
Hovercast: false
Action: macro
Identifier: clicked-button-shift3

/click ClickedStopCastingButton
/use Earthbind Totem

----- Macro Handler Attributes -----
type-clicked-button-c: macro
macrotext-clicked-button-r: /startattack [@target,harm]
macrotext-clicked-button-r: /click ClickedStopCastingButton
macrotext-clicked-button-r: /use [@target,harm,nodead] Wind Shear
type-clicked-button-r: macro
macrotext-clicked-button-f4: /click ClickedStopCastingButton
macrotext-clicked-button-f4: /script SetRaidTarget("target",2)
macrotext-clicked-mouse-shift1: /click ClickedStopCastingButton
macrotext-clicked-mouse-shift1: /use [@mouseover,help,nodead] Healing Wave; [@target,help,nodead] Healing Wave; [@player] Healing Wave
type-clicked-button-3: macro
type-clicked-button-f2: macro
type-clicked-button-alt<: macro
type-clicked-mouse-shift1: macro
macrotext-clicked-button-shiftc: /click ClickedStopCastingButton
macrotext-clicked-button-shiftc: /use [@focus,harm,nodead] Hex
macrotext-clicked-button-f3: /click ClickedStopCastingButton
macrotext-clicked-button-f3: /script SetRaidTarget("target",1)
type-clicked-button-shift3: macro
type-clicked-button-f: macro
macrotext-clicked-button-shiftr: /click ClickedStopCastingButton
macrotext-clicked-button-shiftr: /use [@focus,harm,nodead] Wind Shear
type-clicked-button-shiftr: macro
macrotext-clicked-button-mousewheelup: /startattack [@target,harm]
macrotext-clicked-button-mousewheelup: /click ClickedStopCastingButton
macrotext-clicked-button-mousewheelup: /use [@mouseover,harm,nodead] Purge; [@target,harm,nodead] Purge; [@player] Purge
type-clicked-button-f3: macro
macrotext-clicked-button-shifts: /startattack [@target,harm]
macrotext-clicked-button-shifts: /click ClickedStopCastingButton
macrotext-clicked-button-shifts: /use [@mouseover,help,nodead] Primordial Wave; [@target,harm,nodead] Primordial Wave; [@player] Primordial Wave
macrotext-clicked-button-shift3: /click ClickedStopCastingButton
macrotext-clicked-button-shift3: /use Earthbind Totem
macrotext-clicked-button-3: /startattack [@target,harm]
macrotext-clicked-button-3: /click ClickedStopCastingButton
macrotext-clicked-button-3: /use [@mouseover,harm,nodead] Frost Shock; [@target,harm,nodead] Frost Shock
macrotext-clicked-button-altt: /click ClickedStopCastingButton
macrotext-clicked-button-altt: /use [@mouseover,help,dead] Ancestral Spirit; [@target,help,dead] Ancestral Spirit
macrotext-clicked-mouse-4: /click ClickedStopCastingButton
macrotext-clicked-mouse-4: /use [@mouseover,help,nodead] Healing Wave; [@target,help,nodead] Healing Wave; [@player] Healing Wave
type-clicked-mouse-shift2: macro
type-clicked-button-mousewheeldown: macro
macrotext-clicked-button-mousewheeldown: /click ClickedStopCastingButton
macrotext-clicked-button-mousewheeldown: /use [@mouseover,help,nodead] Purify Spirit; [@target,help,nodead] Purify Spirit; [@player] Purify Spirit
type-clicked-button-mousewheelup: macro
type-clicked-button-h: macro
macrotext-clicked-button-f: /click ClickedStopCastingButton
macrotext-clicked-button-f: /use [@mouseover,help,nodead] Chain Heal; [@target,help,nodead] Chain Heal; [@player] Chain Heal
macrotext-clicked-button-h: /click ClickedStopCastingButton
macrotext-clicked-button-h: /use [@mouseover,help,nodead] Water Walking; [@target,help,nodead] Water Walking; [@player] Water Walking
type-clicked-button-f1: macro
type-clicked-button-f4: macro
type-clicked-button-shiftc: macro
type-clicked-button-shifts: macro
type-clicked-button-altt: macro
type-clicked-mouse-4: macro
type-clicked-button-shift<: macro
macrotext-clicked-mouse-shift2: /click ClickedStopCastingButton
macrotext-clicked-mouse-shift2: /use [@mouseover,help,nodead] Earth Shield; [@target,help,nodead] Earth Shield; [@player] Earth Shield
macrotext-clicked-button-f2: /click ClickedStopCastingButton
macrotext-clicked-button-f2: /script SetRaidTarget("target",7)
macrotext-clicked-button-shift<: /click ClickedStopCastingButton
macrotext-clicked-button-shift<: /use Flametongue Weapon
macrotext-clicked-button-f1: /click ClickedStopCastingButton
macrotext-clicked-button-f1: /script SetRaidTarget("target",8)
macrotext-clicked-button-c: /startattack [@target,harm]
macrotext-clicked-button-c: /click ClickedStopCastingButton
macrotext-clicked-button-c: /use [@mouseover,harm,nodead] Hex; [@target,harm,nodead] Hex
macrotext-clicked-button-alt<: /click ClickedStopCastingButton
macrotext-clicked-button-alt<: /use Windfury Weapon

----- Hovercast Attributes -----
type2: macro
shift-macrotext1: /click ClickedStopCastingButton
shift-macrotext1: /use [@mouseover,help,nodead] Healing Wave
ctrl-type2: menu
macrotext-clicked-button-r: /click ClickedStopCastingButton
macrotext-clicked-button-r: /use [@mouseover,harm,nodead] Wind Shear
type-clicked-button-r: macro
shift-type2: macro
type-clicked-button-f1: macro
macrotext1: /click ClickedStopCastingButton
macrotext1: /use [@mouseover,help,nodead] Riptide
type-clicked-button-3: macro
type-clicked-button-f2: macro
macrotext-clicked-button-f: /click ClickedStopCastingButton
macrotext-clicked-button-f: /use [@mouseover,help,nodead] Chain Heal
macrotext-clicked-button-shiftc: /click ClickedStopCastingButton
macrotext-clicked-button-shiftc: /use [@mouseover,harm,nodead] Hex
macrotext-clicked-button-f3: /click ClickedStopCastingButton
macrotext-clicked-button-f3: /script SetRaidTarget("target",1)
type-clicked-button-f: macro
macrotext-clicked-button-altt: /click ClickedStopCastingButton
macrotext-clicked-button-altt: /use [@mouseover,help,dead] Ancestral Spirit
type4: macro
macrotext-clicked-button-mousewheelup: /click ClickedStopCastingButton
macrotext-clicked-button-mousewheelup: /use [@mouseover,harm,nodead] Purge
macrotext4: /click ClickedStopCastingButton
macrotext4: /use [@mouseover,help,nodead] Healing Wave
macrotext-clicked-button-shifts: /click ClickedStopCastingButton
macrotext-clicked-button-shifts: /use [@mouseover,nodead] Primordial Wave
macrotext-clicked-button-3: /click ClickedStopCastingButton
macrotext-clicked-button-3: /use [@mouseover,harm,nodead] Frost Shock
type-clicked-button-mousewheeldown: macro
macrotext-clicked-button-mousewheeldown: /click ClickedStopCastingButton
macrotext-clicked-button-mousewheeldown: /use [@mouseover,help,nodead] Purify Spirit
macrotext-clicked-button-f4: /click ClickedStopCastingButton
macrotext-clicked-button-f4: /script SetRaidTarget("target",2)
type1: macro
macrotext-clicked-button-shiftr: /click ClickedStopCastingButton
macrotext-clicked-button-shiftr: /use [@mouseover,harm,nodead] Wind Shear
type-clicked-button-mousewheelup: macro
macrotext2: /click ClickedStopCastingButton
macrotext2: /use [@mouseover,help,nodead] Healing Surge
type-clicked-button-c: macro
type-clicked-button-altt: macro
type-clicked-button-h: macro
type-clicked-button-f4: macro
type-clicked-button-shiftr: macro
type-clicked-button-shifts: macro
type-clicked-button-f3: macro
ctrl-type1: target
type-clicked-button-shiftc: macro
shift-macrotext2: /click ClickedStopCastingButton
shift-macrotext2: /use [@mouseover,help,nodead] Earth Shield
macrotext-clicked-button-f2: /click ClickedStopCastingButton
macrotext-clicked-button-f2: /script SetRaidTarget("target",7)
macrotext-clicked-button-h: /click ClickedStopCastingButton
macrotext-clicked-button-h: /use [@mouseover,help,nodead] Water Walking
macrotext-clicked-button-f1: /click ClickedStopCastingButton
macrotext-clicked-button-f1: /script SetRaidTarget("target",8)
macrotext-clicked-button-c: /click ClickedStopCastingButton
macrotext-clicked-button-c: /use [@mouseover,harm,nodead] Hex
shift-type1: macro

----- Registered unit frames -----
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
CompactRaidFrame1
CompactRaidFrame1Buff1
CompactRaidFrame1Buff2
CompactRaidFrame1Buff3
CompactRaidFrame1Debuff1
CompactRaidFrame1Debuff2
CompactRaidFrame1Debuff3
CompactRaidFrame1DispelDebuff1
CompactRaidFrame1DispelDebuff2
CompactRaidFrame1DispelDebuff3
CompactRaidFrame2
CompactRaidFrame2Buff1
CompactRaidFrame2Buff2
CompactRaidFrame2Buff3
CompactRaidFrame2Debuff1
CompactRaidFrame2Debuff2
CompactRaidFrame2Debuff3
CompactRaidFrame2DispelDebuff1
CompactRaidFrame2DispelDebuff2
CompactRaidFrame2DispelDebuff3
ElvUF_Arena1
ElvUF_Arena2
ElvUF_Arena3
ElvUF_Arena4
ElvUF_Arena5
ElvUF_AssistUnitButton1
ElvUF_AssistUnitButton1
ElvUF_AssistUnitButton1Target
ElvUF_Boss1
ElvUF_Boss2
ElvUF_Boss3
ElvUF_Boss4
ElvUF_Boss5
ElvUF_Focus
ElvUF_FocusTarget
ElvUF_PartyGroup1UnitButton1
ElvUF_PartyGroup1UnitButton1
ElvUF_PartyGroup1UnitButton1Pet
ElvUF_PartyGroup1UnitButton1Target
ElvUF_PartyGroup1UnitButton2
ElvUF_PartyGroup1UnitButton2
ElvUF_PartyGroup1UnitButton2Pet
ElvUF_PartyGroup1UnitButton2Target
ElvUF_PartyGroup1UnitButton3
ElvUF_PartyGroup1UnitButton3
ElvUF_PartyGroup1UnitButton3Pet
ElvUF_PartyGroup1UnitButton3Target
ElvUF_PartyGroup1UnitButton4
ElvUF_PartyGroup1UnitButton4
ElvUF_PartyGroup1UnitButton4Pet
ElvUF_PartyGroup1UnitButton4Target
ElvUF_PartyGroup1UnitButton5
ElvUF_PartyGroup1UnitButton5
ElvUF_PartyGroup1UnitButton5Pet
ElvUF_PartyGroup1UnitButton5Target
ElvUF_PartyGroup1UnitButton6
ElvUF_PartyGroup1UnitButton6
ElvUF_PartyGroup1UnitButton6Pet
ElvUF_PartyGroup1UnitButton6Target
ElvUF_Pet
ElvUF_PetTarget
ElvUF_Player
ElvUF_Raid40Group1UnitButton1
ElvUF_Raid40Group1UnitButton1
ElvUF_Raid40Group1UnitButton2
ElvUF_Raid40Group1UnitButton2
ElvUF_Raid40Group1UnitButton3
ElvUF_Raid40Group1UnitButton3
ElvUF_Raid40Group1UnitButton4
ElvUF_Raid40Group1UnitButton4
ElvUF_Raid40Group1UnitButton5
ElvUF_Raid40Group1UnitButton5
ElvUF_Raid40Group1UnitButton6
ElvUF_Raid40Group1UnitButton6
ElvUF_Raid40Group2UnitButton1
ElvUF_Raid40Group2UnitButton1
ElvUF_Raid40Group2UnitButton2
ElvUF_Raid40Group2UnitButton2
ElvUF_Raid40Group2UnitButton3
ElvUF_Raid40Group2UnitButton3
ElvUF_Raid40Group2UnitButton4
ElvUF_Raid40Group2UnitButton4
ElvUF_Raid40Group2UnitButton5
ElvUF_Raid40Group2UnitButton5
ElvUF_Raid40Group3UnitButton1
ElvUF_Raid40Group3UnitButton1
ElvUF_Raid40Group3UnitButton2
ElvUF_Raid40Group3UnitButton2
ElvUF_Raid40Group3UnitButton3
ElvUF_Raid40Group3UnitButton3
ElvUF_Raid40Group3UnitButton4
ElvUF_Raid40Group3UnitButton4
ElvUF_Raid40Group3UnitButton5
ElvUF_Raid40Group3UnitButton5
ElvUF_Raid40Group4UnitButton1
ElvUF_Raid40Group4UnitButton1
ElvUF_Raid40Group4UnitButton2
ElvUF_Raid40Group4UnitButton2
ElvUF_Raid40Group4UnitButton3
ElvUF_Raid40Group4UnitButton3
ElvUF_Raid40Group4UnitButton4
ElvUF_Raid40Group4UnitButton4
ElvUF_Raid40Group4UnitButton5
ElvUF_Raid40Group4UnitButton5
ElvUF_Raid40Group5UnitButton1
ElvUF_Raid40Group5UnitButton1
ElvUF_Raid40Group5UnitButton2
ElvUF_Raid40Group5UnitButton2
ElvUF_Raid40Group5UnitButton3
ElvUF_Raid40Group5UnitButton3
ElvUF_Raid40Group5UnitButton4
ElvUF_Raid40Group5UnitButton4
ElvUF_Raid40Group5UnitButton5
ElvUF_Raid40Group5UnitButton5
ElvUF_Raid40Group6UnitButton1
ElvUF_Raid40Group6UnitButton1
ElvUF_Raid40Group6UnitButton2
ElvUF_Raid40Group6UnitButton2
ElvUF_Raid40Group6UnitButton3
ElvUF_Raid40Group6UnitButton3
ElvUF_Raid40Group6UnitButton4
ElvUF_Raid40Group6UnitButton4
ElvUF_Raid40Group6UnitButton5
ElvUF_Raid40Group6UnitButton5
ElvUF_Raid40Group7UnitButton1
ElvUF_Raid40Group7UnitButton1
ElvUF_Raid40Group7UnitButton2
ElvUF_Raid40Group7UnitButton2
ElvUF_Raid40Group7UnitButton3
ElvUF_Raid40Group7UnitButton3
ElvUF_Raid40Group7UnitButton4
ElvUF_Raid40Group7UnitButton4
ElvUF_Raid40Group7UnitButton5
ElvUF_Raid40Group7UnitButton5
ElvUF_Raid40Group8UnitButton1
ElvUF_Raid40Group8UnitButton1
ElvUF_Raid40Group8UnitButton2
ElvUF_Raid40Group8UnitButton2
ElvUF_Raid40Group8UnitButton3
ElvUF_Raid40Group8UnitButton3
ElvUF_Raid40Group8UnitButton4
ElvUF_Raid40Group8UnitButton4
ElvUF_Raid40Group8UnitButton5
ElvUF_Raid40Group8UnitButton5
ElvUF_RaidGroup1UnitButton1
ElvUF_RaidGroup1UnitButton1
ElvUF_RaidGroup1UnitButton2
ElvUF_RaidGroup1UnitButton2
ElvUF_RaidGroup1UnitButton3
ElvUF_RaidGroup1UnitButton3
ElvUF_RaidGroup1UnitButton4
ElvUF_RaidGroup1UnitButton4
ElvUF_RaidGroup1UnitButton5
ElvUF_RaidGroup1UnitButton5
ElvUF_RaidGroup1UnitButton6
ElvUF_RaidGroup1UnitButton6
ElvUF_RaidGroup2UnitButton1
ElvUF_RaidGroup2UnitButton1
ElvUF_RaidGroup2UnitButton2
ElvUF_RaidGroup2UnitButton2
ElvUF_RaidGroup2UnitButton3
ElvUF_RaidGroup2UnitButton3
ElvUF_RaidGroup2UnitButton4
ElvUF_RaidGroup2UnitButton4
ElvUF_RaidGroup2UnitButton5
ElvUF_RaidGroup2UnitButton5
ElvUF_RaidGroup3UnitButton1
ElvUF_RaidGroup3UnitButton1
ElvUF_RaidGroup3UnitButton2
ElvUF_RaidGroup3UnitButton2
ElvUF_RaidGroup3UnitButton3
ElvUF_RaidGroup3UnitButton3
ElvUF_RaidGroup3UnitButton4
ElvUF_RaidGroup3UnitButton4
ElvUF_RaidGroup3UnitButton5
ElvUF_RaidGroup3UnitButton5
ElvUF_RaidGroup4UnitButton1
ElvUF_RaidGroup4UnitButton1
ElvUF_RaidGroup4UnitButton2
ElvUF_RaidGroup4UnitButton2
ElvUF_RaidGroup4UnitButton3
ElvUF_RaidGroup4UnitButton3
ElvUF_RaidGroup4UnitButton4
ElvUF_RaidGroup4UnitButton4
ElvUF_RaidGroup4UnitButton5
ElvUF_RaidGroup4UnitButton5
ElvUF_RaidGroup5UnitButton1
ElvUF_RaidGroup5UnitButton1
ElvUF_RaidGroup5UnitButton2
ElvUF_RaidGroup5UnitButton2
ElvUF_RaidGroup5UnitButton3
ElvUF_RaidGroup5UnitButton3
ElvUF_RaidGroup5UnitButton4
ElvUF_RaidGroup5UnitButton4
ElvUF_RaidGroup5UnitButton5
ElvUF_RaidGroup5UnitButton5
ElvUF_RaidGroup6UnitButton1
ElvUF_RaidGroup6UnitButton1
ElvUF_RaidGroup6UnitButton2
ElvUF_RaidGroup6UnitButton2
ElvUF_RaidGroup6UnitButton3
ElvUF_RaidGroup6UnitButton3
ElvUF_RaidGroup6UnitButton4
ElvUF_RaidGroup6UnitButton4
ElvUF_RaidGroup6UnitButton5
ElvUF_RaidGroup6UnitButton5
ElvUF_RaidGroup7UnitButton1
ElvUF_RaidGroup7UnitButton1
ElvUF_RaidGroup7UnitButton2
ElvUF_RaidGroup7UnitButton2
ElvUF_RaidGroup7UnitButton3
ElvUF_RaidGroup7UnitButton3
ElvUF_RaidGroup7UnitButton4
ElvUF_RaidGroup7UnitButton4
ElvUF_RaidGroup7UnitButton5
ElvUF_RaidGroup7UnitButton5
ElvUF_RaidGroup8UnitButton1
ElvUF_RaidGroup8UnitButton1
ElvUF_RaidGroup8UnitButton2
ElvUF_RaidGroup8UnitButton2
ElvUF_RaidGroup8UnitButton3
ElvUF_RaidGroup8UnitButton3
ElvUF_RaidGroup8UnitButton4
ElvUF_RaidGroup8UnitButton4
ElvUF_RaidGroup8UnitButton5
ElvUF_RaidGroup8UnitButton5
ElvUF_RaidpetGroup1UnitButton1
ElvUF_RaidpetGroup1UnitButton1
ElvUF_RaidpetGroup1UnitButton2
ElvUF_RaidpetGroup1UnitButton2
ElvUF_RaidpetGroup1UnitButton3
ElvUF_RaidpetGroup1UnitButton3
ElvUF_RaidpetGroup1UnitButton4
ElvUF_RaidpetGroup1UnitButton4
ElvUF_RaidpetGroup1UnitButton5
ElvUF_RaidpetGroup1UnitButton5
ElvUF_RaidpetGroup2UnitButton1
ElvUF_RaidpetGroup2UnitButton1
ElvUF_RaidpetGroup2UnitButton2
ElvUF_RaidpetGroup2UnitButton2
ElvUF_RaidpetGroup2UnitButton3
ElvUF_RaidpetGroup2UnitButton3
ElvUF_RaidpetGroup2UnitButton4
ElvUF_RaidpetGroup2UnitButton4
ElvUF_RaidpetGroup2UnitButton5
ElvUF_RaidpetGroup2UnitButton5
ElvUF_TankUnitButton1
ElvUF_TankUnitButton1
ElvUF_TankUnitButton1Target
ElvUF_Target
ElvUF_TargetTarget
ElvUF_TargetTargetTarget
FocusFrame
FocusFrameToT
PartyMemberFrame1
PartyMemberFrame1PetFrame
PartyMemberFrame2
PartyMemberFrame2PetFrame
PartyMemberFrame3
PartyMemberFrame3PetFrame
PartyMemberFrame4
PartyMemberFrame4PetFrame
PetFrame
PlayerFrame
TargetFrame
TargetFrameToT

**Comment by Snakybo** [comment]
Good catch, I'll look into it!

**Comment by h2oboi89** [comment]
Thank you! This has been intermittently causing me to wipe the group as healer!
