### ISSUE TITLE
mouse button bind no longer works.

### ISSUE THREAD

**Issue by whitter392** [Snakybo/Clicked#40]
## Describe the bug
mouse button binds (button3 / button 4) no longer work after 0.13.0. mouse button buttons with modifiers also don't work. mousewheel bind does work.

## General information
* **Clicked Version:** 0.13.0
* **WoW Version:** Retail
* **Did it work before?** Yes in version 0.12.1
* **Does it occur with all other addons disabled?** Yes

## Expected behavior
ability bound to button3/button4 would activate when the bind is pressed

## Reproduction
1. Go to clicked
2. bind any ability to button3/button4 with or without modifier
3. press bind
4. no activation

**Comment by Snakybo** [comment]
Thanks, fixed in 0.13.1 right now, sorry!
