### ISSUE TITLE
Alt key blocks Button 1/Button 2 movement

### ISSUE THREAD

**Issue by Fraktyl** [Snakybo/Clicked#42]
## Describe the bug
Holding down the alt key stops the ability to use the button 1/button 2 move combo.

In WoW if you hold down left and right mouse buttons at the same time you will move forward.  With Clicked installed if you are holding down the alt key when you use this key combination you will not begin to move.  If you are already pressing the two of those buttons and then hit alt it will not interrupt.

Without Clicked installed you can hold alt then click both buttons in any order to begin movement.

## General information
* **Clicked Version:** 0.14.0
* **WoW Version:** Retail
* **Did it work before?** Unsure
* **Does it occur with all other addons disabled?** It works with Clicked disabled

## Expected behavior
Expect the alt button to not block the button 1/button 2 movement combo

## Reproduction
1. Hold Alt
2. Press Button 1/Button 2
3. No Movemement

1. Press Button 1/Button 2
2. Hold Alt
3. Movement is not interrupted

**Comment by Snakybo** [comment]
Do you have a binding on `alt-button1` or `alt-button2` that is set to trigger on Binding Targets?

**Comment by Fraktyl** [comment]
I did on the Priest.  Removing the Binding target from that skill fixes the issue.

![image](https://user-images.githubusercontent.com/478132/104050806-29f84900-51b5-11eb-8973-28d9bddd6569.png)

**Comment by Snakybo** [comment]
👍 yeah that makes sense then, the Binding Targets option are "global" in the sense that they will always capture the input, so if you bind it to `alt-button1` it will try to cast it when it detects that key combination, overriding the default behavior of the game (in this case camera/movement)
