### ISSUE TITLE
/cast Alchemy not working when first logging in

### ISSUE THREAD

**Issue by pgl** [Snakybo/Clicked#49]
I have Alt+Shift+A bound to `/cast Alchemy`. When I first log in, it doesn't work. A little while later, it will start working.

## General information
* **Clicked Version:** 0.15.4
* **WoW Version:** Retail
* **Did it work before?** Unsure (only recently started using Clicked)
* **Does it occur with all other addons disabled?** Unsure... Do I really need to try this?

## Expected behavior
Alchemy window should pop up.

No conditions are used.

## Reproduction
1. Log in
2. Click Alt+Shift+A

## Screenshots

![image](https://user-images.githubusercontent.com/1181139/107846510-97b31880-6de4-11eb-9919-30efc6c4ecfd.png)
![image](https://user-images.githubusercontent.com/1181139/107846518-9eda2680-6de4-11eb-91f6-b7700a623823.png)

**Comment by Snakybo** [comment]
Hi! I'm unable to reproduce this. Is it just on the first login after opening the game? Or every login? Does it work immediately after a `/reload`?

**Comment by pgl** [comment]
OK - I looked into this more and I don't think it's related to Clicked. For some reason if I just do `/cast Alchemy` manually it doesn't work either. Clicking the Alchemy button from the professions pane works, but the slash command doesn't.

Weird! But not your problem. :) Sorry for the time spent.
