### ISSUE TITLE
Delete confirmation dialog appears behind main Clicked window

### ISSUE THREAD

**Issue by pgl** [Snakybo/Clicked#50]
Delete confirmation dialog appears behind main Clicked window.

## General information
* **Clicked Version:** 0.15.4
* **WoW Version:** Retail
* **Did it work before?** Unsure
* **Does it occur with all other addons disabled?** Unsure

## Expected behavior
When deleting a binding, the confirmation dialog appears behind the main Clicked window, so the main window needs to be moved to confirm or cancel the deletion.

## Reproduction
1. Right click a binding and choose "Delete"
2. Confirmation dialog is behind the main Clicked window

## Screenshots
![image](https://user-images.githubusercontent.com/1181139/107846572-15772400-6de5-11eb-8f8c-b315ee847e18.png)
![image](https://user-images.githubusercontent.com/1181139/107846576-1d36c880-6de5-11eb-967a-7fad3167e54e.png)

**Comment by Snakybo** [comment]
Fixed, thanks :)
