### ISSUE TITLE
Tooltip Text Issues

### ISSUE THREAD

**Issue by h2oboi89** [Snakybo/Clicked#51]
![Screenshot 2021-02-21 160414](https://user-images.githubusercontent.com/5531999/108638719-8611e680-745e-11eb-905c-33c628c34881.png)

Latest update (16.2) has weird overlapping text issue. Does not seem to be properly filtering out binds and showing the bind even if the spell is blank?

**Comment by Snakybo** [comment]
Hm, are you consistently getting that?

**Comment by h2oboi89** [comment]
Seems to have gone away now. My PC acting a little wonky since I upgraded to 20H2.

**Comment by h2oboi89** [comment]
NVM, It is still there. Was in another spec when it wasn't.

Seems to not filter out spells I can't cast (IE: Renew while in Shadow spec).

I used "IsUsableSpell" to filter out spells as part of my `filterBind` method in the code I linked you.

This saves me from having to explicitly add the specialization condition on spells for specific specs.

**Comment by Snakybo** [comment]
Oh that makes sense. I think I'll just add in that check globally so they also appear grayed out in the UI. Thanks :)
