### ISSUE TITLE
Support more than five mouse buttons

### ISSUE THREAD

**Issue by Dairyman** [Snakybo/Clicked#52]
## Is your feature request related to a problem?
Mouse buttons 6 and counting do not work on unit frames.

## Describe the solution you'd like
Button 6 and etc to work on unit frames.

## Additional context
Seems the mouse button handling here checks only to Button5
https://github.com/Snakybo/Clicked/blob/64567686078302c3b426438211f698bf6c0c33bb/Clicked/Widgets/AceGUIWidget-ClickedKeybinding.lua#L80-L93

**Comment by Snakybo** [comment]
Interesting, which mouse do you have that has a mouse button 6? Can you confirm that it does work when using the standard keybind interface in esc->keybinds?

**Comment by Dairyman** [comment]
A Logitech G700s which has 11 mouse buttons 😄 . 
Works with standard keybinds and clique. If I change the value in the DB from Button6 to BUTTON6 it works.
