### ISSUE TITLE
Clicked and GladiusEX are not working together ( target and focus  by left and right click not working )

### ISSUE THREAD

**Issue by Zeucean** [Snakybo/Clicked#53]
If you use GladiusEX for Arena Party Frames in arenas to take target and focus with left click and right click does not work while Clicked addon is enabled. Somehow it's interfering with  GladiusEX, and i believe also with sarena and Gladius.
Could this be fixed as it's usefull to have Clicked and GladiusEX both in arena ?
I tried to blacklist the arena  frames but no effect.

**Comment by Snakybo** [comment]
GladiusEx seems to work fine for me, both the party frames and the arena frames (judging by the quick skirmish I did). Gladius doesn't work at all I've noticed, but that's an issue on their side.

sArena doesn't seem to support click-casting at all from what I can see.
