### ISSUE TITLE
Not working with GW2 ui  after update 17.0  after update .16.2 clicked no longer works on raid frames or group frames.  it will work if i turn off GW2.UI

### ISSUE THREAD

**Issue by Lukoon1** [Snakybo/Clicked#55]
## General information
* **Clicked Version:** enter the version of Clicked here
* **WoW Version:** Retail/Classic
* **Did it work before?** Yes in version x.y.z/No
* **Does it occur with all other addons disabled?** Yes/No

**Comment by Gothdroid33** [comment]
Hi
I have the same problem, I use GW2Ui and I have this LUA Error 

`Message: Interface\AddOns\Clicked\Config\Blacklist.lua:123: table index is nil
Time: Fri May 21 17:08:01 2021
Count: 1
Stack: Interface\AddOns\Clicked\Config\Blacklist.lua:123: table index is nil
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Clicked\Config\Blacklist.lua"]:123: in function <Interface\AddOns\Clicked\Config\Blacklist.lua:98>
[string "@Interface\AddOns\Clicked\Config\Blacklist.lua"]:224: in function `BlacklistOptions_RegisterFrame'
[string "@Interface\AddOns\Clicked\UnitFrames\ClickCastFrames.lua"]:182: in function `RegisterClickCastFrame'
[string "@Interface\AddOns\Clicked\UnitFrames\ClickCastFrames.lua"]:50: in function `ProcessFrameQueue'
[string "@Interface\AddOns\Clicked\Core\Clicked.lua"]:89: in function <Interface\AddOns\Clicked\Core\Clicked.lua:86>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[string "=[C]"]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
[string "@Interface\AddOns\AskMrRobot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:90: in function `Fire'
[string "@Interface\AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>`

When I disable GW2UI, no problem Clicked is fully functionnal.

Clicked Version : 1.50
GW2UI : 5.14.2
Wow Version : Retail

**Comment by Snakybo** [comment]
Thanks, fixed
