### ISSUE TITLE
Macro with SendChatMessage not working

### ISSUE THREAD

**Issue by tflo** [Snakybo/Clicked#57]
Tried to launch a simple chat message macro via Clicked, and cannot get it to work.

For example `/run SendChatMessage("Hello", "SAY")` works fine as normal macro, activated via action bar button, but not via Clicked.

No errors logged in BugSack. Also tried it with all other add-ons disabled. Then I get “Interface action failed because of an AddOn”.

All my other Clicked macros work fine. Cannot say if this behavior is new, as I never have tried a SendChatMessage macro via Clicked before.

Not sure if this is is a bug, or if I’m missing something in Clicked’s settings that is required for chat message macros.

Clicked 0.17.2 on WoW Retail 9.0.5

– Tom

**Comment by Snakybo** [comment]
Should be fixed in the next release, thanks!

**Comment by tflo** [comment]
Seems to work fine now. Many thanks for the quick fix!

And gratz to version 1.0.0, btw :)

**Comment by Snakybo** [comment]
Thank you :)
