### ISSUE TITLE
Instance LibTalentInfo 1.0 missing

### ISSUE THREAD

**Issue by rbpaiett** [Snakybo/Clicked#59]
## Describe the bug
Upon entry, this bug appears:

Date: 2021-03-29 13:37:06
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Clicked\Core\LocaleUtils.lua line 2:
   Cannot find a library instance of "LibTalentInfo-1.0".
Debug:
   [C]: error()
   !Swatter\Support\LibStub.lua:23: LibStub()
   Clicked\Core\LocaleUtils.lua:2: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "LibTalentInfo-1.0"."

It also can't initialize or redraw
Cannot run /cc dump

## General information
Version: 1.1.1-Classic
Wow Version: Classic
Worked for version 1.1.0-Classic
Still appears with other addons disabled

## Expected behavior
To logon without Lua errors.

## Reproduction
Simply logon

**Comment by Snakybo** [comment]
Whoops, I'm on a roll breaking stuff today. Sorry about that. Will publish the fix (1.1.2) right now.

**Comment by rbpaiett** [comment]
Lol, it happens, thanks for the update.
