### ISSUE TITLE
Start auto attack don't work

### ISSUE THREAD

**Issue by GMib** [Snakybo/Clicked#63]
## Describe the bug
Checking "start auto attack" don't work, no attack, no targeting, there is no /startattack in status

## General information
* **Clicked Version:** 1.3.0
* **WoW Version:** Retail
* **Did it work before?** Not tested before
* **Does it occur with all other addons disabled?** Yes

## Expected behavior
I want auto attack and auto targeting if no target when cast spell.

![image](https://user-images.githubusercontent.com/31073459/115985262-4fb22e00-a5ab-11eb-9043-535f9dcf68e7.png)
![image](https://user-images.githubusercontent.com/31073459/115985237-2f826f00-a5ab-11eb-811f-bda701549612.png)
![image](https://user-images.githubusercontent.com/31073459/115985241-37daaa00-a5ab-11eb-84dd-c504da3b90cf.png)

**Comment by Snakybo** [comment]
Thus should be working as intended, when adding this I found that you don't need `/startattack` when not explicitly specifying a target (i.e. using "Default").

If you change the target to "Target" it should add the `/startattack` command.

Are you saying that it doesn't work that way? I will check it out if so, thanks.

**Comment by GMib** [comment]
using default, i've no auto attack or auto target regardless i've checked "start auto attack" and "target on cast" or not
using target i've no auto target (because i must have a target ...)
i only want same behavior than macro : /startattack /cast Éclair
if i don't have target it target nearest enemy
i must use macro for each attack spell else

**Comment by Snakybo** [comment]
Will check it out, thanks :)

**Comment by Snakybo** [comment]
Will be fixed in 1.3.1

**Comment by GMib** [comment]
yeah, it work :) thanks
