### ISSUE TITLE
Addon on lower toon non functional

### ISSUE THREAD

**Issue by nedempst** [Snakybo/Clicked#64]
## Describe the bug
Addon non functional with errors on my lower level rogue

## General information
* **Clicked Version:** enter the version of Clicked here
* **WoW Version:** Retail/Classic
* **Did it work before?** Yes in version x.y.z/No
* **Does it occur with all other addons disabled?** Yes/No

Latest version on retail and always works on my main rogue

I think it has to do with spec not being found since when you start at level 1 or whatever and you have some of the options in the profile set to spec and well at first you don't have one.... haha. oh well.

If I reset the profile and "start over" seems fine so might have something to do with stuff trying to load and not finding it or wondering what happened.

My main rogue profile:

S3vB3PjsB4FlD3V2EQGAm2NZZ5SgJn12e01jMD7PTghHXipbbxyiztp94V9NzgucciGagrYS7hAu59xMR566((6(EKWORhbMOQROQFNf5VLyFHQcshRovfzs)ca(PfOraq)oxE5iaugRAOtxQ5qztdj4CYVnWwF5yzBlSX8LJzF)iG1cKM2nqnB0iPQ1QCkz7anVdHhQRIBnfJmBdTWJMq2By0CNLdmcid1LrA)PnYgPaOBb6sW2IDLj7wqxDYAofkJ(E329KaFVR0n3ELQL8TKvXIEKDf08(ra0)IKTPFSNPYQZcv6AAAVGTpTihl4w2yJwymu(E3VQpc)83W2TRpYWJa3JEIEPICP4tD)41V7Vjh6KT5DMq6oIE1JSmoNJ0paMz8aYuMCs2rhordPq3jMO7S1GMR)MZ8Su0v5bvmuZAeOL0xP)c5estf)KZNjB8vRT79POwCGn568iW5D(yRHxsp0O)pqZaQq3rl0GpHmP38gGGAZz7BNBbxbLHtmj)HfsdjJzh2Kvu2y(ei(5LJCKV5cOQtUMsU3Dn9HfYMZI8eLgzZi1tQJNLvQc52PTgwDb5hzpV5SeSJoznOf7s36vEqVlggZA7SiSv35KQR(fMg2l8Ck5)q1K84J39YngQkD0Mg9r56fITNipBlRc1u)j7wVNTLu1i3kKFMT(O)XwDXcY12NVU7)GCUHn5HlplrGR4t1EICnoIBjwyY9w8SiwcYtBK309E8tUF4EFn49kYTl2X)pn0rS383(XVoI80p9r(fOOESX6r15ZJ(0yXdlUoLhNKlr0x9I4kGHnwXWWK9uNZBaH8KT)hO6kD7fd6nS)T9Bn46VEBVb3oOv3Zd(kZdiDyAU8Yg68l6gpYE0A1lM(38tnmzV3U6Df6Bsj4o3JqZRmuI4kc99iOj9PcWD03JEh9wUKOFybX8aw40tA0S0bl0UyblSjmqqqfoSWAiooSW6Re7ryH0nQvMXqKjZflDJfFqHqCbrJDyBqgqjtcCt4Wcv9dlqM(toWwqOE9tRv6agUHdm4HqbNVaLEeNVWAmhoWGd)7KXTOOdmuZpWq98ayOUyJgLiyHl78rQyBfinK4Kf4AiTPSEhunK4ycLembrQgs19JjCsEGjuvquS8Xv4QEdbD(Rp1PZLN37VKkwGe(IlbpqdBvIwUIsLxfLYGElhujLsVsyXRbLlRKuPOedK4ekiXgsi5ny0Kz)NQ4plCADkyt5k(ZpJrmSFXcHGtJGtJGtJi9J0Eqbi2PbXZsyhIfpjqmhyien8tJGMzrzodLeAEszcH4RflaboLboGqbcqGNBsPhBkjtThKoH7sjGWP(beO5uedqO71DUkDmgasQytJLJpZWWcBLaQdeIlhh5UA7RhC57g09IpXd9G38BLhoAE4O9(8q6gbJNNsXLEPzHWqsGEcNZqZaUAOsEqAqS5P0eEQSiRu)wx0HhUbUVg4(Ai3t7(mdmWd3qqJzStkvfoWGqLaid5IH3kJ(DRtXrtPl7Ed5OXJQsFQ1actpN4oCDRbx0H74nVZMLhi6xGarZvvQKOQunAygec6e6CXCdcc1QiuQsyPIdSGpxt7fuGfS8E30zGRBg3M5P5qjfdZttMh2Mgf)vK5PpqQpXjzK3KmO(9xsG5E6TMutu0G0LvtnBCAvQXkklcqXZOPTwcc4fxd)MLROHpqRQmRlzkN5uky2BfxJde(q6NFppJMyLrNaIq5GpWSr92XhidXNk8HQc1R1SmLvto1DP)Qyr4GNSR8CBQaLBtCOHu5zUKeB5Se76uMBteUb(RhF5IR5eR0SmPbv7w9bx2R9xkoidorOWbB4zTNceYI1LwRJFXO4fWpFjoWXEb8JdKKkGKyhOplOijbLkahdNWzeW91c0sPblnzVQv7b9shhdWBwxGaoQvH692wOLJFdWPGzU8ZoF(B)HJYA)y54lGMMgyeLaNBvGvA4v9BDE)lhckoWo0iGWjKueiKSr54SOPvvGAC6EuRkEyXtVSzjz8(xwZwiWmO9gfiCx7wKLkeUWP1RkuMsMwhTQ(to0aVM)fznc)1m0aNIrjHIHtymyoZERHXqSs6Oyiv9K61ltIvvWmFx8kv509jCQb8Ucv5D1wLXT8Il(2Rw)8mW9fidC54jPcpjrSmYqUHfRKyBXBgbm2TyU01jeAiwMsAQcuzfpsBz0E4aqpA63Y74e8ooH)Mzdx)jEJiY3ZeBjogbSYTORTmYsCmk0zrlvUwAdRBRDNUF3AMXJyddAFvB5NFpTPZTC83ODPSpi8wNuh9dv(Xv2yvnig9F89lcVx0)Vj(dGQUQfgzUCmaBQE)6vQ6ZBUZGY3t22twT5C)f6MdmdQy8OfBn3iOjCbX4vDeEtZlF7PBz2C5PpaffJ86nwcgV4XCNjiMiZC5BxqSu77JgLQAv4a)DCqx2zV0TrvUTY5ns1W6aOVgBcgzqVNdkOq6XYsKmyjVXlr4VeO1(qbfy(kF7GcP1Shcnp5uHID3unwAmBWuOWvUr2O6IesM8Y11IRR1lOUw8GDKQGDuu5keSdBNlg9GvUrOvi9YIhXz1VwEQ3ULovp3M48EQQmM3tvn2Og2SJ9u1ereid8JIfck84HlgOBBlMlT(I6nAwTyNFv7gXbNmV9SHxFDpjHIt(3guCPox2FTBn(yV2dbrNKv9Bn46VEl5eYxZ0OWeqDr)fSjGupPo08gdaA3rQ1GU9y97A2jYijYJCdA19CAFHe0)M(0w)fO1aYY5ObLSg0IP)NLQoT0Kdg07IHeoHUwTwQsG9NZI4uMf0GpHm7QFH5Mdf4Fc688YQ8Mxwzyi6JujSIfzbKd1mxXaEsVAUun1fQ24KcUcw0A8tKbIFdfSkYnX1JBtcsXuyyge4eoMbLliWpW2bY(5n9Iqh0BlcoOZ)0qhjbNJkE1z90h(GdkKr0dRFf08EKYYXtnmxo(CeepZFTkldqLXI5eErVsKzi9nmGUxxfwL8StOf9Q2ZqWfVhmt9bY5WcKM2nmzaLeoTAX2(GXsIz7jUf9SnSK2IDvWRL0DO(CEXH0d3p6ffYih7(rNAFSi4(ry6xWrwYWqShuOL0JiMiD02PaQVaAI0jd4DhLv)7CsYQagsVQRlrIkHGpZ2KMKSKL1dkczwuf4aLelcYQe)TTHgbS)mnddY)4IQ4KsU0VhQGSwxJteQT(VGAAQ0efE54jqmwJ8V0GjOanv2aIHf)LcN4ACCMIcodzsyrnmn9DwYlWO)XwDXcKseeaoqey2aNmGeJfFyM0pC9bfLj5WaV45YlRRJlgT52PCpsvn6vuqu4ukGvzj(8ouqkq9F8itQ3Z78XwdVK3SO4nlQWY7xURelKUsmwfNszjXkj8vc3vIImRQVDXS2ws9YiHuczGy908jgAwlhBmD5yfQGJU0qKzKtMWiN46urDJvPy)pwoEQg8oKMgZKyHVewittiMkO5edDkpLfQ3Jw(5qucJZtjydTH3PZ5D6CVW986Zy6PmvOqIC4PeWF8vZN8iUzTJ8WRec8qRItGs4wpKN3wCRhYAsszrGNdQgw7tCKSL3wSiLunqVoVQBjGplLUxXknAWazkUsyfBKtk2rrpMATiRJ1EWsdyws86rZ)isd4xbPS1XE58nWDpjHMjoY67zQe0y1UUdlsZSFFTh4vzaWrkeqseFkL6AfllLWZqRQb6a6vD9Bs3R7Cv6I4b454mFNMQcTatDpTjjfl6HKqLMvAqWzKPrPw7pTr2ifandWiZAamhkBA0v2qFeORogzofkJ(E329KaFVR0n3ELQL8TKvXIQQenD4gbq)ls2M(XEMKJIrRTkIPP9cmDlYs03w2yJwymu(E3VARfHRnWqgwCOwWJnop24bLb81ynnj9tq)GcQuGJnEDgXIaExVQBpbjl1KX0IuaA5MktxScI5luiMdeWrSKpC62u)gEMQPYYXpQQR8BlhVWyvaqy)O1cvtvSnuB54ziOMQ(D(xIFjpD1)9RpPIrZ)GqJtQvP5hw9FNu5dINiS6d)A23gG(F2pG0Hy2McOUyMHonIkDSSqe41F8Rz)YCDMHr3J4zwyYsSzfArINPX8Q5iVAowWQMJV(s04yj4KrBp6GYfDxAVwABVj1BYOvvCfpB3m9Ot(FvGAjI8iRuqJSYXUuzzj5G3ZkLLSKy(GsQj9CXIF0(ilnABv4WKOa3wukJ5iE)MtzZI8yQYo46cnyL3(eaoqR1KUAxLlQHfkDj)QIfl5MT4i(H9dtGmndiZsaXN7)YgZNaXpBFGaD0uEAoXsZPCZ2FX)wxgM3zsE1J8wGg18xpxsy28KlldhF0vlfDXp2JjOB8Wdb0qKovX1rO5SNvDLA1)biO2Cp295kOmCIjYFzlGStv1VB7Vx7gPawTbYeDNTg0K8NKNf82D6OAE7Roj5RVyZSH0Q1VJoCIgsHks6mJhqM0(NbDZ5Fl4287yneVNx21Rpl7f86I9AobENz19aWdBSGPUwWFA96NKW2z1rberOmh44c0kG1ngQkD0MgDnWA9cXE(M2byuHAQ)mGin5gUqIg6EhuWU8nkFgWft)KKlw4cbMDMt5z7Lhxi(MD6QKPj0UDQh8a2ITcszv7pDVHO4TyXtHtyoEpA4K0wf5B0uGkK1XmHdNOP8T)W5rS361AjmZU70CSEaPRGWyyij(vOTOkoc0XncuggeoEMpLpmR0d8uqzMuyqGsw24SxyM41FIuCeML23GfsmwfXPuBrl1CEk8wvRuPbRqeNarQy6sXk8BGb26lhlBBHnMVCm77ZPK4krYwfAmn8YpYBv1QAiOTjhpiEA0hrsvfh98KY4yRI1KGcdsIyCKofDoOjfv(ftGWg9ozjp7opV89ipJ9kKDS6hN5cd9oOuLtXyDvdYoS679EboiSUtvvMr23KBb5jNnajAKYe)9nRF7krqfhiXQIny3R4p8gaMLvup7q9)Wba8heunAjQC5yRzgmkH3JEAIQUYiq0DTKKJOe7ZUVoau2OstLLGjVhbuoOChYpaLmmuC6zsShHwIFozXptGDgQ8LhrzD1n6fdsXpddMz0Z)4IdaZSPDwCcdIRnm1HkeUdjH(Xbctz3IrEe1WxoerOT9QThLJxwiImfLdXyIitzU(2YXiYToN5oZ64fhJydUeNsJpETagtVUBdfjC)JSsiQFNmf7hXggAyvY8TbKjD)53lRHGMoGbKp58hiD08NCWR9uK1XuFe(bH3x9TZGMZFRUHccQqM((QTdZLHqBtiTAvHSOTHiN6z1utesXyoBlTTLzHPbgjtDWrAQUxEKjJCWuy1fRMFSD3Uiw8jNr89FK9cN3KJGg)ueFfYYkOSDjVE(g)mQ3PACbpDWKeOz9KNUD2oeo99i3QmWvmE2YXk9rEqYkmHXQXYVSnPYqgUZlyw9T1YscluhEJGIyLMjS)lEGiWeROyHef92T6dUSx7VWtZx3UXAmP2yeXoj3kQ6X)gwgE9nr6OXJv(ZdBxAJvEEmkSZu3JEMKr6TR19u19uE(6lRSQfWe81JPpKSIedlGcwO)XM676LJnrwi8)TondMMAiBBrjKW6ChK5pT4TFrv((mYOWdA0)N9UEFQTTbd)puVRn06yy9tzukJUdtwCBVBJRemjgWdIDUeh64l83(0RKTJKLSKSvItWvFBWLY8wX6rpVVp)qNfVhCt0JrPpp(b8)MfeAk87BpFExQcpL1OzyTIxSNeCfJuU8e5GE153p2HITOnyAqQ(W99S3YandSXW9SKpMntQVk8B(m4Q9IqSKpsJM)iu(LGdMOfSpyFK40W7wG1RpG9b078(axZV7aegEEE4v(shq2BXqiawYSKvldbVT8MxUo8)IqioiGLll2z9xE7Y0K545obF7fbrt)WBY(CxgNG7BRFd(U)iFeBKFYFXqWOptE(8txD7TsNZvu8tJVj4MNNhDNMOq6gHxvP6RHLP7v4Yg70TK2c74wFVn7WDlaZAkfDXM11cWSjxpKqagSb2Pz0WozlE7KiwkW9DWatDwLapCWPNyQZ1TlwiEZwah272BVB)Ku0rKEvQQC1J9SvwSGoJSG2HIKjyXRElHMtKSr1Hdg91)EmIwrjVRV1mNy55Ya0vKxT7o95eqm9OWyzRqVAE)G5FmF58Gh(Oz1q)5ggn5HxUEyYKhct)i6FG6lnKUIFAirObs5QKpYSLWNtRjMzkxLVo43vK3Wstkb7Y4)LJUcyGR)mo5NXsAGxRhAcAsEZyPRSjPRicFbBa(QzRCOs8f8WRiY(kV4bxVKfeKXYInUq5Vdr)HqisOpni8SsMISnyc1(4meTjBaAJ8B3il7fiyuzrTa9TBkA)eRGXeFjy)rxC63YMih5SPZIpfgORSJ(3d0QGwYjWIrzXOGnPKLbZC28Vv41jcJIQV4fwwk5uEiX7(9O3hNc5V(KhtsV)LRVjiEAWDq6OT2P9iMGkNSMxp3337iWmCVkDAFw4bpCWXNiIpdJA7GkgqdjI0XLaaEzl21XuogbTyh2zc(QyMGW4Y4lp(sHfmdwXKK4)D1caRywqmyoLvqnPJHrctVpCriusiZtMbQiioiT(yiiCMTxtPqHl95KKPpZ3ZwcDlzvlPhlvm)QWlAdnyzpaoptGYd(vCkOAScq9vEZn1d13Q1yklI808V2WauEBQxR6MdKAbSV2irKq6q34eUi8FxhOVQgQaDKaZVZf5buS6XUxkoH7)oSAWWUQNr9x0xmUpFucxA9kK3S(r(yUMf(4uecciaSaCvhM9fGUKbtpY6ZXlJtk(ZtMz2lx)jWhKftkRiAuU2y5HbB756SKwzV1gKeslYd3fltfFlqPqGsToqZoLl7uU2Ot5Yl6U7tvML4fFQSYfVCUGHaJCWE3N3CgyTjlUv5lVS)T(Yy676QzMgxxEps3aduL2YNcNwvmCvuFKUlg9z(O8A2wBUJUeT(2C3CIpQfiOL5drcH6vZvg4OvlZNGfvvoknL5JwE2SHXVFz(s4IB0rG19FpR197ZljTQtPygR73)iNEDPg6A)k9Xai0vq6(u4wkmlc0VD4p87dHJL9jEG81O(T6srw5r07GQYg2tdZPSLZSshTEoBUxi3IagQVwGAHWxBPPz8Tz0mpYmRxw2rAdQuca4WLaa9HyXxFxAgSimoaUtt925VpdpJbz)qAVkGSwzPp6GcwYI1WvL7OcDtFUuQFfTkYuCo5N7muY8ZEnIZzdnmjotzEOSsmD5pJS7XV93JFZMoMiJv6qvA8zo1NzxnOJdRyx)zo3hJjaD3qTXeQ7SSoZ77JppA5KX)1QWLq8dCEWcXj(c1uTWOnWJxAWIu9Z7f8kIlY7L)4IZproSqlVyo1anOhFlSWt46aItYLAghZMalu(APn4f29C9fS54b1CYmDLbNPsea(nC9AA4HQkc0fhk)2lawawxHgWcq6iThdlapEMalagTxgxblOqi5QrwUccLCMfuqMTiEcDXTg5UXoIoY2dbfeut8W0rWdqsMhsQnmGhSYIwHFGWOp2eqHlS5jCvURTjN31c3vx9qXuMFx29DB33Dr1ZYiZ8xjk9vRbkqpyixiy)9COm6UiAchi1O76NPWtJdFgIz4eeDL6ZOO5wnmx(ulsUBv44hIGNdCRj2oPMc28icnAOUY1v9FVQs)4L)jqRQc0)FqahNwA0t7HY114Lr2gjSVvpV2nwS93yHQRmHoKqGP0DWMsVwI1vpzq1ZfuqLs3P3aNfwlicms06KPSE8meKb9JSKn2NkVeZp)xnxelvJFfPAOCyq1QAYy18uloMATKwlwcjmCnaXT75iO53lPswxENfQh8aejjUfc95BXrPdUnnCXXbltV6g0dtA4SItT3rvCv96O3YLtc3Q)RX2HBSbmafWkn5p8p(eVbJo7cIEzHGbfRy2rdo7tTQqIm)CBnhtLjkQv9b)gSouTifW7wDgv1YPfAO))o4kpx4Vu9GIuf9ETgkSTzl7ChQtPoBlzPXL43ZherzfWkOV3lvsIamqPvBRhgsVdFFT9zb6qDjYGnNAXK7ddMlEStO35eUMeT2RnnBefL8vEvRW01xhdpxKXYL5TEbt0JQBWO(8c6JX9xUmTVdoEvaiPfMHbysQb8eeFkmisvg36wuOY5R5zEJpD0fFB4ys(SFXOX4BHT(6ByfmOME6wWIhDfuiYcsqmz6JTKELXdSBt96xVd69HEORyUngZL(IVLHFuzCiZyXWoyWc0wCDx1ISy1lXgPwdsTD1u3NYLQxQLSjegtvBcJkZrzNLSkgu4w16ys95H8GyhO4)creQq0QoetRc9z3Z5vzWnaud3SfTZyTMOMbTtPYR5uHeD7l214mWknIiZbh(o3EfHxBhyyy7wlJxmKl7OWK7Tz9JWeLVY4xVxEfCemI6WYCH8WRFz03P7EQBZ9JXw80y1qbQrAR91WuDjfn9oUE3xCRiehM1O4IjFGnbo7nPr33G5dY3pj6ncmhxeOKw0p2rlrrOtWzwkpTT)i4g)JDh77SDS))T312YPnsq0FODtzaBU8i(sw7QsWzTCYtPaeIbwTwGi6IZYl8TVZmcWcjH6EgPrxO0lPkNYf2gB1NUpN(CAYyTcm40HHvuyE9MF(PldnC3u6ppVmuy1gboMDvc2qeTr6YDcECkwsjOerHkODprNDXqw4yVA30HZSFN(ungkQkjmcXOO6ZnOd52JmfbNpOeTivfOpB4rDjdFq7ieX4qnWhy7uc5KdHtDQc)YYDYibd4ZoWDfEmiIWFI9J7mCuOeJA3QZG(xEtp83n4dfb(aZk)PqxdEQLqHpKHoSlvqIMnRk)10MVv(LjZsLKfVIo9qcEdV9P0kXQUlLGeT6FthS6AxsdnigXsp2aku4GczjnNGlAlxLvuGnnCofnJLpO(sJCdw6o0oYPVFWwabt6FP4owByjk3quqH43b9KtnQtVn597YwbkmuejVZUXVptO2VwHUjG7pISqhq2(u8tmuiwQdjweHmyf0P3qkdkpvw7vwM8lFZnBcVArfPsiWAPwlqLsIpkwwGECsX4nf0oqyFHBOxHyrkDAtWnnmhsYs27OJ6g6EJN8zxchprIyvpfNGuN1i3cHg0OGaBdkZTaYtAN4HVWl8UOacpaprHclWk3WkkXGDiRgFHePFiYJ1qBUgKNVRMU4((h(8WV)Lx5WOr8XDFUpU7g)AIFIacY6HB8(VtuybC(W7dMNou(hkUXRw(VRtsbVIUZsIxz4Vcywnlf)vapksXBwqqWMZdjEXBLc2ESNw7(xY7XlCBkkCOfXwaB5xCaWgPoN7jcDJYt9kWEk1uQdKbpHuQ)MTMOvSdrfvb61UutmM9ReX(wnoqfLWZUdodCn6cZMdJRxeCxbxBcevd8jFTMrO4bWsaHwvYrOYd)tkest0js43F1EH8JDohJ53uxJX8eD9q5abW0ZQ2ooqHFu8ulaWj7zvwKuVbaiH7sLChtV6mhALoaqxoaGQSsDRb963PANRGIT5s8ej)JWfKDbKkLOfmkpmXVd3vLSfeSpwPfSa)sTc3QCgApSSxIPkKAgNqN2zdFQkACbYkeCYPRq45OZCEQG0ve4AiujEM7eLk4EIOxSJQ9a6V5ZEkCCtRETrMNGIQNbEQMsnlNYmYrDnoNGBArHmkDbGRvHuDq4ACX2mQyLnV8yDkdnhapMxrObbC)pYlabM2FoJge9cD7TZkVt3goLYh1Q)1DUQ)(WL987vvkzplEmI4Opy1)oSI5HZDJB)(RV(mlsWJpAry83bhDlixGAhYs)CCFOPpxFuMJG8f01Z0Y0B7yThF4l05EoSV13)WqwALhpac5odsArjGFYPgPkrggccxp1516YI)CT1OUqq8UZvxaUJifwMpdWtyagwnt3lLaEmh4BLVFS9cDXTfqq6oTVUBhK2MwDZjiOK0cTFSbUL4LN(RhPvHppztc3jNc7r)cJ0)CRemmMgiqb8tSkS)78lJMsQFZRt3d7xxZfYfZYVkhxEGUvP02uwCmvfru6bmq1r94gQgOdyz3v2oT7FZ19W5XofJAi71WJByG3iBNzUE(yTylVAPfo4PUWsCLtE(hp8c73WCIdp6Atjw0j4UUUKX4(HT58hSwK(fM6WNeVlvK7b7zjUhXqg1Deo5kaReRHaahUFZDZqZ)QCKel9TehgXlVq0Tw9X4dAFv3qFMdrQuTe)WPmaVq52hdoHBf7uJUPbXV8rFuCMHEh8rJeb8aZGbFJ4n0Zt34n2P2J8FedFpt71p7mN4WS2ohd0XXFd)u8LWbLqCwSscslEWVoSzCJ3t(O2NzH(Qm356GhPOZJwQZvusvDZqTt55lxHvDHbFbNuabtwqJOIue7sn1gIcoW9MD8znc(0cUBrrJUP9qdjE346SB6kDN3iZ3nL(N27MoNLaS)XUPgoMRCTxVBQhz1gIBqlzhXve58fvY4kMRFFY)s(nXYWrFHN56Lt2)JM7gZ1eRjxrHTGazIEIwJHnlT0bs31F96uva9Gi2(9ZYjecg2q(kLyuwmbviaC8w4JheBbwQ03K1mGqDezV2d4K5UTqIiHJSkLVwvdyRKl9B5Lo2(Byk7geVvZnDzu8)KH96XApXgjyHUb5NpD3ZJ0(PJ9sFYeAfuDRTEMgt2yBsXzgRTMob2yTVX)i3tsJWGx()KnfzarmP(6FWb46ol9DN4A7BnZE1S5Kz(lwyX8i9HVu3s)pCPiDepJK(YXz2JR6pQVCb)yTu3XX274xIGzLs8NgU)656ijWl)BMZxt2gCEzdE)6U7s67Dg)ZJ4KsI6f3WHc677qMy474sMp5k688bV8F10nX3CyEXH(9aTHCx68FJ1A9PoFIwB2YC5)49Bc7FPnQ7nE8)p

![image](https://user-images.githubusercontent.com/59960468/116276646-4b5a6080-a7b7-11eb-9c89-cf5ac2ccca72.png)
![image](https://user-images.githubusercontent.com/59960468/116276694-54e3c880-a7b7-11eb-932f-a3a470f1c138.png)

**Comment by Snakybo** [comment]
Fixed in 1.3.2, thanks
