### ISSUE TITLE
No stance condition on TBC classic version

### ISSUE THREAD

**Issue by novsirion** [Snakybo/Clicked#68]
## Describe the bug
The macro condition on stance doesn't show/work.

## General information
* **Clicked Version:** 1.5.1
* **WoW Version:** Classic
* **Did it work before?** No
* **Does it occur with all other addons disabled?** Yes

## Expected behavior
Like retail version, we could choose stance condition on macro.

## Screenshots

![2021-05-29 12_03_05-World of Warcraft](https://user-images.githubusercontent.com/7797113/120066378-533b4800-c076-11eb-8a82-7bf069c38a64.png)

**Comment by Snakybo** [comment]
I don't actually play classic or TBC so I can't easily get the available stances for every class/spec and no way at all to test whether it actually works.
