### ISSUE TITLE
Suggestion: Remove rank or auto uprank all button in TBC

### ISSUE THREAD

**Issue by wheatbread** [Snakybo/Clicked#70]
## Is your feature request related to a problem?
It's currently a bit laborious to search for and replace old ranks with new ranks every time you level up in TBC.  It would be great if, like Clique, there was an option to right-click and remove ranks from the spell.  Alternatively, a button we could click to auto-uprank all bound spells to max ranks that we know would be amazing.

**Comment by Snakybo** [comment]
Can add this 👍

**Comment by Snakybo** [comment]
After taking a more in-depth look this is harder than it seems because spells are saved using their spell IDs instead of their name, and each rank has its own ID. Will take a look later.

**Comment by Snakybo** [comment]
Will be available in the next release, there's a button to remove the rank of the spell:
![image](https://user-images.githubusercontent.com/3172140/123510497-406b6180-d67c-11eb-8af6-e6b5963ba9f7.png)

after which it will always use the max available rank:
![image](https://user-images.githubusercontent.com/3172140/123510504-4b25f680-d67c-11eb-9404-03aedd311399.png)

Additionally, you can right-click spell book items now to automatically use the max rank (a shortcut to selecting -> remove rank).
