### ISSUE TITLE
Suggestion: Default Template We Can Set

### ISSUE THREAD

**Issue by wheatbread** [Snakybo/Clicked#71]
## Is your feature request related to a problem?
First, Clicked is amazing for customization and I love the options like "target on cast" etc. 

I do have to admit, however, that I was using Bindpad and Clique over it for a long while, simply because Bindpad is so much faster to set up each spell on--2 steps are you just drag a spell to the pad and set a keybind and you're done.  With Clicked, you have to click on New > click on what type of binding > drag the spell >  set up the keybind, so double the steps.  Clique is also super simple to set up fast for a pleb like me.  I remember I struggled to make a dispel spell work with Clicked because I hadn't set up the targets, as an example, but Clique just works when bound.  

Might it be possible to have a default setup in Clicked where it just casts and works with no setup needed for targets, etc., unless you want to fiddle with it more?  And a way to just quickly drag spells directly to the window and bind each in 2 step moves would also be amazing!  

It's a terrific addon and I don't mean to sound like I'm complaining, because I'm honestly not.  Just thought it would be great if it had the simple 'just click and work' options, too, for noobs like me/ people keybinding a ton of stuff all at once.

**Comment by Snakybo** [comment]
The default "create binding" option is set up to mimic how dragging a spell onto your action bar would behave, so just cast on your target or self-cast if enabled.

I can add a template that sets the default options to click-cast, so it works with unit frames 👍

**Comment by Snakybo** [comment]
This'll be in in the next version on Wednesday.
