### ISSUE TITLE
Cancel Aura conditional

### ISSUE THREAD

**Issue by kamari0** [Snakybo/Clicked#76]
## Is your feature request related to a problem?
In PvP and PvE I like to be able to cancel certain auras such as Ice Block, Presence of Mind, Bubble, Bop when casting certain abilities. Being able to add these as a conditional would be great.

## Describe the solution you'd like
Add /cancelaura * to the options

## Describe alternatives you've considered
I have just gone and created macros for these slots but I just ended up with a million macros for what I do.

## Additional context
Thanks a bunch if you can get this implemented!

**Comment by Snakybo** [comment]
I've been tinkering with this a while ago, will have a look to see if I can get it in a good state 👍
