### ISSUE TITLE
Issue with Clicked and action bar bindings

### ISSUE THREAD

**Issue by Hinabell** [Snakybo/Clicked#8]
I tried Clicked for a bit and it worked great and I really like it however since i started using it i ran into the same problem a couple of times. At first I thought it was maybe just beta being weird but then I tried the addon again on retail.
It happened first after starting a m+ on beta and today after installing it on retail, I logged on later on and some of my normal bindings stopped working, not reacting. The exact same 2 binds i use both on my action bar(i use elvui if that has any relevance) and bound in clicked. They are set to use healing spells on friendly unit frames and that works fine. However when I logged on and tried to attack an enemy with my normal dps spells they completely stopped working. I had to take them off my bar and put them back on. I never experienced something like this before, only after i installed Clicked in both cases so I am not sure maybe it is something in this addon causing issues. Not sure what could be triggering it though as i closed the game a couple times and I could not make it happen again, but I only just started using this addon. Usually I run clique with 0 problems.

Bindings I use in both are 1 and Q. Rest is mouse buttons and they seemed fine.

**Comment by Snakybo** [comment]
Hm interesting, I'll look into it. I've just uploaded a new version that contains a bunch of bugfixes and improved the way bindings load, if it happens again after updating please let me know as well :)

**Comment by Hinabell** [comment]
Hey! I updated Clicked today and turned it on instead of Clique to try it
some more. Logged out for dinner. Came back, mount farming, i went into a
raid and same thing happened, my spells on my action bar that share a bind
with clicked in the addon didnt work until I either move the spells or
reload. Seems a bit random and mostly happens after i log out for a while
and freshly back in, but not every time as I tried exiting game and coming
back and it worked. Again, this only ever happens with Clicked for me.

**Comment by Hinabell** [comment]
Small update, I looked at using Clicked again but the problem i have is still there. It seems like in the case of the button on my action bar i use both on there and bound in clicked sometimes becomes unresponsive, mainly when just starting to play the game or starting a m+. I can click the bind on the bar and it works but the bind itself does not. If i use the heal bind and then try the action bar bind it suddenly fixes itself.

**Comment by Snakybo** [comment]
I haven't been able to ever reproduce this, however I thoroughly checked if everything was as it should be and found something that I believe could be the cause. I made some changes there and will include that in the next version.

If you still encounter it in the next version (likely 0.11) please reopen this issue and I'll have another pass at it

**Comment by Hinabell** [comment]
The problem is still there. Tested clicked again couple of days ago, it worked fine at that time but then logged on one day, and the action bar buttons that i use in clicked for 2 healing spells/dps spells on action bar became unresponsive again. This seems to stop if i use the clicked bind. So solar wrath and lifebloom is same bind, one for only unit frame target friendly heal and solar wrath is just on action bar. Solar wrath stops working but if i use lifebloom then it starts to work after. Same if i press the other healing spell bound to both.
