### ISSUE TITLE
Global bindings

### ISSUE THREAD

**Issue by Snakybo** [Snakybo/Clicked#82]
## Is your feature request related to a problem?
Currently all bindings are saved to the selected profile, however there could be a lot of bindings that are shared between multiple characters.

## Describe the solution you'd like
An option to create a "global" binding that is shared across all characters. The binding itself would not be saved in the selected profile's database, but rather in the "global" section of the database.

**Comment by oliverfischer83** [comment]
I like that feature, but I think there should also be an exception to this. For example if all my characters have their health potion attached to key X, this would be a perfect global binding. But for some reason on my warlock I want to have my Healthstone bind to key X, then there should be an option to disable that global binding for that character profile. Or even a more passive style like overriding that global key bind by a local key bind would be fine I think.

**Comment by Snakybo** [comment]
Captured in https://github.com/Snakybo/Clicked/milestone/2

**Comment by Snakybo** [comment]
@oliverfischer83 with the current setup, you should be able to achieve that by using the multi-mode on the class load option. You can select all **but** Warlock.
