### ISSUE TITLE
Switch actionbar button based on talents.

### ISSUE THREAD

**Issue by Dajova** [Snakybo/Clicked#83]
## Is your feature request related to a problem?
Not really a problem per say, more of a convenience request.

## Describe the solution you'd like
I used to use a addon called [TalentMacros](https://www.curseforge.com/wow/addons/talentmacros), which would replace said buttons in the macro based on selected talents. I would very much like to see something like that.

## Describe alternatives you've considered
I know you can still use said macros based on conditions, but i would like to see something a bit more.... visually.

## Additional context
I use the same keybind for several abilities and it doesnt get visually displayed, so... just wanna see a option to replace the actionbar button itself with said ability when switching. 
![image](https://i.imgur.com/LPW9UV2.png)

**Comment by Snakybo** [comment]
Hi!

Currently Clicked does not use action bar buttons in any way, and it's also something I haven't looked into at all. Perhaps at some point in the future I might look into it but since Clicked does not use macro slots it might be more complex.
