### ISSUE TITLE
Raise Ally click not working

### ISSUE THREAD

**Issue by Hapie07** [Snakybo/Clicked#88]
### Describe the bug

Raise Ally is not working on my Blood DK. I have it set to it should target an alive friend/enemy, however, it they're dead, it should cast Raise Ally, however, it just contains to target them even if they're dead. It works fine using the Engineering BR, and Druid Rebirth, just not DK Raise Ally.

### Clicked Version

Clicked 1.6.7

### World of Warcraft Flavor

Shadowlands

### Testing

- [X] Yes
- [ ] No

### Reproduction Steps

Create a Target the Unit on Button 1 on a Friendly Alive unit frame
Bind Raise Ally to Button 1 on a Friendly Dead unit frame

### Screenshots

![Target alive](https://user-images.githubusercontent.com/73953708/145068217-da62ec94-63dc-496d-b3bd-088199b7ef0c.png)
![Raise ally 2](https://user-images.githubusercontent.com/73953708/145068223-92f17516-f5c4-4a96-86bb-23f46609d5f8.png)
![Raise Ally](https://user-images.githubusercontent.com/73953708/145068226-7a24d80b-2569-4a24-bff5-0ae286118717.png)

**Comment by Snakybo** [comment]
Can you open the "Status" page and show the output on there?

**Comment by Hapie07** [comment]
![image](https://user-images.githubusercontent.com/73953708/145072582-bc695d7d-281d-425d-9cad-7beca849c094.png)

**Comment by Snakybo** [comment]
Ah, yeah I remember. Targeting and casting are currently different internally so when combining them they don't work that well. I wanted to look into improving that in the future.
