### ISSUE TITLE
can't bind mod-<wheel up/down> (mac)

### ISSUE THREAD

**Issue by uncomplimentary** [Snakybo/Clicked#90]
### Describe the bug

when i try to bind mod-<wheel up/down>, it drops the mod.  mod-keypress and other modifiers work fine.

### Clicked Version

1.6.7

### World of Warcraft Flavor

Shadowlands

### Testing

- [ ] Yes
- [X] No

### Reproduction Steps

try to set mod-<wheel up/down> as the key on any binding

**Comment by nteetor** [comment]
I have also run into this problem. I get no response when binding a macro to, in my case, SHIFT + WHEEL DOWN.
