### ISSUE TITLE
Binded spell hotkey blocks action bar key from being pressed when hovering over unit frame

### ISSUE THREAD

**Issue by walkmanake** [Snakybo/Clicked#94]
### Describe the bug

I have healing spell that should work only on friendly unit frames, let's say it's binded on "4". On the same keybind ("4") on action bar i have offensive spell. And if i put mouse over enemy unit frame (target, focus, boss, etc), i can't use spell from my action bar, because addon trying to use binded healing spell even on enemies.

### Clicked Version

1.6.10

### World of Warcraft Flavor

Shadowlands

### Testing

- [X] Yes
- [ ] No

### Lua Errors

No lua errors.

### Reproduction Steps

1. Bind help spell to button you have harm spell on action bar on
2. Set cursor over enemy unit frame and press key with harm spell on action bar

### Debug Output

Version: 1.6.10
Project ID: 1
Race: Troll
Level: 60
Class: DRUID
Specialization: 102
Talents: 1/1 2/3 3/3 4/3 5/3 6/2 7/2
Mode: AnyUp

Possess Bar: disabled
Override Bar: disabled
Vehicle: disabled
Vehicle UI: disabled
Pet Battle: disabled

----- Loaded binding 1 -----
Keybind: 1
Hovercast: true
Action: macro
Identifier: clicked-button-1

/stopspelltarget
/use [@mouseover,harm,nodead] Лунный огонь

----- Loaded binding 2 -----
Keybind: SHIFT-1
Hovercast: true
Action: macro
Identifier: clicked-button-shift1

/stopspelltarget
/use [@mouseover,harm,nodead] Солнечный огонь

----- Loaded binding 3 -----
Keybind: MOUSEWHEELDOWN
Hovercast: true
Action: macro
Identifier: clicked-button-mousewheeldown

/stopspelltarget
/use [@mouseover,help,nodead] Омоложение

----- Loaded binding 4 -----
Keybind: 4
Hovercast: true
Action: macro
Identifier: clicked-button-4

/stopspelltarget
/use [@mouseover,help,nodead] Быстрое восстановление

----- Loaded binding 5 -----
Keybind: Q
Hovercast: true
Action: macro
Identifier: clicked-button-q

/stopspelltarget
/use [@mouseover,help,nodead] Снятие порчи

----- Loaded binding 6 -----
Keybind: R
Hovercast: true
Action: macro
Identifier: clicked-button-r

/stopspelltarget
/use [@mouseover,help,nodead] Озарение

----- Hovercast Attributes -----
type-clicked-button-shift1: macro
macrotext-clicked-button-mousewheeldown: /stopspelltarget
macrotext-clicked-button-mousewheeldown: /use [@mouseover,help,nodead] Омоложение
macrotext-clicked-button-1: /stopspelltarget
macrotext-clicked-button-1: /use [@mouseover,harm,nodead] Лунный огонь
macrotext-clicked-button-q: /stopspelltarget
macrotext-clicked-button-q: /use [@mouseover,help,nodead] Снятие порчи
type-clicked-button-mousewheeldown: macro
macrotext-clicked-button-shift1: /stopspelltarget
macrotext-clicked-button-shift1: /use [@mouseover,harm,nodead] Солнечный огонь
type-clicked-button-q: macro
type-clicked-button-r: macro
macrotext-clicked-button-r: /stopspelltarget
macrotext-clicked-button-r: /use [@mouseover,help,nodead] Озарение
macrotext-clicked-button-4: /stopspelltarget
macrotext-clicked-button-4: /use [@mouseover,help,nodead] Быстрое восстановление
type-clicked-button-4: macro
type-clicked-button-1: macro

----- Registered unit frames -----
Boss1TargetFrame
Boss2TargetFrame
Boss3TargetFrame
Boss4TargetFrame
Boss5TargetFrame
CompactRaidFrame1
CompactRaidFrame1Buff1
CompactRaidFrame1Buff2
CompactRaidFrame1Buff3
CompactRaidFrame1Debuff1
CompactRaidFrame1Debuff2
CompactRaidFrame1Debuff3
CompactRaidFrame1DispelDebuff1
CompactRaidFrame1DispelDebuff2
CompactRaidFrame1DispelDebuff3
ElvUF_Arena1
ElvUF_Arena2
ElvUF_Arena3
ElvUF_Arena4
ElvUF_Arena5
ElvUF_AssistUnitButton1
ElvUF_AssistUnitButton1
ElvUF_AssistUnitButton1Target
ElvUF_Boss1
ElvUF_Boss2
ElvUF_Boss3
ElvUF_Boss4
ElvUF_Boss5
ElvUF_Boss6
ElvUF_Boss7
ElvUF_Boss8
ElvUF_Focus
ElvUF_FocusTarget
ElvUF_PartyGroup1UnitButton1
ElvUF_PartyGroup1UnitButton1
ElvUF_PartyGroup1UnitButton1Pet
ElvUF_PartyGroup1UnitButton1Target
ElvUF_PartyGroup1UnitButton2
ElvUF_PartyGroup1UnitButton2
ElvUF_PartyGroup1UnitButton2Pet
ElvUF_PartyGroup1UnitButton2Target
ElvUF_PartyGroup1UnitButton3
ElvUF_PartyGroup1UnitButton3
ElvUF_PartyGroup1UnitButton3Pet
ElvUF_PartyGroup1UnitButton3Target
ElvUF_PartyGroup1UnitButton4
ElvUF_PartyGroup1UnitButton4
ElvUF_PartyGroup1UnitButton4Pet
ElvUF_PartyGroup1UnitButton4Target
ElvUF_PartyGroup1UnitButton5
ElvUF_PartyGroup1UnitButton5
ElvUF_PartyGroup1UnitButton5Pet
ElvUF_PartyGroup1UnitButton5Target
ElvUF_PartyGroup1UnitButton6
ElvUF_PartyGroup1UnitButton6
ElvUF_PartyGroup1UnitButton6Pet
ElvUF_PartyGroup1UnitButton6Target
ElvUF_Pet
ElvUF_PetTarget
ElvUF_Player
ElvUF_Raid40Group1UnitButton1
ElvUF_Raid40Group1UnitButton1
ElvUF_Raid40Group1UnitButton2
ElvUF_Raid40Group1UnitButton2
ElvUF_Raid40Group1UnitButton3
ElvUF_Raid40Group1UnitButton3
ElvUF_Raid40Group1UnitButton4
ElvUF_Raid40Group1UnitButton4
ElvUF_Raid40Group1UnitButton5
ElvUF_Raid40Group1UnitButton5
ElvUF_Raid40Group1UnitButton6
ElvUF_Raid40Group1UnitButton6
ElvUF_Raid40Group2UnitButton1
ElvUF_Raid40Group2UnitButton1
ElvUF_Raid40Group2UnitButton2
ElvUF_Raid40Group2UnitButton2
ElvUF_Raid40Group2UnitButton3
ElvUF_Raid40Group2UnitButton3
ElvUF_Raid40Group2UnitButton4
ElvUF_Raid40Group2UnitButton4
ElvUF_Raid40Group2UnitButton5
ElvUF_Raid40Group2UnitButton5
ElvUF_Raid40Group3UnitButton1
ElvUF_Raid40Group3UnitButton1
ElvUF_Raid40Group3UnitButton2
ElvUF_Raid40Group3UnitButton2
ElvUF_Raid40Group3UnitButton3
ElvUF_Raid40Group3UnitButton3
ElvUF_Raid40Group3UnitButton4
ElvUF_Raid40Group3UnitButton4
ElvUF_Raid40Group3UnitButton5
ElvUF_Raid40Group3UnitButton5
ElvUF_Raid40Group4UnitButton1
ElvUF_Raid40Group4UnitButton1
ElvUF_Raid40Group4UnitButton2
ElvUF_Raid40Group4UnitButton2
ElvUF_Raid40Group4UnitButton3
ElvUF_Raid40Group4UnitButton3
ElvUF_Raid40Group4UnitButton4
ElvUF_Raid40Group4UnitButton4
ElvUF_Raid40Group4UnitButton5
ElvUF_Raid40Group4UnitButton5
ElvUF_Raid40Group5UnitButton1
ElvUF_Raid40Group5UnitButton1
ElvUF_Raid40Group5UnitButton2
ElvUF_Raid40Group5UnitButton2
ElvUF_Raid40Group5UnitButton3
ElvUF_Raid40Group5UnitButton3
ElvUF_Raid40Group5UnitButton4
ElvUF_Raid40Group5UnitButton4
ElvUF_Raid40Group5UnitButton5
ElvUF_Raid40Group5UnitButton5
ElvUF_Raid40Group6UnitButton1
ElvUF_Raid40Group6UnitButton1
ElvUF_Raid40Group6UnitButton2
ElvUF_Raid40Group6UnitButton2
ElvUF_Raid40Group6UnitButton3
ElvUF_Raid40Group6UnitButton3
ElvUF_Raid40Group6UnitButton4
ElvUF_Raid40Group6UnitButton4
ElvUF_Raid40Group6UnitButton5
ElvUF_Raid40Group6UnitButton5
ElvUF_RaidGroup1UnitButton1
ElvUF_RaidGroup1UnitButton1
ElvUF_RaidGroup1UnitButton2
ElvUF_RaidGroup1UnitButton2
ElvUF_RaidGroup1UnitButton3
ElvUF_RaidGroup1UnitButton3
ElvUF_RaidGroup1UnitButton4
ElvUF_RaidGroup1UnitButton4
ElvUF_RaidGroup1UnitButton5
ElvUF_RaidGroup1UnitButton5
ElvUF_RaidGroup1UnitButton6
ElvUF_RaidGroup1UnitButton6
ElvUF_RaidGroup2UnitButton1
ElvUF_RaidGroup2UnitButton1
ElvUF_RaidGroup2UnitButton2
ElvUF_RaidGroup2UnitButton2
ElvUF_RaidGroup2UnitButton3
ElvUF_RaidGroup2UnitButton3
ElvUF_RaidGroup2UnitButton4
ElvUF_RaidGroup2UnitButton4
ElvUF_RaidGroup2UnitButton5
ElvUF_RaidGroup2UnitButton5
ElvUF_RaidGroup3UnitButton1
ElvUF_RaidGroup3UnitButton1
ElvUF_RaidGroup3UnitButton2
ElvUF_RaidGroup3UnitButton2
ElvUF_RaidGroup3UnitButton3
ElvUF_RaidGroup3UnitButton3
ElvUF_RaidGroup3UnitButton4
ElvUF_RaidGroup3UnitButton4
ElvUF_RaidGroup3UnitButton5
ElvUF_RaidGroup3UnitButton5
ElvUF_RaidGroup4UnitButton1
ElvUF_RaidGroup4UnitButton1
ElvUF_RaidGroup4UnitButton2
ElvUF_RaidGroup4UnitButton2
ElvUF_RaidGroup4UnitButton3
ElvUF_RaidGroup4UnitButton3
ElvUF_RaidGroup4UnitButton4
ElvUF_RaidGroup4UnitButton4
ElvUF_RaidGroup4UnitButton5
ElvUF_RaidGroup4UnitButton5
ElvUF_RaidGroup5UnitButton1
ElvUF_RaidGroup5UnitButton1
ElvUF_RaidGroup5UnitButton2
ElvUF_RaidGroup5UnitButton2
ElvUF_RaidGroup5UnitButton3
ElvUF_RaidGroup5UnitButton3
ElvUF_RaidGroup5UnitButton4
ElvUF_RaidGroup5UnitButton4
ElvUF_RaidGroup5UnitButton5
ElvUF_RaidGroup5UnitButton5
ElvUF_RaidGroup6UnitButton1
ElvUF_RaidGroup6UnitButton1
ElvUF_RaidGroup6UnitButton2
ElvUF_RaidGroup6UnitButton2
ElvUF_RaidGroup6UnitButton3
ElvUF_RaidGroup6UnitButton3
ElvUF_RaidGroup6UnitButton4
ElvUF_RaidGroup6UnitButton4
ElvUF_RaidGroup6UnitButton5
ElvUF_RaidGroup6UnitButton5
ElvUF_RaidpetGroup1UnitButton1
ElvUF_RaidpetGroup1UnitButton1
ElvUF_RaidpetGroup1UnitButton10
ElvUF_RaidpetGroup1UnitButton10
ElvUF_RaidpetGroup1UnitButton11
ElvUF_RaidpetGroup1UnitButton11
ElvUF_RaidpetGroup1UnitButton12
ElvUF_RaidpetGroup1UnitButton12
ElvUF_RaidpetGroup1UnitButton13
ElvUF_RaidpetGroup1UnitButton13
ElvUF_RaidpetGroup1UnitButton14
ElvUF_RaidpetGroup1UnitButton14
ElvUF_RaidpetGroup1UnitButton15
ElvUF_RaidpetGroup1UnitButton15
ElvUF_RaidpetGroup1UnitButton16
ElvUF_RaidpetGroup1UnitButton16
ElvUF_RaidpetGroup1UnitButton17
ElvUF_RaidpetGroup1UnitButton17
ElvUF_RaidpetGroup1UnitButton18
ElvUF_RaidpetGroup1UnitButton18
ElvUF_RaidpetGroup1UnitButton19
ElvUF_RaidpetGroup1UnitButton19
ElvUF_RaidpetGroup1UnitButton2
ElvUF_RaidpetGroup1UnitButton2
ElvUF_RaidpetGroup1UnitButton20
ElvUF_RaidpetGroup1UnitButton20
ElvUF_RaidpetGroup1UnitButton21
ElvUF_RaidpetGroup1UnitButton21
ElvUF_RaidpetGroup1UnitButton22
ElvUF_RaidpetGroup1UnitButton22
ElvUF_RaidpetGroup1UnitButton23
ElvUF_RaidpetGroup1UnitButton23
ElvUF_RaidpetGroup1UnitButton24
ElvUF_RaidpetGroup1UnitButton24
ElvUF_RaidpetGroup1UnitButton25
ElvUF_RaidpetGroup1UnitButton25
ElvUF_RaidpetGroup1UnitButton26
ElvUF_RaidpetGroup1UnitButton26
ElvUF_RaidpetGroup1UnitButton27
ElvUF_RaidpetGroup1UnitButton27
ElvUF_RaidpetGroup1UnitButton28
ElvUF_RaidpetGroup1UnitButton28
ElvUF_RaidpetGroup1UnitButton29
ElvUF_RaidpetGroup1UnitButton29
ElvUF_RaidpetGroup1UnitButton3
ElvUF_RaidpetGroup1UnitButton3
ElvUF_RaidpetGroup1UnitButton30
ElvUF_RaidpetGroup1UnitButton30
ElvUF_RaidpetGroup1UnitButton31
ElvUF_RaidpetGroup1UnitButton31
ElvUF_RaidpetGroup1UnitButton32
ElvUF_RaidpetGroup1UnitButton32
ElvUF_RaidpetGroup1UnitButton33
ElvUF_RaidpetGroup1UnitButton33
ElvUF_RaidpetGroup1UnitButton34
ElvUF_RaidpetGroup1UnitButton34
ElvUF_RaidpetGroup1UnitButton35
ElvUF_RaidpetGroup1UnitButton35
ElvUF_RaidpetGroup1UnitButton36
ElvUF_RaidpetGroup1UnitButton36
ElvUF_RaidpetGroup1UnitButton37
ElvUF_RaidpetGroup1UnitButton37
ElvUF_RaidpetGroup1UnitButton38
ElvUF_RaidpetGroup1UnitButton38
ElvUF_RaidpetGroup1UnitButton39
ElvUF_RaidpetGroup1UnitButton39
ElvUF_RaidpetGroup1UnitButton4
ElvUF_RaidpetGroup1UnitButton4
ElvUF_RaidpetGroup1UnitButton40
ElvUF_RaidpetGroup1UnitButton40
ElvUF_RaidpetGroup1UnitButton5
ElvUF_RaidpetGroup1UnitButton5
ElvUF_RaidpetGroup1UnitButton6
ElvUF_RaidpetGroup1UnitButton6
ElvUF_RaidpetGroup1UnitButton7
ElvUF_RaidpetGroup1UnitButton7
ElvUF_RaidpetGroup1UnitButton8
ElvUF_RaidpetGroup1UnitButton8
ElvUF_RaidpetGroup1UnitButton9
ElvUF_RaidpetGroup1UnitButton9
ElvUF_TankUnitButton1
ElvUF_TankUnitButton1
ElvUF_TankUnitButton1Target
ElvUF_Target
ElvUF_TargetTarget
ElvUF_TargetTargetTarget
FocusFrame
FocusFrameToT
PartyMemberFrame1
PartyMemberFrame1PetFrame
PartyMemberFrame2
PartyMemberFrame2PetFrame
PartyMemberFrame3
PartyMemberFrame3PetFrame
PartyMemberFrame4
PartyMemberFrame4PetFrame
PetFrame
PlayerFrame
TargetFrame
TargetFrameToT

----- Profile -----
TZz3onoouC8NODePP0wUSmugIMskttHrJ0ixmPMs0KeNnXbMoxG2DVDVAEi27xnRqAKwTZZq5nAp2PfslLKuxGbASaz1EI)4CCS))Z2idsd1dzDIJ)ah)HrWNnfgyJciilRdA1UnYcBZCO(CZEy7q6ry3y4HiROaIRBY3mRxVkukC4qc7qFhwZtzKWxJJyOtqwomI3nfsufMyp4lDJ9V8y74ig17YJf2N8ydBO5Sm8H64uSn5JgVUJP1hnmpQ)(or29FxmjI7r7Jd)eYcY75KqMOb6rngG2gzr(mXoMNLoHdiH8yYYHxBHXbcpkc8uwZygTjJHT)0nMoGWU1In23M4cnwmzGfpubJmK1NiJ4DxiR97COvR3VxRwT3PZ7ntAHHHyEZY7iHS6mG4ZCo1H7cvqwUu8aEVyGlEejK3h0LGD94MopP7z8Fn(7Wp)Z1)24)E8)bofXLyZidsA5tDhHpXLCB(3E(C44dHb4194V(GSfbVuHcyz2XSvQ8AUb0rh7YCce1gV7rKdgVoSDXrrPl8oDp0yN0Lw7oLojlIINeCg(VjKghKk0wqWa1FgXcm6Y2b768f80rFtCiEdMrOa)kCeYVg7eeqgKHp4rJ9zPZXDDcg8gIDw2UPR7B9Px4NQHeZgUjFBlIxAO3YhemSlmeA5l3xO(eXKS7p49jW0g(48aclR47chpVSFtztpN4JLXnTpd77tCNP6N1rb3Ci(MwIgZgqPHrzofy(rEgM9Ft3ohEq)dA2T3h63PB)UnNzaTOCbNh0tYo7lWH7thK18sBQ3j4S6LdbzU0Z56fsb9MmNXMKf20XjCLxr)sizySloenvk)ChyqueYQP5hqwXG2mmDT1UnpSn8SZOGqQRdBuYJfv1KY3YNR1iEfCg8(n0MlMpBr2Rv7dsv)TnoIlHCB2NwfBlQyqbugWIELAv1lDSLDZdNORWjLhCYDc2sml5oJwuSKsilrhjdlrRXM1QumuYIeOxKo(ddGy5jtzJ6sJsQUiuYu2r(sw5oC7feKyLMz8uqqYLILpZUiciYUC9LIG80Zowbz3NtWdjxo3cx5W4VE9FE9VF9Faf5hJV6YJh)TX)a(oyHxfGTVn(FhFf8PVp(Quv4kSJ1CxIZSeMfiWNh1ywiXDGiSCWwZXPMdJnHbMEP2vbdqImaNkBPvRwzd40vbCEsbolAfXWMTfJBFMJD0ZwsrhT8yhZFsBCrbFEK2266hqztWaKidqPXwv0kgpz95SW0Y7SWQ9ZApRn7U)8JEy3ZEwvNw3sbCki6RY9G(Maoka6l)1JuiPTCfPUL08isZKtGvH(wX1NuK1(84EMDmUiOm8KT0RUrbprS1hGI1Eg727xYfRuxHvqLtSYI2rLcOu4kwbuwhak1rYauQuVrb5jRph417uh41dYWUIkpFFR6xSW)LyT)5IlYhowKzQYQc8iQRRo2R5Icjx9uHq5YbrZDbaSxAh7vdWaKidvPAJQ6nkByLKTPSPcU8ydxQMPNQ(7OOakifq5ziqzlWaKidqrBJk6vlDBujHOORikkIIIOue)urukxefTnal8uzyk661RPx2qkQTNOGjkysH8tfmPKbt4rgpvgysJgvRu6GjQ)qkkyIcMui)ubtkzWKkiMivgyc)0U2uRSrtsoTRAkMIIPOykfXpvmLsgtHpUMNkdtPXw6LUB2yfflrXsuSKI4NkwsjJLiUL8AYDn5l(TAC9HLKXLqP4eL81WEbHuYvXwAQH2sEPaxn4wUyEfxrXvwd5k8RT2dpxrCz51K72YVe3UX1nWYk(F9lfyPGGffsrHuuiLxwiLAj2axiIpD3s7v1ELg0bqdMQvAr9Flz0o8(tWBzukVNjsOC7474HfVzpdQ0P9a(KpZ2o5FI(gCLIgjMeJcmsKogY)8eH4tCbqGRJi(5Lh9)

**Comment by Snakybo** [comment]
Yes, that is working as intended. The game doesn't allow you to "selectively" activate a button in that sense. Once you configure a button in the addon it will register itself as the thing that processes that button. If any of the conditions fail (barring the "Load conditions" as those fully disable the binding), nothing will happen as the addon cannot give control over that button back to the base game.
