### ISSUE TITLE
Disable Right Clicking on Unit Frames (during combat)

### ISSUE THREAD

**Issue by volostyle** [Snakybo/Clicked#97]
Hi, I'm switching from Clique to this addon, but I can't figure out how to disable the right click menu on unit frames when in combat ONLY. This was something I could do in Clique, but I can't figure it out with this one. As a healer, it's the worst thing in the world to accidentally right click a unit frame during intense healing only to have the context menu pop up and block half the frames. I really need to disable this during combat.

If this is possible now, please let me know! Thank you.

**Comment by Snakybo** [comment]
Hi!

I don't think this is possible at the moment.. I will look into this.

**Comment by volostyle** [comment]
![image](https://user-images.githubusercontent.com/41602737/181132917-e20c4866-657b-48f5-b858-67f3b1258990.png)

Here's what the Clique config looks like if that helps. The highlighted yellow part is what you do in Clique to prevent the right click menu from popping up during combat.

**Comment by volostyle** [comment]
Hi, any luck with this one?
